Java-Algorithm-Study/algorithm-problems

- chris-an/2.28/Boj_10828.java
- chris-an/2.28/Boj_9012.java
- chris-an/2.28/Boj_9093.java
- chris-an/home/2.28/Boj_10828.java
- chris-an/home/2.28/Boj_9012.java
- chris-an/home/2.28/Boj_9093.java
*첫 번째*(실패) 
1. 처음은 '(' , 끝은 ')' 으로 끝나야함
2. ')' 와 '('는 숫자가 동일 해야 함.
3. 괄호는 무조건 짝수여야 함.
--> 이 방식으로 했을 시에, 2번에서 이슈가 생김 
*두 번째* 
1. 앞선 첫 번째 방식 2번을 해결하기 위해서, 변수를 하나로 줄이고 if문 하나 더 추가
---
*첫 번째*
1. 입력 값 데이터를 받는다.
2. 입력 값 데이터를 sentence -> words -> word 로 분할
3. word 를 뒤에서부터 글자 하나 씩 뽑아서, 저장
---
*첫 번째*
1. 기존에 stack 방식대로 코드 작성
> 이 문제는 StringTokenizer, Bufferedreader, StringBuiler 를 처음 써봐서 적응하느라 시간이 걸렸음.
> Jungmin : Boj 9012 / Boj 9093 / Boj 10828

- jihoon/home/2.28/boj_10828.java
[문제 보러가기](https://www.acmicpc.net/problem/10828)
* 먼저 스택을 담을 배열과 마지막 요소를 가르킬 포인터를 선언하였다.
* 배열 길이는 주어지는 명령의 라인 갯수만큼 설정했다. stack으로 구현했을때 모두 push명령어가 들어오더라도 전부 수용할 수 있는 길이가 충분해야 하기 때문이다. 
* 배열 대신에 ArrayList으로 구현하면 배열 길이를 지정하지 않아도 되어서 편할 것 같은데 뭐가 더 효율이 좋은지 모르겠다.
* 처음에 입출력을 Scanner으로 해서 시간초과가 떠서 몇시간을 해멨다. 앞으로 Scanner 대신에 BufferedReader써야 겠다.
> jihoon : boj 10828 스택

- jihoon/home/2.28/boj_10828.java
- jihoon/home/2.28/boj_9012.java
[문제 보러가기](https://www.acmicpc.net/problem/9012)
* 스택을 만든다
* 글자가 '(' 와 같이 여는 기호이면 스택에 푸시한다
* 글자가 ')' 와 같이 닫는 기호일 때, 스택이 비었다면 오류를 출력한다. 그렇지 않다면 스택에서 팝한다
* 입력의 끝에 스택이 비어 있지 않다면 오류를 출력한다.
이 문제가 스택이라는 것을 미리 알고 풀었기에 빨리 접근할 수 있었다. 혼자서는 스택을 이용해서 풀 생각은 못 했을 것 같다.
> jihoon : Boj 9012 괄호

- jihoon/home/2.28/boj_10828.java
- jihoon/home/2.28/boj_9012.java
- jihoon/home/2.28/boj_9093.java
[문제 보러가기](https://www.acmicpc.net/problem/9093)
* 주어진 라인들을 공백으로 구분해 배열에 넣는다.
* 배열에 있는 단어들을 StringBuffer의 reverse 메서드를 사용해 뒤집어 출력한다.
StringBuffer는 String과는 다르게 수정이 가능하며 여러가지 메서드들이 있다.
> jihoon : boj 9093 단어 뒤집기

- yoonji/home/2.28/boj_9012.java
- `(`를 만나면 +1을 하고, `)`를 만나면 -1을 한다.
- 음수이면 `(`보다 `)`가 많은 것이므로 NO 출력하면서  반복문 중단한다.
- 모든 반복을 돌고나서 체크할 때는 0과 양수인 경우만 확인하면 된다.
처음 접근할 때 복잡하게 접근하는 바람에 자료구조를 사용하려해서 동작은 했지만, 백준 실행할 때 컴파일 에러가 떠서 갈아엎어야했다. 단순히 생각해서 접근하는 것도 필요한 것 같다.
> Yoonji : boj 9012 괄호

- yoonji/home/2.28/boj_10828.java
- yoonji/home/2.28/boj_9012.java
- yoonji/home/2.28/boj_9093.java
- StringBuilder의 `reverse`를 이용하여 단어를 뒤집는다.
- 또 다른 StringBuilder에 String을 추가하여 최종 문장을 출력한다.
- StringBuilder의 `setLength`를 사용하면 가장 효율적으로 StringBuilder를 초기화할 수 있다.
- 특정 로직을 메서드로 추출하여 어떤 동작을 의미하는지 쉽게 알수있도록 한다.
> Yoonji : boj 9093 단어 뒤집기

- yoonji/home/3.01/boj_1406.java
- yoonji/home/3.01/boj_1874.java
- `hasNext` : 다음 원소가 있는지 체크
- `hasPrevious` : 이전에 원소가 있는지 체크
- `next` : 순방향(->)으로 커서 이동
- `previous` : 역방향(<-)으로 커서 이동
- `remove` : 다음 원소 제거
> 참고 : http://www.tcpschool.com/java/java_collectionFramework_iterator
- LinkedList 자료구조를 이용해서 시도했는데, 시간초과가 계속 떠서 결국 `ListIterator`를 알게되서 사용했다.
- 스택을 사용해도 될 것 같다.
- 문제자체가 이해가 잘 안되서 구글링을 해서 이해했다. 아직도 문제만 읽어보면 이해하기 어려운 것 같다.
- 이해한 바로는
1. 수열을 입력받는다. -> input
2. 현재 값부터 해당 값까지 정수를 스택에 push한다.(오름차순) -> +
3. input값과 stack의 마지막 값이 같은 값인지 비교하여 같으면 pop, 같지 않으면 수열 만족X => NO 출력 & 종료
- 한번에 출력하기위해 StringBuilder 이용
> 머지 충돌로 인해 해결하다가 push를 해버려서 일부만 수정 후 pr 올립니다.
> yoonji: boj 1406 에디터 / boj 1874 스택 수열

- jihoon/home/2.28/boj_10828.java
- jihoon/home/2.28/boj_9012.java
- jihoon/home/2.28/boj_9093.java
- jihoon/office/3.1/boj_11899.java
> jungmin, jihoon, jiyoung : boj 11899 괄호 끼워넣기

- chris-an/home/3.02/Boj_10845.java
- chris-an/home/3.02/Boj_10866.java
- chris-an/home/3.02/Boj_1158.java
문제가 이해가 되지 않아 요세푸스 순열이 무엇인 지를 찾아봄.
커서를 이동시켜서 문제를 풀 수 있지만, 먼저 자료구조를 사용할 수 있는 방법을 찾아 봄.
자료구조 큐를 이용하는 방법이 간단하였음.
#####
---
이번 풀이 방식은 자바 내에있는 큐 자료구조를 이용해서 풀어 보았음.
---
덱 문제는 풀어 본 적이 없어, 일단 스택에서 양방향 입출력이 가능한 걸 구현한 걸 토대로
자바에 스택도 자료구조가 있으니, 덱도 자료구조가 있을 거라 생각함.
역시나 덱 자료구조도 내장되어있어. 메서드 사용법 익히면서 품.
----
> 전체적으로 오늘 문제는 직접 구현하는 시도보단 자바 내에있는 자료구조를 가지고 풀면서, 자료구조 내장함수를 익히는데 중점으로 함.
> Jungmin : Boj 1158 / Boj 10845 / Boj 10866 (merge를 하지 않고 push를해서 다시..)

- chris-an/home/3.02/Boj_10866.java
- chris-an/home/3.03/Boj_10799.java
- chris-an/home/3.03/Boj_17413.java
- chris-an/office/3.03/Programmers_42576.java
- chris-an/office/3.03/Programmers_76501.java
- chris-an/office/3.03/Programmers_81301.java
처음에는 정규식 또는 Charator.isDigit 을 사용할까 했지만, 더 쉽게 코드 작성할 수 있는 방법이 있었음.
contains으로 확인한 값을 replace로 변환. 
여기서 배열을 두 개 쓸 필요없이 숫자가 1~9까지니 인덱스 번호를 활용할 수 있다는 생각을 하여 charAt를 사용도 가능
---
일단, 이 문제는 풀지 못하였음. Hash를 사용한다는 힌트를 얻고 계속 풀이를 해보았지만 실패
이 문제는 애초에  Hash 말고 코드를 짜는 방법도 있지만 Hash 를 사용할 경우 getOfDefault 를 써주어야 코드를 쉽게 짤 수 있다.
---
...
---
문제 풀이할 때, 주의해야하는 점을 찾았다.
나와있는 테스트케이스가 다 성공했지만, 히든케이스에 막혀서 '틀렸습니다' 라고 뜸.
히든케이스는, 출력값을 미리 알고 코드를 작성할 경우를 대비하여 미연의 방지로 몇가지 히든케이스들이 존재. 
따라서, 출력값에 맞춰서 코드를 작성할 경우, 히든케이스에 막혀 틀렸을 수도 있으니, 문제로만으로 로직을 짤 수 있게 끔 습관들이기
💣   완전 주의
---
문제를 이해하고 설계하는 데에 시간을 썼던 문제고, 스택 활용도를 높일 수 있던 문제였음.
다시 풀어봐야 함.
내가 왜 이 문제를 이해를 하지 못 했는 지를 원인 분석을 함.
앞 선, 단어 뒤집기 문제 처럼 결과(그림)를 보고 해석하려는 습관이 있었음. 이 부분도 문제를 읽고 문제로만 해석을 했어야 했지만
그림을 보고 이해하려고 레이저 나간 수(?) 막대기는 아래에 몇 개가 깔리는 거지? 그건 왜 설명이 안나와 있지? 등 문제에서 요구하는 바랑 다르게 …
> Jungmin : Programmers - 숫자 문자열과 단어 / 완주하지 못한 선수 / 음양더하기,  백준 - Boj 17413 / Boj 10799

- chris-an/home/3.04/Boj_17298.java
- chris-an/home/3.04/Boj_17299.java
- chris-an/home/3.04/Boj_1935.java
Stack 으로 풀어야겠다는 생각하고 설계를 하였음. 받은 입력값을 앞에서부터 처리하는 것보다 뒤에서 처리하려고 코드설계를 함.
코드 구현 중에 깨닫게 된 점은 배열 앞에서 접근하던, 뒤에서 접근하던 스택을 인덱스로 사용할 수 있는 방법을 알지 못했다면 구현하기 힘든 거 같아보이고, N-1번을 다 비교해서 확인하기엔 O(n제곱) 이라 시간복잡도 고려하면서 풀어야함.
이번 문제를 가지고 스택에 인덱스를 담아 활용할 수 있는 점을 배움. 😭
> 다시 풀어봐야 함.
💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣💣
오큰수 문제와 동일하고 응용된 문제지만 풀지 못했다.
여러 배열을 선언 후, 여기서도 스택이 인덱싱 역할을 했는데 이 부분에서 더 나아가 생각을 못한 거 같다.
1. 먼저 최대 수열 길이를 담을 공간 만들기
2.  입력 받아온 배열
3. 스택으로 인덱싱 컨트롤 하기 
> 여기서 Stack 인덱싱처리로 입력 받은 배열의 위치를 찾아 값을 찾은 다음 해당된 값이 몇 개 인지를 확인하는 부분을 생각 못함...😭 
중위식 후위식에 대한 걸 검색해서 알아보고, 데이터데이터연산자/데이터연산자데이터 에 대한 패턴을 확인 한 뒤에 
스택으로 풀면 쉽게 풀릴 수 있을 거 같다는 생각을 함.
먼저, 피연산자, 피연산자, 연산자 규칙으로 앞쪽에서 연산 처리한 걸 다시 push 하는 형태로 로직을 설계
여러가지 방법 중, Hash 를 사용함. 문제에서 A~Z까지 임의 값을 순차적으로 값을 넣으라는 문장을 보고 가능한 걸 확인.
이후에 해쉬맵 데이터를 넣을 때 알파벳은 아스키코드를 연상 한 후에 코드 …
> Jungmin : Boj 17298  / Boj 17299 / Boj 1935

- jiyoung/home/2022-03-05/boj_10808.java
- jiyoung/home/2022-03-05/boj_10809.java
- jiyoung/home/2022-03-05/boj_1918.java
- stack을 이용해 구현하였다.
- stack에 대한 개념은 알겠는데도 문제를 풀 때 응용을 잘 못하겠다.
- 번지수를 계산하는 방법이 흥미로웠다.
- indexOf() 메소드에 대해서 알게 됐다
- indexOf()  
: 해당 문자가 처음으로 등장하는 위치를 리턴, 만약 해당 문자가 없으면 -1을 리턴한다
> Jiyoung : boj 1918 후위 표기식 / 10808 알파벳 개수 / 10809 알파벳 찾기

- jihoon/home/3.3/Boj_10799.java
- jihoon/home/3.3/Boj_17413.java
- jihoon/office/3.3/PlusPositiveNegative.java
- jihoon/office/3.3/ReplaceString.java
* 처음에 정규표현식으로 접근했다. 태그가 시작, 종료하는 위치들을 배열에 저장하고 subString을 하며 뒤집을 문자들은 뒤집고 건너뛸 문자들은 건너 뛰는 방식으로 풀었는데 loop를 두번 돌아야 하니 시간초과로 해결되지 않았다.
* for루프를 돌며 문자열이 여는 괄호, 닫는 괄호, 괄호가 아닌 경우로 구분했고 괄호가 아닌 경우 이전에 괄호가 닫혔는지 여부에 따라 괄호 안에 있는지 밖에 있는지 구분하여 풀었다.
> 주석으로 자세하게 설명했다.
* 문제 이해는 어느정도 되었으나 구현을 어떻게 할지 감이 잡히지 않아 검색으로 로직을 검색했다.
* 문제의 핵심은 닫는 괄호 ')'를 만났을 때 레이저인지 막대기 끝인지 구분하는 것이다. 
* 여는 괄호 '('를 만나면 스택에 전부 push하고 닫는 괄호 ')'를 만나면 레이저인지 막대기 끝인지 구분하여 레이저인 경우 그때까지 쌓인 스택 사이즈를 더해주고 막대기 끝이면 1을 더해준다. 
* 막대기 끝과 레이저를 구분하는 방법은 닫는 괄호를 만났을 때 그 이전 문자열이 여는 괄호인지 닫는 괄호인지 알면 된다.
> Jihoon : Boj_10799 쇠막대기 / Boj_17413 문자열 뒤집기 2

- jeongwoo/home/2022-03-03/Boj10799.java
- jeongwoo/home/2022-03-04/Boj17298.java
- jeongwoo/home/2022-03-04/Boj1935.java
1. 여는 괄호가 나오면 스택에 넣는다.
2. 닫는 괄호가 나왔는데, 이전 값이 여는 괄호라면 스택 맨 위에 있는 것을 빼고 (레이저니까) stack.size만큼 cnt에 더한다.
3. 닫는 괄호가 나왔는데, 이전 값이 여는 괄호가 아니라면 스택 맨 위를 빼고 cnt++
--- 
문제 해결하고 다른 사람 코드 보다가 잘못 올렸네요.. 
스터디에서 풀었던 문제 올리고 머지하고, 집에서 푼 문제 커밋하고 올리려고 PR 하려고 하니까 사라졌네요.........
> jeongwoo: BOJ 10799 쇠막대기

- chris-an/home/3.07/Boj_10820.java
- chris-an/home/3.07/Boj_11655.java
- chris-an/home/3.07/Boj_2743.java
문자열 여러 줄을 한 번에 입력 받을 때 처리하는 방법이 한 번에 생각이 나지 않았습니다. 
BufferedReader 는 엔터로 경계, split은 스페이스(공백), 엔터 로 경계를 나눕니다.
---
....🙄
---
알파벳 마지막 인 'z' / 'Z' 를 넘어 갈 경우 루프를 어떻게 줄 지를 생각하는 문제입니다.
아스키코드를 이용해서 코드를 짰습니다.
> Jungmin : Boj 10820 / Boj 2743 / Boj 11655

- yoonji/home/3/04/boj_17299.java
- yoonji/home/3/04/boj_1918.java
- yoonji/home/3/04/boj_1935.java
- yoonji/home/3/08/boj_11656.java
- 숫자를 만나면 스택에 넣고, 연산자를 만날 때 숫자에서 두개를 꺼내 계산을 한다.
- 계산된 값은 다시 스택에 넣는다.
- 스택의 크기는 항상 1보다 크거나 같아야 진행될 수 있다.
-소수점 둘째자리까지 반올림할 때는 `String.format()`을 이용했다. `String.format("%.2f",변수)`
- 문제를 제대로 읽지 않아서 "-20억보다 크거나 같고 20억보다 작거나 같은" 수를 고려하지 못했다.
- float이 아닌 double로 값을 계산해야 한다.
- 연산자의 우선순위를 구분하기 위한 Map 자료구조가 필요하다.
- 스택에 넣을 문자는 연산자이다. (`(` 포함)
- 단, 스택에서 pop하여 우선순위를 비교할 때 `(`를 만나면 중지해야하니, 가장 낮은 우선순위로 둔다.
- 처음에 괄호를 먼저 추가해준 후에 작업을 진행해야하는건지.. 스택을 연산자 스택, 피연산자 스택 두개 만들어야하는건지, 우선순위를 위한 Map을 일일히 다 추가해주는게 맞는건지 감이 안왔다.
- 다른 사람의 코드를 보면서 이해하였고 정리가 되었다.
- 메모리 : 14228kb , 시간: 132ms
- 크기가 n인 수열 A = A1, A2, .. , An => Ai에 대한 오등큰수 NGF(i)
- Ai가 수열 A에서 등장한 횟수 : F(Ai)
- Ai의 오등큰수 : 오른쪽에 있으면서 수열 A에서 등장한 횟수가F(Ai)보다 큰 수 중 가장 왼쪽에 있는 수
- 그런 수가 없으면 오등큰수는 -1
- NGF를 배열로 진행
- 각 값이 등장한 횟수를 따로 map에 추가
=> `시간 초과 발생`
- F를 map대신 배열의 …
> yoonji: boj 1935 후위 표기식2 / 1918 후위 표기식

- chris-an/home/3.08/Boj_10824.java
- chris-an/home/3.08/Boj_11656.java
자료형 표현범위에 대해서 다시 생각해보게 된 문제였습니다...
---
문자열 알고리즘 종류는 여러 개가 있는데, 그 중 4가지를 비교를 해보면서 사용해 본 문제였습니다.
1. 직접 정렬을 구현해서 품
2. Array.sort 를 사용한 정렬
3. Collections.sort 를 사용한 정렬
4. Comparator API 사용한 정렬
> 4가지 다 메모리와 시간 복잡도를 확인했을 때, 별반 차이가 없지만 로직상으로는 Collections.sort 가 빠르니, 다음 문자열 정렬 땐 3번을 사용할 생각입니다.
> Jungmin : Boj 10824, Boj 11656

- yoonji/office/3/08/prg_모의고사.java
- 많이 맞춘 수포자를 반환하기위해 ArrayList 생성 후 배열로 반환
- 수포자 수만큼 돌면서
- 문제 정답수만큼 돈다.
- 변수명 `checkPattern`에 대한 고민도 필요할듯 싶다.
> yoonji, Jiyoung : prg 모의고사

- yoonji/home/3/08/boj_11656.java
- yoonji/home/3/09/boj_1934.java
- yoonji/home/3/09/boj_2609.java
- 접미사 배열을 생성하기 위해 반복문을 돌며 `String.subString(startIdx, endIdx)` 사용했다.
- 사전순 정렬을 위해 알파벳 정렬을 하고 리턴한다.
- 메모리: 18588kb, 시간: 292ms
> 03.08 문제입니다.
> 1934 2609 문제는 따로 pr했으니 해당 pr에서는 무시하셔도 됩니다!
> yoonji : boj 11656 접미사 배열

- chris-an/home/3.09/Boj_10430.java
- chris-an/home/3.09/Boj_1934.java
- chris-an/home/3.09/Boj_2609.java
...
---
유클리드 호제법을 이용하여, 최대공약수를 구하여, 최대공약수를 이용하여 최소공배수를 구하였습니다.
---
위와 동일하게 접근하였습니다.
> Jungmin : Boj 10430, Boj 2609, Boj 1934

- jihoon/home/3.9/Boj_1934.java
```
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
public class Boj_10430 {
public static void main(String[] args) throws IOException {
BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));
String[] line = bf.readLine().split(" ");
int a = Integer.parseInt(line[0]);
int b = Integer.parseInt(line[1]);
int c = Integer.parseInt(line[2]);
System.out.println((a + b) % c);
System.out.println(((a % c) + (b % c)) % c);
System.out.println((a * b) % c);
System.out.println(((a % c) * (b % c)) % c);
}
}
```
유클리드 호제법을 사용해서 풀었다. 시간 복잡도는 O(log(n))
```
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
public class Boj_2609 {
private static int gcd(int a, int b) { …
```
> Jihoon : boj 10430 나머지 / boj 2609  최대 공약수와 최소 공배수/ boj 1934 최소 공배수

- chris-an/home/3.10/Boj_1929.java
- chris-an/home/3.10/Boj_1978.java
소수 구하는 기본적인 로직
으로 1,2 수를 제외하고 순차적으로 나눠서 나머지 값 여부에 따라 소수 인지 아닌지를 구분 해줍니다.
---
소수를 탐색해야할 수가 100만이 넘어가면서, 전 문제인 소수찾기처럼 하나한 완전탐색으로 찾기에는 시간복잡도가 높아서 되지 않았습니다.
그래서, 여러가지 방법을 찾아가면서 테스트를 해보았습니다.
1. 하나하나 다 확인해가면서 소수 찾는 기본적인 방법  **O(n)**
: 버퍼를 쓰더라도 시간복잡도가 굉장히 높았습니다.
2. 두 번째는 1번을 사용할 때, 실상 절반이상은 소수판별로직을 돌 필요성이 없는 수 라 반으로 나눈 상태로 진행했습니다.  **O(n/2)**
: 이것도 동일하게, 시간복잡도가 높았습니다. 
3. 세 번째는 에라토스테네스의 체라는 걸 알게 된 후, 이걸로 원하는 소수값을 출력하려 했습니다. **O(nloglogn)**
: 굉장히 빠르지만, 미리 공간을 할당하고 초기화한 상태로 시작한 점이 걸려서 다른 방법을 찾아보았습니다.
4. 네 번째는 약수를 이용하여 수학적인 접근입니다. **O(√n)**
: 소수인지 아닌지를 구분할 N 의 약수를 구한뒤, 약수를 곱하여 N이 나오도록 나열을 해보면 그 중간값이 N의 루트와 근사값이 같습니다. 고로, 루트N 까지만 소수판별로직을 돌더라도, 그 뒤에있는 수는 더이상 돌 필요없
는 무의미한 수라, 로직에서 배제시킬 수 있습니다.
> Jungmin : Boj 1978 / Boj 1929

- yoonji/home/3/10/boj_1929.java
- yoonji/home/3/10/boj_1978.java
- 두 문제 모두 `StringTokenizer`를 활용하여 입력을 받았다.
- 두 문제 모두 소수를 찾는 메서드를 활용했다.
- `isPrime` 메서드
- 1인 경우 false 리턴
- 2부터 숫자의 제곱근까지 반복 i를 돌며 i로 나누어 떨어지면 소수가 아니므로 false 리턴
- ifelse문이 잘 마무리됐다면 소수이므로 true 리턴
- M과 N을 각자 변수에 넣어줄지, stream을 이용해서 한번에 배열에 넣어줄지 고민했다. 전자가 더 효율이 높다.
- 주어진 수들 중 소수를 만날 때마다 1을 증가시킨다.
> yoonji : boj 1929 소수구하기 / 1978 소수찾기

- jihoon/home/3.10/Boj_1929.java
- jihoon/home/3.10/Boj_1978.java
- jihoon/office/3.10/Pro_carpet.java
- jihoon/office/3.10/Pro_findPrime.java
주어진 수를 돌며 소수인지 하나하나 확인하며 풀었다
에라토스테네스의 체를 이용하여 푸니 시간이 절반으로 줄었다.
하나하나 소수를 확인 할때는 18584KB / 496ms, 
에라토스테네스를 이용할 때는 20144KB / 232ms이 걸렸다
> Jihoon : boj 1978 소수 찾기 / boj 1929  소수 구하기

- jihoon/home/3.10/Boj_1929.java
- jihoon/home/3.10/Boj_1978.java
- jihoon/office/3.10/Pro_carpet.java
- jihoon/office/3.10/Pro_findPrime.java
문자열이 주어졌을 때 candidate을 하나 뽑아 조합 set에 추가한 다음에 남은 문자열에 candidate을 더해 새로운 조합을 만들어서 재귀함수로 넣어준다. 더 이상 뽑을 candidate가 없을 때까지 반복한다.
구하고자 하는 카펫의 가로,세로를 각각 alpha, beta라 하면 다음 두개의 연립 방정식을 세울 수 있다
alpha * beta = brown + yellow (노란색과 갈색 영역 넓이의 합은 전체 넓이)
(alpha - 2) * (beta - 2) = yellow (노란색 영역의 넓이는 가로와 세로에서 각각 2를 뺀 숫자의 곱)
연립방정식의 해를 풀어 정리하면 
alpha = (a + Math.sqrt(a * a - 4 * b)) / 2;
beta = a - alpha;
> 프로그래머스 소수찾기 / 프로그래머스 카펫

- yoonji/home/3/11/boj_10872.java
- yoonji/home/3/11/boj_1676.java
- yoonji/office/3/08/prg_소수찾기.java
- yoonji/office/3/10/boj_2798.java
- yoonji/office/3/10/prg_카펫.java
- dfs 알고리즘을 이용하였고, 재귀로 해결한 문제
- 문자열 길이를 깊이로 여겼다.
- 재귀를 이용할 때는 종료조건을 추가해줘야하고, 매개변수에는 재귀에서 증가하는 값과 제한값을 넣어줬다.
- but, 이 제한값도 재귀를 가장 바깥에서 호출하는 반복문에서는 문자열 길이만큼 증가한다. ("117" ->3번 반복)
- (더 짧아야하는) 세로를 기준으로 반복문을 돌면서, 전체 타일 갯수에 대한 나눠떨어지는 가로를 구한다.
- 제곱근만큼만 반복하여 반복횟수를 줄인다.
> yoonji, jiyoung : prg 소수찾기 / 카펫

- jeongwoo/home/2022-03-08/Boj10824.java
- jeongwoo/home/2022-03-08/Boj11656.java
- jeongwoo/home/2022-03-09/Boj10430.java
- jeongwoo/home/2022-03-09/Boj1934.java
- jeongwoo/home/2022-03-09/Boj2609.java
1. 오늘 소수 찾기 하면서 나왔던 substring 적용
2. 자른 값들을 List에 저장
3. Collections 사용해서 오름차순 정렬
---
1. StringTokenizer로 공백 기준으로 쪼개서 배열에 저장
2. 배열 인덱스로 접근해서 String으로 문자 합침
3. 합친 것끼리 덧셈 형식으로 더해 줌
String[] arr = br.readLine().split(" ");
이렇게 했으면 더 좋았을 것 같네요.
숫자들의 최대치를 안 봐서 int로 접근했다가 1,000,000 넘어가는 것 보고 long으로 변경했습니다.
> Jeongwoo: BOJ 11656 접미사 배열 / BOJ 10824 네 수

- yoonji/home/3/11/boj_10872.java
- yoonji/home/3/11/boj_1676.java
- yoonji/home/3/11/boj_1676_recursion.java
- yoonji/home/3/11/boj_6588.java
- yoonji/home/3/12/boj_17087.java
- yoonji/home/3/12/boj_2004.java
- yoonji/home/3/12/boj_9613.java
- yoonji/office/3/08/prg_소수찾기.java
- yoonji/office/3/10/boj_2798.java
- yoonji/office/3/10/prg_카펫.java
- 재귀로 풀었다. 
- 로직을 떠오르는대로 짜게 될 경우 시간초과가 떴다.
- 구글링 후 로직을 이해하였다. 
- for문으로 작성된 것을 팩토리얼로도 시도하였다. (통과) => 코드 길이 감소. 메모리 조금 감소. 시간 조금 증가
- 너무 깊은 for문으로 들어가거나 이해하기 힘들정도로 너무 복잡해질 때만 팩토리얼을 쓰자. (특히 문풀 외의 상황에선 대부분 사용 X)
- 소수찾기를 할 때는 이전에 팀원분이 피드백주신 `에라토스테네스의 체`를 이용하여 풀었다. (구글링)
> 자세한 해설은 주석으로 추가했습니다.
- 동일한 코드를 계속 채점해봤더니 시간이 점점 늘어나는 것을 봤다. 백준의 채점된 시간처리로 시간효율을 따지기 보다 직접 걸린 시간을 print로 찍어보는게 정확할 듯 싶다.
> yoonji : boj 10872 팩토리얼 / 1676 팩토리얼 0의 갯수/ 6588 골드바흐의 추측

- yoonji/home/3/12/boj_17087.java
- yoonji/home/3/12/boj_2004.java
- yoonji/home/3/12/boj_9613.java
- N은 1,000,000을 안넘지만 sum은 넘을 수 있음을 주의
- `StringBuilder`를 이용하여 출력했다.
> ➕  `refactoring` : ArrayList 초기화를 반복문 내로 이동 
>  - 반복문 내에서만 사용하는 변수라면, for문 내에서 생성해주자.
- 예제만을 보고 거리값들 중 min, max의 GCD를 리턴했는데, 반례를 생각해보면 최대&최솟값만 고려할 때 모든 수의 최대공약수를 고려하지 못하는 경우가 생길 것이라 판단하였다.
- 두 값끼리의 gcd를 구하는 방향으로 진행.
> yoonji : boj 9613 GCD 합 / 17087 숨바꼭질6

- jeongwoo/home/2022-03-10/Boj1929.java
- jeongwoo/home/2022-03-10/Boj1978.java
- jeongwoo/home/2022-03-11/Boj10872.java
- jeongwoo/home/2022-03-11/Boj1676.java
- jeongwoo/home/2022-03-11/Boj6588.java
- jeongwoo/home/2022-03-13/Boj17087.java
- jeongwoo/home/2022-03-13/Boj2004.java
- jeongwoo/home/2022-03-13/Boj9613.java
1. 재귀를 통해 구현
---
1. 처음에는 팩토리얼 메소드를 사용해서 구한 다음에 뒤에서부터 0의 개수를 찾으려고 했었음
2. 입력 최대값을 보면 n <= 500인데 이 경우 int의 범위를 넘어가고, long, BigInteger로도 안 됐움
3. 다른 방법을 검색해 보니까 0이 들어가려면 결과값을 소인수분해 했을 때 2, 5를 한 세트로 가지고 있으면 됨
4. 2는 5의 개수보다 많을수밖에 없어서 해당 값을 5로 몇 번 나눌 수 있는지를 찾으면 됨
5. 그러면 팩토리얼 값을 구하지 않고도 n! 말고 n을 가지고도 0이 몇 개 있는지 찾을 수 있게 된다
---
1. 4보다 큰 짝수는 두 홀수인 소수의 합으로 나타낼 수 있으니까 for문의 범위는 3부터 시작
2. 두 홀수인 소수의 합이므로 n/2까지만 돌아주면 된다
3. i의 값이 소수인 경우, n - i도 소수인지 판별해서 맞다면 출력하고, flag = true로 두고, 찾은 값이 자명하니까 바로 for문 탈출
4. flag가 false라면 못 찾은 경우니까 Goldbach's conjecture is wrong. 출력한다.
5. Goldbach's conjecture is wrong. 이거를 처리 안 해 주고 계속 맞왜틀 하고 있었다..
---
> Jeongwoo : BOJ 10872 팩토리얼 / BOJ 1676 팩토리얼 0의 개수 / BOJ 6588 골드바흐의 추측

- jihoon/home/3-12/Boj_17087.java
- jihoon/home/3-12/Boj_2004.java
- jihoon/home/3-12/Boj_9613.java
2와 5의 제곱수의 개수를 찾고 조합 개수를 구하는 공식에 따라 답을 써줬다.
이중 for루프를 돌며 두개의 숫자를 뽑은 다음 GCD함수에 넣어주었다.
문제 핵심은 2개 이상의 수들의 최대공약수를 구하는 것이다. 이전에 만들었던 GCD 함수를 이용해서 for루프를 돌아주며 구했다.
> Jihoon : Boj 2004 조합 0의 개수 / Boj 9613 GCD 합 / Boj 17087 숨바꼭질

- chris-an/home/3.12/Boj_17087.java
- chris-an/home/3.12/Boj_2004.java
- chris-an/home/3.12/Boj_9613.java
접근조차 못한 문제입니다...
어느정도 문제 이해를 위해, 조합 개념을 찾으면서  팩토리얼 0 개수 찾기 문제와 비교 후. 문제를 풀었습니다.  
> 이해하고 일단 외워야 할 거 같습니다..💣
---
일일이 for문을 돌아 gcd 값을 찾도록 설계했습니다.
---
문제가 이해가 되지 않아서, 구글링 후 문제를 풀었습니다.
여러 수의 최소공약수를 구하는 문제라 그 이후는 쉽게 풀었습니다.
> 문해력을 기르자.....😭
> Jungmin : Boj 2004 / Boj 9613 / Boj 17087

- chris-an/home/3.14/Boj_1212.java
- chris-an/home/3.14/Boj_1373.java
- chris-an/home/3.14/Boj_2089.java
2->10->8 진수 변경방법도 있지만
2->8 진수 변경방법이 있을 거 같아서 찾아서 설계를 하였습니다.
Integer 클래스에서 제공하는 함수도 있습니다.
---
윗 문제와는 반대되는 개념인데 차이는 2진법으로 바꿀 때, 앞에 인덱스 0이 생략되는 점이라
처음 설계해서 코드를 짤 땐, 반복문을 빈번하게 사용을 하여서 시간 복잡도랑 메모리 복잡도가 굉장히 높게 나왔습니다. 
따라서 Integer 클래스를 써서 코드를 작성했는데, 그게 더 복잡도 효율이 좋게 나왔습니다💣
그래서 다른 방법으로 코드를 짜야할 거 같다고 생각해서 다른 분 한 걸 참고했습니다.
> 코드 주석이 제 코드입니다.
---
일단, 접근하는데 시간이 오래걸렸습니다.
이유는 정수의 나눗셈 수학적 정의를 잘 모르는 상태에서 계속 모호하게 접근을 하다보니 코드설계가 되지 않았습니다.
블로그 다른 분들 코드를 참고했습니다.
그리고 이번에 나눗셈 정의를 찾아봤습니다. a = bg + r ( g, r 은 정수 이며 , 0 <= r < b )
이 수학적 정의를 알고 문제를 보니깐 문제 진법 변환을 어떻게 해야하는 지 눈에 보였습니다.
---
> Jungmin : Boj 1373 / Boj 1212 / Boj 2089

- jihoon/home/3-14/Boj_1212.java
- jihoon/home/3-14/Boj_1373.java
- jihoon/home/3-14/Boj_2089.java
8 = 2 ^3이기 때문에 주어진 2진수를 세 자리씩 끊어서 8진수로 변환해준다. (만약 세자리씩 안나누어지면 0으로 채워준다.)
나눈 세자리씩 8진수로 변환한다.
변환된 8진수를 순서대로 합쳐주면 변환이 끝난다.
주어진 8진수를 한 자리씩 끊어준다.
각각의 수를 3자리의 2진수로 변환한다.
변환된 2진수를 순서대로 합쳐주면 변환이 끝난다.
주어진 수를 -2로 나눠주며 나머지를 add한다.
몫이 0이 될때까지 반복하며 나머지들을 모아 쓰면 된다.
> Jihoon: boj 1373 2진수 8진수 / boj 1212 8진수 2진수 / boj 2089 -2 진수

- yoonji/home/3/14/boj_1212.java
- yoonji/home/3/14/boj_1373.java
- 2의 제곱으로 나올 수 있는 경우의 수(0,1,2,3,4,5,6,7)와 배열을 map으로 생성해놓음
- input의 각 자리값(map의 `key`값)과 매칭되는 `value` 배열을 찾아서 append한다.
- 메모리:	29688, 시간: 552
- 인덱스를 3씩 줄여나가며 String을 substring()으로 잘라서 확인한다.
- 해당 substring에 대해서 반복문을 돌면서 각 자릿수 * Math.pow(2, j) 를 곱하여 합한다.
> ⚠️ 런타임 에러 : 바깥 반복문에서 0을 포함하면 sb에 0이 추가되므로 전혀 다른 답으로 도출된다.
> yoonji : boj 1373 2진수8진수 / 1212 8진수2진수

- yoonji/home/3/14/boj_1212.java
- yoonji/home/3/14/boj_1373.java
- yoonji/home/3/15/boj_17103.java
- cnt를 구하기 위해 반복문을 도는 부분에서 `반복 종료를 N-3`으로 두어서 계속 통과되지 못했다. + 중복을 피하기위해 a>b일 때 종료하는 if문 추가
- 이와 관련하여 다른 분의 코드를 참고하여 `N의 절반까지만 돌도록 하여 반복되는 경우를 제거`하도록 수정하였고 통과하였다.
> yoonji : boj 17013 골드바흐 파티션

- jeongwoo/home/2022-03-14/Boj1212.java
- jeongwoo/home/2022-03-14/Boj1373.java
- jeongwoo/home/2022-03-14/Boj2089.java
> Jeongwoo: BOJ 1373 2진수 8진수 / BOJ 1212 8진수 2진수 / BOJ 2089 -2 진수

- jeongwoo/home/2022-03-15/Boj11005.java
- jeongwoo/home/2022-03-15/Boj17103.java
- jeongwoo/home/2022-03-16/Boj11576.java
- jeongwoo/home/2022-03-16/Boj11653.java
- jeongwoo/home/2022-03-16/Boj2745.java
> Jeongwoo: BOJ 11005 진법 변환 2 / BOJ 17103 골드바흐 파티션

- yoonji/home/3/16/boj_11576.java
- yoonji/home/3/16/boj_11653.java
- yoonji/home/3/16/boj_2745.java
- 오름차순으로 진행해야하니 작은 수부터 최대한 나눌수 있는 만큼 반복해서 나누도록 한다.
- 두가지 방법
- 방법 1: for문을 돌면서 i가 1인지 체크하고, i로 나눠떨어지면 로직 진행 후,  다시 그 값으로 돌아가서 나눠떨어지는지 체크하도록  i--한다.  (메모리  17784)
- 방법 2 (주석): while문으로 i가 1인지 체크하고 while문 내에서 for문을 돌아서 i로 나눠떨어지면 break한다. (메모리 18208)
- 주석에 추가하였습니다.
- A진법 -> 10진법 -> B진법
- 10진법에서 B진법으로 변환 후 출력 시 공백을 두고 출력한다.
> 숫자 m개가 공백을 구분으로 높은 자릿수부터 차례대로 주어진다. ??? 이것을 완벽히 이해하고 넘어갔어야하는데...
> yoonji : boj 11653 소인수분해 / 2745 진법 변환 / 11576 Base Conversation

- jihoon/home/3-16/Boj_11576.java
- jihoon/home/3-16/Boj_11653.java
- jihoon/home/3-16/Boj_2745.java
소인수 분해 문제에서 내가 푼 코드는 주석처리했고 
https://st-lab.tistory.com/152 여기를 참고해서 다시 풀었다.
> Jihoon: Boj 2745 진법 변환 / Boj 11576 base conversion / Boj 11656 소인수 분해

- chris-an/home/2.28/Boj_9012.java
- chris-an/home/3.16/Boj_11576.java
- chris-an/home/3.16/Boj_11653.java
- chris-an/home/3.16/Boj_2745.java
- chris-an/home/3.17/Boj_1463_bottomUp.java
- chris-an/home/3.17/Boj_1463_dfs.java
- chris-an/home/3.17/Boj_1463_topDown.java
전날 풀었던 진법변환2 반대로 진법변환을 하면되는 문제여서 쉽게 접근해서 풀었습니다.
---
문제 이해를 또 못했습니다.. 뭐 이렇게 문제설명이 친절하지 않는지..
하..망할 문해력
문제 이해한 뒤로는 쉽게 접근해서 풀었습니다. 
문제를 이해하려다가 블로그에서 접근방식 소스를 얻어서 풀었습니다. 
진법변환 문제는 여러 문제를 풀었는데, 다른 방식인 스택을 이용할 수 있다는 글을 보고 StringBuilder.reverse 로 변환한 값을 뽑아내는 게 아닌 스택으로 접근해서 풀이도 가능해서 마지막 변환 출력 부분을 그런식으로 코드를 짰습니다.
---
소인수분해는 알기론, 소수로 계속해서 나누는 걸로만 기억을하고 
소수 1000만개를 미리 세팅하고, 소인수분해 작업을 했습니다.
그리고 다른 분들 코드를 보았는데,
소인수분해의 정의를 제대로 잘 알고있었다면 더 쉽게 문제를 풀 수 있다는 사실을 알고,
코드를 다시 작성했습니다.
> 소인수분해 정의 : 합성수를 소수들의 곱으로 나타냅니다. 또한 모든 합성수는 소인수분해된 형태를 갖는다.
이러한 산술의 기본 정리에서 증명된 조건에 따르면, 2부터 N값을 나눠도, 나머지가 0이 되는 N값은 그 N값으로 소인수분해가 된다는 사실입니다. 
확실히 메모리랑 시간 복잡도 효율이 올라갔습니다.👍
> Jungmin : Boj 2745 / Boj 11576 / Boj 11653

- chris-an/home/3.17/Boj_1463_bottomUp.java
- chris-an/home/3.17/Boj_1463_dfs.java
- chris-an/home/3.17/Boj_1463_topDown.java
- chris-an/home/3.17/Boj_test.java
- chris-an/office/3.17/Pro_12915.java
- chris-an/office/3.17/Pro_42883.java
- chris-an/office/3.17/Pro_72410.java
- chris-an/office/3.17/Pro_86051.java
Top-down : 기본 점화식을 구한 뒤 재귀함수로 구현합니다.
Bottom-up : 재귀보다는 설계를 하기는 쉬운 거 같습니다. 반복문을 통해 구현합니다. 
DFS : 트리 형식으로  재귀함수로 구현합니다 (그림참고)
DFS 트리구조👇
> 주석으로 코드 설명 남겨놓았습니다.
---
----
> Jungmin : Programmers Pair programming / Boj 1463

- yoonji/home/3/17/boj_11726.java
- yoonji/home/3/17/boj_1463.java
처음에는 -1, /3, /2로 나누는 경우로 구분을 했다. 계속 시간초과가 떠서 찾아보니
`/6`으로 나누고 `else if /3`, `else if /2`, `else -1`로 하면 더 적은 재귀를 호출할 수 있음을 알게되었다.
- 2 x 1 : 
1  
- 2 x 2 : 
1 1 
2
- 2 x 3 : 
1 1 1
1 2
2 1
- 2 x 4 : 
1 1 1 1
1 1 2
1 2 1
2 1 1
2 2
- 2 x 5 : 
1 1 1 1 1
1 1 1 2   -> 4번
1 2 2     -> 3번
➡️ 1 -> 2 -> 3 -> 5 -> 8  : 어떠한 규칙은 찾은 느낌이었는데 fibo라고는 생각 못함
> yoonji : boj 1463 1로만들기 / 11726 2*n 타일링

- chris-an/home/3.18/Boj_11052.java
- chris-an/home/3.18/Boj_11727.java
- chris-an/home/3.18/Boj_9095.java
기본 점화식을 만들기 위해서, 생각한 로직은 주석으로 달았습니다.
점화식을 구한 뒤, 남은 구현부분은 bottom-up 으로 구현했습니다.
> 앞선 타일링과 유사해 금방 접근했습니다. 앞에 1문제는 Top-down 방식이고 이번엔 bottom-up으로 구현했습니다.
---
기본 점화식을 만들기 위해서, 생각한 로직은 주석으로 달았습니다.
위와 동일하게 점화식을 구한 뒤로는 Bottom-up 방식으로 쉽게 구현했습니다.
---
이 문제는 일반항을 구하기 위해서 규칙을 찾는데 계속해서 Bottom-up 방식으로 사고를 하기는 하는데, 경우의 수를 너무 나열을 한 뒤에, 규칙성을 찾다보니깐 꽤 힘들었습니다.
경우의 수를 나열을하는 건, dfs 같은 문제와 연결되는 dp 문제인 거 같은데.. 이 문제 같은 경우에는 dp로 사고를 해야했던 거 같습니다.
Bottom-up 을 풀 때, N 값이 증가하는 것마다 최대값을 끌고 큰 문제를 풀어야했었습니다.
확실히 이 문제를 통해서 Bottom-up 구현하는 걸 많이 배웠습니다.
> Jungmin : Boj : 11727 / Boj : 9095 / Boj : 11052

- jihoon/home/3-17/Boj_11726.java
- jihoon/home/3-17/Boj_1463.java
처음에 접근을 완전히 잘못 했다. 처음에는 숫자 2와 3만 소인수로 가질 때까지 -1을 해주고 소인수 분해해서 2와 3의 인수의 개수를 더해주려고 했다. 하지만 처음부터 빼주는 것이 아닌 2와 3으로 나누면서 중간중간에 -1을 해줘야 한다는 사실을 몰랐다...결국 다른 분의 블로그를 보고 해결했다..
https://st-lab.tistory.com/133 어떻게 저런 생각을 하지..?
처음부터 감이 안잡혀 바로 구글링..
점화식을 세우는게 관건인데 잘 못하겠다 ㅎㅎ
https://jaemin8852.tistory.com/157
> Jihoon: Boj 1463 1로 만들기 / Boj 11726 타일링

- jeongwoo/home/2022-03-17/Boj11726.java
- jeongwoo/home/2022-03-17/Boj1463.java
1. 기본 적으로 dp[n] = dp[n-1] + 1
2. 그러나 2, 3의 배수인 경우 더 적은 경우를 통해 1로 만들 수도 있으니까 dp[n/1] + 1, dp[n/3] + 1을 넣어서 더 적은 값과 비교한다.
3. 6의 배수인 경우도 있으니까 if - else if 말고 if, if로 둔다
---
1. 그림 그려서 공식 찾았다.
4. dp[n] = dp[n-1] + dp[n-2]
5. 한 번 런타임 에러가 떴는데, 이유는 dp[1], dp[2]를 초기화하고 시작했는데, 이 경우 dp = new int[n+1]로 잡아 줬기 때문에 n = 1인 경우 out ouf bounds.
6. 해결 방법 1: dp = new int[1001]
7. 해결 방법 2: dp[0] = dp[1] = 1로 초기화하고, for문을 2부터 시작.
> Jeongwoo: BOJ 1463 1로 만들기 / BOJ 11726 2xn 타일링

- chris-an/home/3.19/Boj_10844.java
- chris-an/home/3.19/Boj_15990.java
- chris-an/home/3.19/Boj_16194.java
앞선 문제와 비슷하지만, 최소값이다보니, 0으로 초기화 된 부분만 수정하여, 먼저 DP 테이블에 값을 넣고 시작하였습니다.
---
처음에는 경우의 수 규칙이있는 지 먼저 찾아보다가 없는 거 같아
이건 부분 문제로 큰 문제를 해결 해야겠다는 생각을 했습니다.
계속 트리형태로 나열 한뒤에 점화식으로 만들려고 했지만, 거기까지 생각이 닿지는 못했습니다.
> N4 : 파랑 / N5 : 빨강 / N6 : 분홍
----
2차배열로 나타내어, 자릿수와 자릿값으로 점화식을 만들 수 있다는 걸 배웠습니다.
>현재 DP를 많이 풀어보지 않은 상태에서 DP 문제 풀 땐, 오래 계속 붙들고 풀려고 해도 풀 수 있는 건 아니라는 걸  알았습니다.  
많은 문제를 접하면서 문제를 풀어나가는 방식(접근방식)을 익혀야할 거 같습니다.
> Jungmin : Boj 16194 / Boj 15990 / Boj 10844

- yoonji/home/3/19/boj_10844.java
- yoonji/home/3/19/boj_15990.java
- yoonji/home/3/19/boj_16194.java
- N개의 카드를 구매하는 최소비용을 구한다.
⚠️ Math.min()을 활용하는데, 처음 배열을 초기화하면 0이 들어가있으므로 원하는 값이 도출되지 않음.
➡️ 내부 for문을 돌기 전에 d[i]에 i팩 가격을 미리 넣어놓고, 대신 내부 for문에서는 i팩 가격을 구하는 경우까지 돌지 않아도 되므로 `for (int j=1; j<i; j++)`로 진행한다.
- `N에 대해서 0~9까지 수들 중 모든 1차이나는 경우의 수`를 `D[N]`이라 한다.
- 각 자릿수의 값 i(0~9)에 대한 경우의 수를 구해야하므로 2차원 배열 `D[N][i]`로 선언한다.
- 재귀를 이용하였다.
- 만약 자릿수가 1번째 자리라면 1번째 자리는 한가지 경우밖에 없으니 바로 리턴한다.
- 자릿수가 이미 0이 아닌 경우는 경우의 수가 구해진 자릿수+자릿값이니 로직을 타지 않는다.
- D[N]은 i = 0~9 반복문을 돌면서
- i가 0이면, `N-1`이 1인 경우 & i가 9이면 `N-1`이 8인 경우의 수로 지정하면되고,
- 그외의 경우 (else) : N번째 자리가 i면 N-1번째 자리는 i+1이거나 i-1인 경우의 수를 구해서 더해야 한다. 
- D[N] = N을 만드는 경우의 수
1. N이 7이라면, 6에는 +1, 5에는 +2, 4에는 +3
2. D[N][i] = N을 만들면서 마지막자리가 i인, 즉 i를 더하는 경우의 수
- EX) D[N][1] = N을 만들기 위해 마지막자리가 1인, 즉 1을 더하는 경우의 수(N-1, N-2, N-3을 만드는 경우 중 마지막 자리가 1이면 안되므로 i가 2,3인 경우의 수만을 구한다.) …
> yoonji : 16194 카드구매하기2 / 15990 1,2,3 더하기2

- jeongwoo/home/2022-03/19/Boj10844.java
- jeongwoo/home/2022-03/19/Boj15990.java
- jeongwoo/home/2022-03/19/Boj16194.java
* -아이디어
* 1. dp[i] = i 장 구매할 수 있는 최소 금액
* 2. 카드 i 장 구매할 수 있는 경우는 P1팩 + (i-1), P2팩 + (i-2), P3팩 + (i-3), ..., Pi팩
* 3. dp[i] = max(P1 + dp[i-1], P2 + dp[i-2], P3 + dp[i-3], ..., Pi)
* 4. 11052와 접근은 똑같지만 최소 금액이므로 dp 배열을 MAX_VALUE로 초기화한다.
---
* -아이디어
* 1. dp[i] = i를 만들 수 있는 개수
* 2. 연속된 숫자를 두 개 이상 사용하지 못한다..
* 3. dp[i]를 마지막 숫자를 기준으로 파티셔닝하면 dp[5]인 경우에 1 + 3 + 1 / 3 + 2, 2 + 1 + 2 / 2 + 3이 된다.
* 4. 중복된 숫자가 오지 못하니까 dp[5] = dp[4]에서 2, 3으로 끝나는 숫자 개수 + dp[3]에서 1, 3으로 끝나는 숫자 개수 + dp[2]에서 1, 2로 끝나는 숫자 개수의 합
---
* -아이디어
* 1. dp[i][j] = j로 시작하는 길이가 i인 계단 수의 개수
* 2. dp[3][1]: 123, 121, 101 / dp[3][2]: 232, 212, 210, 234 / dp[3][3]: 343, 345, 321, 323 / ... / dp[3][8]: 898, 878, 876 / dp[3][9]: 987, 980
* 3. 규칙을 찾아보면 dp[i][1] = dp[i-1][2] + dp[i-2][1] / dp[i][2] = dp[i-1][1] + dp[i-1][3] .. / dp[i][9] = …
> Jeongwoo: BOJ 16194 / BOJ 15990 / BOJ 10844 

- chris-an/home/3.21/Boj_11053.java
- chris-an/home/3.21/Boj_14002.java
- chris-an/home/3.21/Boj_2193.java
주석으로 접근방식을 적어놓았습니다. 
---
가장 긴 증가하는 부분 수열이라는 이름대로
주어진 A 수열에서 앞에서부터 갚을 하나씩 뽑아 증가하는 형태의 수열로 만드는 문제인 거 같아 그렇게 접근을 시도했습니다.
결과는 실패..
가장 긴 수열을 구하는 문제라, 
첫째 자리부터 쭈욱 구하면 긴 수열이되는 줄 알았는데, 아니네요...
A1부터 시작해서 차례대로 가장 긴 수열의 길이를 확인해가면서
최종적으로 N번째 기준에서 가장 긴 수열을 찾는 문제여서
두 가지 방법으로 문제를 풀었습니다.
DP 문제 같지가 않았는데? 라고 생각했는데 역시.. DP 문제였네요...
---
앞 문제를 풀고, 다른 분 블로그로 다른 방식 푸는 방법을 공부했는데,
이 문제는 그 방법 연장선인 거 같아서
앞 문제에서 추가로 스택으로 값을 뽑아주는 방법으로 구현했습니다.
> Jungmin : Boj 2193 / Boj 11053 / Boj 14002

- chris-an/home/3.22/Boj_1912.java
- chris-an/office/3.22/Boj_1699.java
- chris-an/office/3.22/Pro_12899.java
- chris-an/office/3.22/Pro_68935.java
- chris-an/office/3.22/Pro_77484.java
- chris-an/office/3.22/Pro_77884.java
https://devnuts.tistory.com/27
> 이번 DP 문제는 로직 설계 후, 점화식을 찾아 금방 접근할 수 있었습니다. 구현 쪽에서 시간이 걸렸고, 이중 포문을 쓰는 관계로 시간 초과가 떠서 for문 하나로 변경을하면서 기존 로직은 유지하되, Math.max 함수를 추가하여 변경했습니다.
점화식 설계는 점차 익숙해지지만, 구현이 더디는 걸 보완하기 위해선 시간이 오래걸려도 끝까지 풀어봐야하는 거 같습니다.
---
와 진짜 빡세네요 :(
https://devnuts.tistory.com/28?category=1009733
>접근방식은 위의 블로그에 정리해놓았습니다.
실패코드가 있는데, 아쉽게도 왜 그 코드가 틀렸는 지는 잘 모르겠네요..
DP로 다시 재접근해서 풀려고 하는데 머리가 안 돌아가서 끝까지 못풀었지만, 그래도 이번 문제를 통해서 제곱 관련하여 DP 접근을 할 수 있을 거 같습니다 !
> Jungmin : Boj 1912 / Boj 1699

- jihoon/home/3-18/Boj_11727.java
- jihoon/home/3-18/Boj_9095.java
- jihoon/home/3-21/Boj_11053.java
- jihoon/home/3-21/Boj_14002.java
- jihoon/home/3-21/Boj_2193.java
- jihoon/home/3-22/Boj_1699.java
- jihoon/home/3-22/Boj_1912.java
놀랍게도 10분만에 풀렸다... 아이패드로 먼저 dp를 써놓고 구현방식을 생각한 다음 푸니까 잘 풀렸다! 생각한 대로 나와줘서 너무 감사 ㅠㅠ
연속된 합이며 중간에 수를 건너뛸 수 없으므로 단일 반복문으로 풀었다. 
처음에 접근을 아예 잘못했다. dp가 아닌 while문으로 큰 제곱수부터 빼주었지만 무조건 큰 제곱수를 뺀다고 최소항이 되지 않는 다는 사실을 간과했다. 결국 해설을 보고 풀었다. 다음에 다시 풀라고 하면 못 풀 것 같다 ㅎㅎ
> Jihoon: Boj 1912 연속합 / Boj 1699 제곱수의 합

- yoonji/office/3/22/prg_124나라의숫자.java
- yoonji/office/3/22/prg_3진법뒤집기.java
- yoonji/office/3/22/prg_로또.java
- yoonji/office/3/22/prg_약수개수와덧셈.java
🔑 key point : 제곱근만큼 돌면서 같은 수의 약수인 경우 `+1`, 다른 수의 약수인 경우 `+2`
```java
// ★ 제곱근만큼만 돈다!!
for (int j = 1; j * j <= i; j++) {
if (j * j == i) cnt++;  // 동일 수 ex) 6*6
else if (i % j == 0) cnt+=2;  // 그외의 수 ex) 3*12 (12까지 가지 않고 +=2로 해결!)
}
```
> 주석으로 설명 추가하였습니다.
1. N을 3진법으로 변환하면서 list에 추가한다.
2. list에서 꺼내면서 `Math.pow()` 이용하여 10진법으로 변환한다. (list에서 추가 후, 꺼내는 과정에서 뒤집기가 자동으로 해결)
- `%3`의 값을 이용하면 해결되는 문제이다.
- 나머지로 나올 수 있는 값들을 배열로 만들어둔다.
- 단, 3의 배열인 수에 대해서는 처리를 따로 해야하는데, `n-1`을 한다.
3으로 나눠떨어지는 경우를 따로 처리를 해주기 위해 3의 배수들의 규칙을 찾았고
이 때 4를 붙여주면서 -1을 해줘야한다는 아이디어까지 도출되었다. 결국 처리를 해주다가 시간이 종료되었는데
3의 배수든 아니든 해당하는 나머지값을 추가해주고, 3의 배수일 경우만 -1을 하면 되었다.
> 혼자 풀었으면 못 풀었을 문제 😞
> yoonji, jeongwoo : prg 약수개수와덧셈 / 로또 / 3진법 뒤집기 / 124나라의숫자

- chris-an/home/3.23/Boj_1149.java
- chris-an/home/3.23/Boj_15988.java
- chris-an/home/3.23/Boj_2225.java
https://devnuts.tistory.com/29?category=1009733
> 접근한 방식과 전체적으로 생각한 내용을 써가면서 풀었습니다. 문제를 풀 때 사고가 유연하질 못해서 한 곳만 계속 접근했던 거 같습니다. N과 K의 규칙을 찾았다면 풀어낼 수 있었지만, 아쉽게도 K를 고정시키고 N의 개수만 확인헀네요.. 
이후에 다른 분 코드를 참고해서 부족한 부분을 찾았습니다..
---
위 문제는, 전에 풀었던 문제에 산술 오버플로만 해결하면 됐던 문제였습니다.
`1,2,3 더하기` + `1,2,3 더하기5`  => 이 두 문제를 합한 문제입니다.
> 이 문제는 메모리랑 시간 복잡도 효율이 좋지 않아 다시 한 번 풀어야할 거 같습니다.
---
https://devnuts.tistory.com/30?category=1009733
> 이 문제 풀 때, 테스트케이스를 확인하면서 문제를 이해했고,  테스트케이스 5 기준으로 로직설계를 했습니다.
이 문제는 `1로만들기` 라는 문제와 유사해서 뒤에 합할 값을 알아야하기 때문에 뒤에서 앞을 확인하는 생각으로 접근했습니다.
> Jungmin : Boj 1149 / Boj 15988 / Boj 2225

- yoonji/home/3/22/boj_1699.java
- yoonji/home/3/22/boj_1912.java
- DP[N] = 숫자 N을 만드는 제곱수들의 최소항의 개수
- i=2부터 N까지 돌면서, 
- 매번 i까지의 제곱수(`j=1~j*j<=i`)만큼 반복문을 돌면서 `DP[N]` = min(`DP[i - (제곱수)]+1`, `DP[N])`)
- `DP[i - (제곱수)]+1` : 제곱수가 들어간 dp의 배열의 값(최소항 개수) 을 이용한다.
- `DP[N])` : 1의 제곱으로 구성된 항의 개수
나름 규칙과 점화을 내려서 로직을 짰는데 통과되지 못하고 "틀렸습니다".. 아직 반례를 못찾았다.
- dp[n] = N번째 까지의 최대합
- dp[i] = i-1번째까지의 최대합+num[i]와 num[i]중 더 큰값
> yoonji : boj 1699 제곱수의 합 / 1912 연속합

- yoonji/home/3/22/boj_1699.java
- yoonji/home/3/22/boj_1912.java
- yoonji/office/3/24/prg_크레인인형뽑기게임.java
- yoonji/office/3/24/prg_키패드누르기.java
> 로직 설명은 모두 주석으로 추가하였습니다.
- 키패드 번호를 3으로 나눈 나머지가 0일 때, 1일 때, 2일 때로 구분하여 좌측, 중앙, 우측으로 나누고자 했다.
- 이때 2,5,8,0 키패드 중 0에 대한 처리를 어떻게 해줘야할지 고민했었는데 그냥 if문에서 처음에 numbers가 0인지 체크하면 해결되는 문제였다.
- 각 키패드의 index를 이용한 위치 정보는 Map과 2차원 배열 모두 가능한데, 전자는 `Map<String, Integer[]>`으로 초기화하고,값을 넣을 때마다 value에 `new Integer[]{ new Integer(0), new Integer(0) }`과 같이 넣어줘야했기 때문에 가독성이 좋지 않다. 
- 그외 접근방식에서도 2차원 배열이 더 나은 선택이라 생각한다.
- 문제에서 인형이 없어도 정상동작해야한다는 것을 잊고 문제풀기에 들어갔던 것 같다. 처음 설계 시에 모든 조건을 고려해야할 것이다.
-  `playBox`로 명명한 배열 내 `numbers.length`개의 스택을 생성하여 값을 넣어줄 때 이중 for문으로 `Stack`에 인형을 넣어주다보니 복잡했다.
- 해결할 수 있었던 과정은 직접 손으로 적으면서 반복문대로 따라가다보니 알게되었다. 처음부터 그렇게 적어보지 못한게 아쉽다!
```java
// 2. 행은 --, 각 열은 ++해서 반복을 돌면, 각 인덱스를 돌면서 스택에 push한다.
for (int i = board.length-1; i >= 0 ; i--) {
for (int j = 0; j < board[i].length; j++) { …
```
> yoonji, jihoon, jungmin : prg 키패드 누르기 / 크레인인형뽑기게임

- jihoon/home/3-23/Boj_1149.java
코드는 이전 pr에 이미 merge되어서 코멘트로 남깁니다.
```
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.StringTokenizer;
public class Boj_2225 {
public static void main(String[] args) throws IOException {
var bf = new BufferedReader(new InputStreamReader(System.in));
var st = new StringTokenizer(bf.readLine(), " ");
int N = Integer.parseInt(st.nextToken());
int K = Integer.parseInt(st.nextToken());
long[] dp = new long[N + 1];
Arrays.fill(dp, 1);
for (int i = 1; i < K; i++) {
for (int j = 1; j <= N; j++) {
dp[j] = (dp[j - 1] + dp[j]) % 1_000_000_000;
}
}
System.out.println(dp[N]);
bf.close();
}
}
```
정민님 코드 참고...
```
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import …
```
> jihoon : boj 1149 / boj 2225 / boj 15988

- chris-an/home/3.24/Boj_11057.java
- chris-an/home/3.24/Boj_1309.java
- chris-an/office/3.24/Pro_64061.java
- chris-an/office/3.24/Pro_67256.java
https://devnuts.tistory.com/31
위 블로그에 적어 놓았습니다.
---
https://devnuts.tistory.com/32
위 블로그에 적어 놓았습니다.
> `합분해` 와 비슷했던 문제라 테이블 표를 만들어서 금방 접근했습니다. 
확실히, DP는 문제 풀수록 접근하는 방법들이 쌓여 다양하게 접근을 시도해볼 수 있어서 좋은 거 같습니다.
> Jungmin : Boj 1309 / Boj 11057

- chris-an/home/3.25/Boj_1932.java
- chris-an/home/3.25/Boj_1932_2.java
- chris-an/home/3.25/Boj_2156.java
- chris-an/home/3.25/Boj_9465.java
https://devnuts.tistory.com/33?category=1009733
위의 블로그에 생각한 로직을 정리해가며 풀었습니다.
---
https://devnuts.tistory.com/34?category=1009733
위의 블로그에 생각한 로직을 정리해가며 풀었습니다.
---
https://devnuts.tistory.com/35?category=1009733
위의 블로그에 생각한 로직을 정리해가며 풀었습니다.
---
> 오늘 문제는 풀 때 다 달랐습니다.
어떤건, 로직 설계를 빨리 끝냈지만 구현 시간이 오래걸렸고,
다른 어떤 건, 로직 설계가 오래 걸렸지만, 구현이 빨랐던 문제도 있고 다양했습니다.
...ps는 새벽까지 질질 끌면 금방 지쳐서 퍼지네요ㅜ
> Jung min : Boj 9465 / Boj 2156 / Boj 1932

- chris-an/home/3.26/Boj_11054.java
- chris-an/home/3.26/Boj_11055.java
- chris-an/home/3.26/Boj_11722.java
https://devnuts.tistory.com/36
---
https://devnuts.tistory.com/37
---
https://devnuts.tistory.com/38
---
> 블로그에 접근방식과 생각하는 과정을 글로 적어 놓았습니다.
이번 문제를 다루면서 느꼈던 건, 기존에 풀었던 문제를 기반으로 코드를 추가하여 구현을 하면 전에 풀었던 문제위주의 코드가 되어 본 문제를 풀 때, 삽질을 많이하는 거 같습니다....😭
> Jungmin : Boj 11055 / Boj 11722 / Boj 11054

- jihoon/home/3-25/Boj_1932.java
해설은 주석과 같이 써놓았습니다
다른 두 문제는 답을 봐도 명확하게 이해가 가지 않아 다음에 풀어야 할 것 같습니다...
> Jihoon: boj 1932 정수 삼각형

- yoonji/home/3/23/boj_1149.java
- yoonji/home/3/23/boj_15988.java
- yoonji/home/3/23/boj_2225.java
- 앞 집에 칠한 색깔로 칠하지 않는다.
- 조건은 3개를 주었지만, 결론적으로 i-1만 신경쓰면 된다. (본인은 i-1, i+1을 모두 신경쓰려했었다..)
- 점화식
```markdown
d[i][0] = min( d[i-1][1], d[i-1][2] ) + R
d[i][1] = min( d[i-1][0], d[i-1][2] ) + G
d[i][2] = min( d[i-1][0], d[i-1][1] ) + B
```
- 점화식 : `D[i] = D[i-1] + D[i-2] + D[i-3]`
⚠️ 계산 시 dp에 저장되는 값은 int 범위를 넘으니 long[]으로 dp 초기화
> 과정 및 점화식 정의과정은 주석으로 추가하였습니다.
- 점화식을 정의 내리는 과정에서 한번 더 규칙을 찾아내야하는 게 어려웠다.
- 규칙을 찾는 과정에서
- 몇개 경우를 끄적여 본다. (`숫자로`)
- 작은 규칙이 큰 규칙에 적용된다는 것을 기억하며 이를 dp의 작은 규칙들로 큰 규칙들을 정의해나가기 위해 `식으로` 변환한다.
- 식에서 규칙을 발견한다.
> yoonji: boj 1149 RGB거리 / 15988 1,2,3더하기3 / 2225 합분해

- chris-an/home/3.26/Boj_11055.java
- chris-an/home/3.28/Boj_13398_1.java
- chris-an/home/3.28/Boj_13398_2.java
- chris-an/home/3.28/Boj_17404.java
- chris-an/home/3.28/Boj_2133.java
https://devnuts.tistory.com/39?category=1009733
----
https://devnuts.tistory.com/40?category=1009733
---
https://devnuts.tistory.com/41?category=1009733
---
> 오늘은 끝까지 제가 푼 문제가 없었네요... 결국 다른 분 코드를 보면서 이해하고, 공부했습니다. 전에 풀었던 문제에서 조건이 붙은 응용 문제였는데, 코드 로직짜기가 굉장히 힘들었습니다. 풀었던 DP문제를 다시 공부하면서 복습해야겠네요...😂
> Jungmin : Boj 13398 / Boj 2133 / Boj 17404

- yoonji/home/3/23/boj_1149.java
- yoonji/home/3/23/boj_15988.java
- yoonji/home/3/23/boj_2225.java
- yoonji/home/3/24/boj_11057.java
- yoonji/home/3/24/boj_1309.java
- DP[N] = `길이 N개의 오름차순 갯수(경우의 수)`
- 이전에 풀었던 문제(아마 boj_10844)와 유사한 로직이라 풀 수 있었던 것 같음
- 내가 직접 푼, 혹은 참고하며 푼 문제를 다시 풀어보거나 상기시켜보는 것만으로도 좋을듯함.
> 현재 주석처리 되어있는 line25에서 i가 N일 때 ans에 더해주도록 하여 아래에서 반복문을 다시 돌지 않고자 했는데 `틀렸습니다` 결과가 나온다. 이유는 아직도 모르겠다
- `D[i]`는 i번째 칸에 올 수 있는 경우의 수
- 0개를 둘 수 있는 경우, 1개를 왼쪽에/오른쪽에 둘 수 있는 경우를 구분하기위해 `2차원 배열`로 표현한다.
- `D[i][j]`는 i번째 칸에 올 수 있는 상황 j의 경우의 수
> yoonji: boj 11057 오르막수 / 1309 동물원

- chris-an/home/3.29/Boj_2309.java
- chris-an/home/3.29/Boj_3085.java
- chris-an/office/3.29/Pro_12982.java
- chris-an/office/3.29/Pro_1845.java
- chris-an/office/3.29/Pro_42889.java
- chris-an/office/3.29/Pro_86491.java
https://devnuts.tistory.com/42
> 브루트포스 문제 같이 풀었던 거 같습니다. 
내일은 다른 분들 코드를 참고해서 다듬어야할 거 같습니다. 
---
https://devnuts.tistory.com/43
> 처음에 main 문에서 다 처리하려고 하니깐 정리도 안되고 삽질을 엄청 많이 했습니다..
확실히 메서드를 따로 빼면서 정리가 된 거 같습니다 !
코드 짜면서, 이런 문제가 코테에 나오면 개인적으로 오래 걸릴 거 같다는 생각을 하게 됐네요 :(
생각보다 IDE 디버깅을 좀 해서, 그 부분을 줄이고자 많은 연습이 필요할 거 같네요.
> Jungmin : Boj 3085 / Boj 2309 / Programmers 4문제

- jeongwoo/home/2022-03/22/Boj1699.java
* -아이디어
* 1. dp[i] = i를 이룰 수 있는 제곱수의 합 중 최소 개수
* 2. i보다 작은 제곱수들을 다 비교해야 된다.
* 3. ex) 43 = 6^2 + 2^2 + 1 + 1 + 1도 있지만 5^2 + 3^2 + 3^2이 최소 개수가 된다.
* 4. 가장 작은 제곱수부터 가장 가까운 제곱수까지 비교하면서 최소 개수를 찾는다.
* 5. dp[i] = Math.min(dp[i], dp[i - j^2] + 1)
처음에 접근을 
```java        
while (n >= 1) {
n -= (int) Math.pow(Math.floor(Math.sqrt(n)), 2);
cnt++;
}
```
이런 식으로 했는데 이렇게 되면 가장 가까운 제곱수로 계산하게 돼서  43 = 6^2 + 2^2 + 1 + 1 + 1 이렇게 된다..
> Jeongwoo: BOJ 1699 제곱수의 합

- jihoon/home/3-29/Boj_2309.java
- jihoon/home/3-29/Boj_3085.java
##Boj 3085 사탕게임
문제 예제에서 주어진 예제들과 제가 임의로 넣은 값들도 다 정상적으로 출력값이 나오는데 계속 틀리다고 나옵니다 ㅠㅠ 반례를 찾아주세요...
countRowCol 메서드로 board가 주어졌을때 행과 열에 같은 색으로 주어진 사탕의 최대 갯수를 세도록 했습니다.
swapRow 메서드는 board가 주어졌을 때 인접한 행끼리 swap하는 함수입니다.
swapCol 메서드는 board가 주어졌을 때 인접한 열끼리 swap하는 함수입니다.
main메서드에서 
행에서 인접한 사탕끼리 swap하며 countRowCol 메서드를 호출하여 최대갯수를 갱신합니다.
열에서 인접한 사탕끼리 swap하며 countRowCol 메서드를 호출하여 최대갯수를 갱신합니다.
> Jihoon: Boj 2309 일곱난쟁이, Boj 3085 사탕게임

- chris-an/home/3.30/Boj_1107.java
- chris-an/home/3.30/Boj_14500.java
- chris-an/home/3.30/Boj_1476.java
- chris-an/office/3.31/Pro_17681.java
https://devnuts.tistory.com/45?category=1009733
----
https://devnuts.tistory.com/46?category=1009733
---
https://devnuts.tistory.com/47
---
> 완전탐색 문제가 익숙치 않아, 완전탐색 로직으로 생각을 잘 못하는 거 같습니다.
계속 완탐 문제를 풀 때,  알고리즘으로 풀기 보단 알고 있는 걸로 구현을 하다가 많은 예외처리를 만났던 거 같습니다... 다양한 문제 풀면서 많이 연습이 필요한 거 같습니다.
> Jungmin : Boj 1476 / Boj 1107 / Boj 14500

- jihoon/home/3-30/Boj_14500.java
- jihoon/home/3-30/Boj_1476.java
인터넷에서 약간의 도움을 받고 코드를 최대한 간단하게 짜보았다. 
도형 몇가지 경우를 빠트려서 한참 헤맸다... 도형이 모양을 미리 생각해서 배열로 만들어 놓고 도형을 옮겨가며 구했다.
도형의 경우는 다음과 같다.
> Jihoon: boj 1476 날짜 계산 / boj 14500 테트로미노

- chris-an/home/3.31/Boj_1748.java
- chris-an/home/3.31/Boj_6064.java
https://devnuts.tistory.com/48
---
https://devnuts.tistory.com/49
---
> 이번 두 문제는 문제 구현을 한 뒤에 시간초과와 메모리 초과로 인한 이슈로 여러 번 시도하면서 효율을 높이고자 로직 설계를 다시 해야하는 문제 였습니다.
두 문제를 풀 때 뭔가 익숙한 문제였지만 처음 생각했던 로직으로 풀린 건 없었습니다. 문제를 풀면서 확실히 더 다양하게 생각해볼 수 있다는 걸 알게 됐습니다. 
사고의 유연성을 기르자.....
> Jungmin : Boj 1748 / Boj 6064

- yoonji/home/4/01/boj_15649.java
- yoonji/home/4/01/boj_9095_BruteForce.java
- yoonji/office/3/31/prg_다트게임.java
- yoonji/office/3/31/prg_비밀지도.java
> 순서는 주석에 추가하였습니다.
> 문제를 푼 과정은 [해당 글](https://thisisprogrammingworld.tistory.com/183)에 정리하였습니다.
> 순서는 주석에 추가하였습니다.
풀 예정
> yoonji, jihoon: prg 다트게임 / 비밀지도

- jihoon/home/3-31/Boj_1748.java
- jihoon/office/3-31/Pro_17681.java
- jihoon/office/3-31/Pro_70129.java
처음 접근 방식은 stringbuilder, sb를 만들고 반복문으로 수를 계속 append 한다음 sb의 length을 리턴하도록 했다.
시간초과 에러가 날 줄 알았는데 메모리 초과가 떴다.
수학적으로 접근해서 자릿수가 넘어갈때 길이가 어떻게 달라지는지 계산하며 풀었다.
주어지는 수 두개를 입력받아 하나라도 2로 나눈 나머지가 1일 때는 1, 모두 다 0일때는 0으로 생각해서 풀었다.
쉽게 풀렸다.
> Jihoon: Boj 1748 수 이어쓰기 1 / 프로그래머스 이진변환 반복하기 / 프로그래머스 1차 비밀지도

- jihoon/home/4-1/Boj_15649.java
- jihoon/home/4-1/Boj_15650.java
- jihoon/home/4-1/Boj_9095_bruteForce.java
좀 구식적인 방법으로 풀었던 것 같다. 먼저 123으로 더해서 나오는 경우의 수를 나누어봤다.
>1로만 더했을 때, 
2로만 더했을 때, 
3으로만 더했을 때,
1, 2로만 더했을 때,
1, 3으로만 더했을 때,
2, 3으로만 더했을 때,
1, 2, 3으로 더해을 때
각각의 경우의 수를 더해주었다. 예를 들어 1, 2로 더했을 때 경우의 수를 세는 방법은, 이중문으로 1을 i번, 2를 j번 쓴다고 구한다음 (i+j)! / i! * j!을 계산해주었다. 즉 같은 것이 있는 수열의 갯수를 구해주면 되는 것이다.
프로그래머스 소수 찾기 과정해서 꼭같이 해주었던 경험이 있어 쉽게 접근했다. String으로 먼저 만들고 풀었는데 나중에 배열로도 풀어봐야겠다.
오히려 접근하기 어려웠던 문제... 다시 찬찬히 풀어봐야겠다.
> Jihoon: Boj 9095 123 더하기 / Boj 15649 N과 M 1 / Boj 15650 N과 M 2

- chris-an/home/4.01/Boj_15649.java
- chris-an/home/4.01/Boj_15650.java
- chris-an/home/4.01/Boj_9095_recur.java
recur 함수를 구현할 때, 재귀가 익숙하지 않아 애 먹었습니다.
그래도 베이스케이스, 구현 시 어떤식으로 값을 탐색할 것인지, 초기 첫 메서드 스타트는 어떻게 시작할 것인지의 기준을 잡고 문제에 접근하니 
이번 문제는 그래도 접근이라도 가능했던 거 같습니다.
이걸 풀 때, IDE 디버깅을 하면서 풀었는데, 이게 맞나 싶네요...
재귀함수 연습하기 위해선, 일단 구현하고 디버깅을 한동안 수시로 해야할 거 같습니다.
아직은 눈으로 하는 디버깅이 IDE 디버깅을 못따라가네요..
---
https://devnuts.tistory.com/51
아직까지도 DFS 문제 구현하는 게 쉽지 않았습니다. 
일단 재귀함수를 설계 해본 게 한 손에 뽑이니, 일단 문제를 계속 접하면서 나만의 여러 접근방법을 늘려야할 거 같습니다.
> 오늘 문제 기점으로 어떻게 처음에 접근해야 하는 지는 감이 온 거 같습니다. 문제는...그 이후에 계속 설계하고 구현해보고를 반복해서 공부해야겠네요....
> Jungmin : 1,2,3 더하기(완탐ver) / N과 M(1) / N과 M(2)

- jeongwoo/home/2022-04/01/Boj15649.java
- jeongwoo/home/2022-04/01/Boj15650.java
- jeongwoo/home/2022-04/01/Boj9095Dfs.java
- jeongwoo/home/2022-04/02/Boj15651.java
- jeongwoo/home/2022-04/02/Boj15652.java
- jeongwoo/home/2022-04/02/Boj15654.java
DFS를 하면서 느낀 점은 파라미터를 어떻게 구성할 것인지와 return을 언제 할 건지가 제일 중요한 것 같다.
나올 것 같으면서도 안 나오고...
접근 방법은 주석으로 달아놨습니다
> Jeongwoo: BOJ 9095 1, 2, 3 더하기 DFS / 15649 N과 M (1) / 15650 N과 M (2)

- yoonji/home/4/02/boj_15651.java
- yoonji/home/4/02/boj_15652.java
- yoonji/home/4/02/boj_15654.java
> 4-5문제 정도 푸니까 N과 M 같은 숫자 배치 경우의 수 문제는 어느정도 이해가 잘 되는 것 같다. 반복의 힘 👍 
이번 세 문제 모두 조건은 각자 달랐지만 `예외 추가` 혹은 `조건을 위한 배열 추가` 정도의 차이였다.
> 조건에 대한 처리는 주석으로 추가했습니다.
**➕ 공통적으로..**
재귀적으로 생각하고 반복문을 만드는 것도 처음엔 힘이 들었는데, 아래와 같이 그림을 그려보니 이해가 바로 되고 코드로 옮기는데에도 수월했다.
> yoonji: boj 15651 N과M(3) / 15652 N과M(4) / 15654 N과M(5)

- jihoon/home/4-2/Boj_15651.java
- jihoon/home/4-2/Boj_15652.java
- jihoon/home/4-2/Boj_15654.java
이제는 익숙해져서 느낌적인 느낌으로 풀수는 있는데, 남한테 설명하라고 하면 못 이해시킬 것 같다...아직 정확한 이해가 안된 것 같다.
> Jihoon: Boj 15651 / Boj 15652 / Boj 15654

- chris-an/home/4.02/Boj_15651.java
- chris-an/home/4.02/Boj_15652.java
- chris-an/home/4.02/Boj_15654.java
앞선 문제를 푼 뒤에 보니깐, 쉽게 접근이 가능했습니다. 생각 정리할 것도 없이 풀려서... 따로 블로그에 접근 플로우 정리는 안했습니다.
> Jungmin : Boj 15651 / Boj 15652 / Boj 15654

- chris-an/home/4.04/Boj_15655.java
- chris-an/home/4.04/Boj_15656.java
- chris-an/home/4.04/Boj_15657.java
접근방식은 앞선 N과 M 시리즈 문제와 구현이 동일합니다.
> 해당 문제에서 Base case 부분은 동일해야 하지만, 재귀방식은 짜기 나름인데 비슷할 거 같습니다.
> Jungmin : Boj 15655 / Boj 15656 / Boj 15657

- yoonji/home/4/05/boj_15664.java
- yoonji/office/4/05/prg_내적.java
- yoonji/office/4/05/prg_다리를지나는트럭.java
- yoonji/office/4/05/prg_숫자의표현.java
- yoonji/office/4/05/prg_체육복.java
> Yoonji, Jungmin : prg 내적 / 다리를지나는트럭 / 숫자의표현 / 체육복 

- chris-an/home/4.05/Boj_15663.java
- chris-an/home/4.05/Boj_15664.java
- chris-an/office/4.05/Pro_12924.java
- chris-an/office/4.05/Pro_42583.java
- chris-an/office/4.05/Pro_42862.java
- chris-an/office/4.05/Pro_70128.java
제가 접근한 생각은 블로그에 정리했습니다.
https://devnuts.tistory.com/58
> 전에 풀었던 문제와 비슷하여 금방 접근했던 거 같습니다.
---
> Jungmin : Boj 15663 / Boj 15664 /  👉  Yoonji, Jungmin : 프로그래머스 4문제

- yoonji/home/4/05/boj_15663.java
- yoonji/home/4/05/boj_15664.java
- `TreeSet`
- `SortedSet`을 구현합니다.
- 객체(데이터)를 중복 저장하지 않고, 오름차순으로 데이터를 정렬합니다.
- 내부적으로 `TreeMap`을 사용합니다.
- `LinkedListSet` : 
- `Set`을 구현합니다.
- 객체(데이터)를 중복 저장하지 않고, 입력한 순서대로 데이터를 저장합니다.
- 내부적으로 `LinkedHashMap`을 사용합니다.
> yoonji: boj 15663 N과 M(9) / 15664 N과 M(10)

- jeongwoo/home/2022-03/29/Boj2309.java
- jeongwoo/home/2022-03/29/Boj3085.java
- jeongwoo/home/2022-04/04/Boj15655.java
- jeongwoo/home/2022-04/04/Boj15656.java
- jeongwoo/home/2022-04/04/Boj15657.java
이전 문제들에서 크게 벗어나는 게 없었다.
풀이 방법은 주석에 있습니다.
> Jeongwoo: BOJ 15655 N과 M (6) / 15656 N과 M (7) / 15657 N과 M (8)

- yoonji/home/4/06/boj_10972.java
- yoonji/home/4/06/boj_15665.java
- yoonji/home/4/06/boj_15666.java
- `dfs` 메서드 추출을 하긴 했지만 사용자의 input 관련 부분 또한 메서드로 추출하고자 했습니다.
- 추가적으로  input을 받는 클래스인 `FastReader` 클래스를 생성하여 구현했습니다. (참고했습니다.)
- 실제적으로 메모리와 시간 모두 효율이 향상되었습니다. (백준 채점을 완전히 믿을 수는 없지만 두 지표 모두 꽤 큰 차이가 있었습니다.)
> 이번 문제에서 자료구조를 사용하지않고도 구현할 수 있는 부분을 아직 완전히 이해하지 않아서 N과M(11)은 `TreeSet`으로, `N과M(12)`는 `LinkedHashSet`으로 구현한 코드를 commit했습니다. (수정 예정)
> yoonji :  boj15665 N과M(11) / boj15666 N과M(12) 

- chris-an/home/4.06/Boj_10972.java
- chris-an/home/4.06/Boj_15665.java
- chris-an/home/4.06/Boj_15666.java
처음에는 전 문제들 풀 때처럼, 보너스 문제인 줄 알고 재귀로 당연하게 LinkedHashSet 을 이용하여 재귀루프를 돌렸는데, 
시간,메모리 복잡도가 굉장히 효율이 떨어지게 나와 접근을 잘못했다고 느꼈습니다.
중복 허용이라 LinkedHashSet 도 사용할 필요가 없었네요.. 
입력받은 수열이 중복되는 숫자가 들어올 경우에만 breakPoint 부분을 만들어 잡아주면 되는 문제인데, 
문제를 제대로 인지하지 못하고 바로 구현했던 거 같습니다.
중복된 수가 수열에 동일하게 나올 경우 전 값만 체크해주면 됩니다.
코드 수정 전
코드 수정 후
----
처음 접근했던 방식은 방문처리를 먼저 생각하여 boolean을 이용하여 입력 받은 수열의 다음 수열을 가져오려고 했습니다. 그리고, 만약 순열이 마지막인 경우를 확인해  -1 을 출력해야하는 부분을 해결해야하는데, 
예전 실수처럼 `풀었던 문제의 코드기반` 으로 코드를 주먹 구구식으로 하나씩 해결해야 하는 것 같았습니다.
그렇게 되면 나중에 구현을 다 끝내고도 예외 테스트케이스에 걸리는 경우가 생길 거 같아. 
순열에 대해서 다시 생각하고 접근방식을 찾아보았습니다.
다른 방법을 찾아보니, swap 방법이 있다는 걸 알았습니다. 
swap 으로 수동적으로 값을 교환해준다면, 문제를 해결할 수 있다는 걸 알게 되어 그 기반으로 구현했습니다.
🤔방문처리 외에 swap 방식으로 순열문제를 해결하는 걸 배웠네요:)
> Jungmin : Boj 15665 / Boj 15666 / Boj 10972

- chris-an/home/4.07/Boj_10973.java
- chris-an/home/4.07/Boj_10974.java
앞에서 풀었던 다음 순열 문제에서 반대로 생각을 해주면 쉽게 접근이 가능했지만,
다음순열에선, 오름차순 정렬을 Arrays.sort 에서 부분정렬 처리를 해주었는데 이번엔 반대로 내림차순 정렬을 해주는 부분에선
메서드를 하나 빼서, 구현을 하는 식으로 코드를 짰습니다.
부분정렬(내림차순) 내장함수를 계속 찾아보니깐 없었네요...
----
N과 M 문제와 비슷해서 방문처리로 접근을해서 풀었습니다.
> Jungmin : Boj 10973 / Boj 10974

- jihoon/home/4-7/Boj_10973.java
- jihoon/home/4-7/Boj_10974.java
- jihoon/office/4-7/Pro_1835.java
- jihoon/office/4-7/Pro_42860.java
바로 전 문제인 다음순열을 풀었던 터라 쉽게 접근 할수 있었다. boolean을 리턴하는 prevPermutations함수를 만드는 것이 예외 처리하기가 훨씬 간편했다.
처음에 접근하기가 어려웠다. 주어진 조건들을 만족하는 경우의 수가 너무 많아서 애를 먹었다. dfs 한 단어를 듣고 완전탐색으로 풀면 되겠다고 생각했다. 주어진 카카오 친구들이 8명밖에 되지 않으니 세워서 나열하는 모든 경우의 수 (순열) 즉 8! = 40320을 만들어 놓고 주어진 조건에 맞는 상황들을 필터링 해나가는 방식으로 풀었다.
> Jihoon: Boj 10973 이전순열 / Boj 10974 모든 순열 / 프로그래머스 조이스틱 / 프로그래머스 단체사진 찍기

- chris-an/home/4.08/Boj_10819.java
- chris-an/home/4.08/Boj_10971.java
- chris-an/home/4.08/Boj_6603.java
이 문제는 테스트케이스를 먼저 분석하다가 시간을 낭비했던 문제였습니다
문제 자체로 그냥 읽고 바로 해결하려고 했다면, 더 금방 풀수 있지 않았을까 합니다..
문제는 풀었지만, 수식으로 테스트케이스가지고 왜 출력값 62를 왜 찾고 있었는지 참...😂
---
예외상황 2 가지만 잡아주었으면, 기존에 알던대로 금방 풀 수 있는 문제였습니다.
메모리는 괜찮은데 시간 복잡도는 500정도 나온 거라, 
다른 분 거 코드보고 재 분석해도 좋을 거 같습니다.
---
N과 M이랑 유사해서 간단히 접근했던 문제였습니다.
> Jungmin : Boj 10819 / Boj 10971 / Boj 6603

- yoonji/home/4/06/boj_10972.java
- yoonji/home/4/07/boj_10973.java
- yoonji/home/4/07/boj_10974.java
- yoonji/office/4/07/prg_조이스틱.java
> 설명은 주석으로 추가했습니다.
- 1차원배열 `visited`를 이용해서 한 line에서의 숫자 중복을 피했다.
- 이렇게 조건문으로 중단해야하는 시점에 잘라주는게 백트래킹 기법이라고 부르는 것을 이제야 알았다.!
- 1차원 배열이 아닌 `ArrayList`에 넣고 `contains`로 체크하는 방법도 있는데 시간은 더 오래 걸리지만 간결해보였다. (사실 완전 처음에 이렇게 접근을 했었던 적이 있었다) ➡️ [링크](https://www.youtube.com/watch?v=wxQmnEKNXAM) 참고해보셔도 좋을듯합니다 😃
> yoonji: boj 10972 다음순열(0406) / 10973 이전순열 / 10974 모든순열

- yoonji/home/4/08/boj_10819.java
- yoonji/home/4/08/boj_10971.java
- yoonji/home/4/08/boj_6603.java
- 예외처리를 해줘야할 것이 많았던 문제
- 테스트케이스를 생각해보는 능력을 길러야겠음을 느꼈습니다.
> 필요한 설명은 모두 주석으로 추가하였습니다.
> yoonji: boj 6603 로또 / 10819 차이를 최대로 / 10971 외판원 순회2 

- jihoon/home/4-8/Boj_10819.java
- jihoon/home/4-8/Boj_10971.java
- jihoon/home/4-8/Boj_6603.java
먼저 갈 수 있는 도시의 순서쌍을 미리 만들어 놓고 순서대로 도시를 방문하여 비용을 구하는 방식으로 접근하였다. 처음에는 가능한 모든 순서쌍을 전부 구한 다음 비용을 계산했는데 시간과 메모리가 너무 크게 나와 순서상을 구하면서 그때 그때 비용을 계산하는 로직으로 만드려고 했다. 스스로 코드로 구현하지는 못했지만 다른 분이 쓴 코드 보고 겨우 이해하는 정도로 마무리 된 것 같다...
> Jihoon: Boj 10819 차이를 최대로 / Boj 10971 외판원 순회 2 / Boj 6603 로또

- chris-an/home/4.11/Boj_15661.java
- chris-an/home/4.11/Boj_2529_after.java
- chris-an/home/4.11/Boj_2529_before.java
앞에 풀었던 `스타트와 링크` 문제를 푼 뒤, 제가 풀었던 방식에서 복잡도 효율을 높이기 위해 리팩토링하다가 본 코드를 가지고 접근했습니다.
이 문제에선, 앞선 문제와 다르게, 한 명 이상으로 팀이 이루어질 수 있다는 점입니다.
그래서, `main` 에서 인원 수별 조합을 찾은 뒤, 능력치 최소를 구하는 `twoTeamStatsRoof` 메서드를 타는 방식으로 코드를 구현 했습니다.
그리고, 최소가 0이라, 0일 경우에는 복잡도 효율을 높이고자, ` System.exit(0)` 바로 main 메서드 종료를 시킵니다.
---
이번 문제 접근을 그냥 생각대로 주먹 구구식으로 먼저 문제를 풀었습니다.
1. 조합방식을 찾은 뒤, 조합을 구합니다.
2. 부등호 확인을 한 뒤, 조합 인덱스 가지고 부등호 대입해서 `true / false` 확인을 합니다.
3. `min / max` 를 구합니다.
여기서, 틀렸다는 말이 나와 min, max 가 아닌 정렬을 통하여 최소 최대를 출력하는 코드를 변경했습니다.
하지만, 시간복잡도가 높게 나와. 다른 분 코드를 보고 코드 수정을 했습니다.
역시, 주먹 구구식이 아닌, 재귀 roof 돌 때, break point 구간을 만들어 쓸 때 없는 재귀를 잡아주는 방법으로 설계를 했어야 합니다..
---
> Jungmin : Boj 15661 / Boj 2529 / Boj 1248

- yoonji/home/4/09/boj_14051.java
- yoonji/home/4/11/boj_2529.java
- 처음 접근할 때 부등호를 기준으로 뒤의 숫자를 결정하도록 접근을 하였다.
- 우선 dfs 문제라는 것을 인지하면 틀에 맞게 접근하는 것이 좋을 것 같다.
- 노드에 방문했을 때 깊이 끝까지 갔다가 다음 노드를 방문하는 규칙을 생각하며 로직을 짜면 딴 길로 세지 않을 것이다.
> 실버 2였음에도 어째 문제 푸는 시간은 점점 줄어들지 않는 것 같다..ㅋㅋ
> yoonji: boj 2529 부등호

- jihoon/home/4-12/Boj_11723.java
- jihoon/home/4-12/Boj_1182.java
가장 간단하게 Set을 만들고 접근했다. 메모리초과 또는 시간초과를 예상하고 풀었지만 통과는 되었다. 물론 메모리랑 시간은 각각 299964 | 1480이 들었다. System.out.println()은 시간 초과가 떴고 StringBuilder와 BufferedWriter둘다 사용해보았지만 메모리와 시간 둘다 큰 차이가 없었다. 구글링 해서 다른 방법도 찾아보면 좋을 것 같다.
123더하기 문제랑 비슷해서 쉽게 풀었다.
> Jihoon: Boj 11723 집합 / Boj 1182 부분 수열의 합

- yoonji/home/4/12/boj_11723.java
- yoonji/home/4/12/boj_1182.java
- yoonji/office/4/12/prg_뉴스클러스터링.java
- yoonji/office/4/12/prg_주식가격.java
depth를 기준으로 끝내는 것이 아닌 점에서 헤맸다.
`i`보다 `i+1`이 크거나 같든, 작든 1초가 흘렀으므로 `++`를 해주고 작을 경우는 해당 내부 for문을 `break`한다.
> 그외 : 주석으로 작성하였습니다.
> yoonji : boj 11723 집합, 1182 부분 수열의 합 / yoonji, Jungmin, Jihoon : prg 뉴스클러스터링, 주식가격

- chris-an/home/4.12/Boj_11723_after.java
- chris-an/home/4.12/Boj_11723_before.java
- chris-an/home/4.12/Boj_1182.java
다들 비슷하게 접근한 거 같습니다..
아직 비트마스크가 익숙하지 않지만 추가로 비트마스크 풀이법을 찾아보고 공부하는 정도로 만족했네요
---
루프 돌면서, S값일 경우 count를 해주어 출력합니다.
예외의 경우는 basecase 구현 때문에 S 가 0일 경우를 마지막에 1을 빼주는 식으로 처리해줍니다.
---
> Jungmin : Boj 11723 / Boj 1182

- jeongwoo/home/2022-04/08/Boj6603.java
- jeongwoo/home/2022-04/12/Boj11723.java
- jeongwoo/home/2022-04/12/Boj1182.java
처음에는 arrayList, 다음에는 hashSet을 사용했는데 arrayList가 시간면에서 조금 더 빠르더라고요. 아주 조금이긴 하지만.
hashSet이 더 나을 줄 알았는데 생각과 달라서 내부적으로 왜 그런지 검색해 봐야 되겠습니다.
---
몇 번 시도했는데 틀리길래 이유를 생각해 보니까 집합 원소로 음수도 들어가기 때문이더라고요.
dfs에서 if else로 하면 if에 들어갔다가 음수 + 양수 조합으로 다시 s를 충족할 수 있으니까...
> Jeongwoo: BOJ 11723 집합 / BOJ 1182 부분수열의 합

- chris-an/home/4.13/Boj_1260.java
- chris-an/home/4.13/Boj_13023.java
- chris-an/home/4.13/Boj_14391.java
접근을 어떻게 해야하는 지는 설계를 했는데, 구현이 어려웠습니다 :(
구현이 안됐다는 표현이 맞겠네요ㅜ
이번 기회에 이런 문제 구현을 어떤식으로 하는 지 이 문제를 통해 배운 걸로 만족해야겠네요.
----
이 두 문제를 접하면서, 그래프에 대한 지식이 부족했다는 걸 느껴서 공부하면서 문제를 풀었습니다. 앞에 풀었던 완탐 문제는 DFS와 BFS문제가 아닌, 그냥 브루트포스 와 백트래킹 문제 였네요. 이번 문제는 머리속으로 로직 설계가 안됐습니다.
다시 이 두 문제를 풀면서 DFS, BFS 공부를 해야 할 거 같습니다.
> 오늘 문제들은 뭔가 또 새로운 걸 배우는 기분이였네요😂
> Jungmin : Boj 14391 / Boj 13023 / Boj 1260

- jihoon/home/4-13/Boj_1260.java
- jihoon/home/4-13/Boj_13023.java
인접행렬을 연결된 수를 리스트로 가지는 map으로 구현했는데 이중배열로 1,0으로 표현했으면 좋았을 것 같다. 
아직 BFS문제는 더 풀어봐야 익숙해질 것 같다.
> Jihoon: Boj 13023 ABCDE / Boj 1260 DFS와 BFS

- yoonji/home/4/13/boj_1260.java
- yoonji/home/4/13/boj_13023.java
- yoonji/home/4/13/boj_14391.java
- 친구관계로 주어지는 M만큼의 관계가 있어야 1을 출력한다고 잘못 이해해서 그 부분에서 헤맸다.
- 연결된 노드간 관계가 필요하므로 1차원 배열에 ArrayList로 연결 노드를 나타냈다.
- 인접 노드를 나타내는 그래프는 배열과 List 자료구조가 있을 것이다.
- 본인은 길이 N의 배열 내에 ArrayList로 연결 관계를 나타냈다.
> yoonji: boj 13023 ABCDE / 1260 DFS와BFS

- jeongwoo/home/2022-04/13/Boj1260.java
- jeongwoo/home/2022-04/13/Boj13023.java
DFS, BFS 접한 이후로 BFS 문제는 거의 처음인가 두 번째로 풀어서 익숙하지 않았다. 
구현에 약간 애먹었다. 다시 봐야 될 것 같다.
---
문제 이해하기가 조금 까다로웠다. 주어진 조건 안에서 ABCDE, 즉 5명이 이어져 있는지를 따지는 문제였다.
지금까지 풀었던 dfs랑은 살짝 결이 다른 느낌인데 앞으로 이런 문제가 많이 나오니까 익숙해질 필요가 있다.
간선 존재 여부를 확인하는 문제는 인접 행렬을 사용하고, A와 연결된 모든 정점을 확인할 때에는 인접 리스트가 유리하다.
행렬로 하게 되면 0인 곳도 돌아야 돼서 인접 리스트를 사용하였다.
> Jeongwoo: BOJ 1260 DFS와 BFS / BOJ 13023 ABCDE 

- chris-an/home/4.14/Boj_11724.java
- chris-an/home/4.14/Boj_11724_adjArray.java
- chris-an/home/4.14/Boj_11724_bfs.java
- chris-an/home/4.14/Boj_1707_bfs.java
- chris-an/home/4.14/Boj_1707_dfs.java
- chris-an/office/4.14/Pro_12941.java
- chris-an/office/4.14/Pro_12973.java
- chris-an/office/4.14/Pro_84512.java
처음에 `연결 요소 (Connected Component)의 개수` 이 말이 무슨 말인 지 몰라서 계속 헤맸던 거 같습니다.
아직도 인접 관계가 있는 문제에 대한 접근이 어려운 거 같습니다.
이 문제를 인접 행렬 방식, BFS 방식으로 코드 분석을 추가로 해야 할 거 같습니다.
> 하.. 할 게 많네요
---
이분 그래프 라는 개념이 생소해서, 개념 공부 후 코드 구현하는 방법을 익히는 걸로 초점을 맞춰서 풀었습니다.
dfs, bfs 두 가지 방법을 알아 보았습니다.
> Jungmin : Boj 11724 / Boj 1707  ,  프로그래머스 3문제

- chris-an/home/4.15/Boj_2178.java
- chris-an/home/4.15/Boj_2667.java
- chris-an/home/4.15/Boj_4963.java
`Coordinate` 커서 역할을 하는 class 를 만들고, 사방면으로 움직일 수 있게 `dx` `dy` 전역변수로 변수 값(사방면 이동)을 초기화한 뒤, bfs를 이용하여 탐색하게끔 구현했습니다.
bfs 타입을 int로 하여 각 단지마다 집이 몇 채 있는 지 count를 해주었습니다.
---
w, h 너비와 높이를 가지고, 설계를하여 구현까지 잘 마무리 했는데, 
계속 `java.lang.ArrayIndexOutOfBoundsException` 나서 너비와 높이의 설계를 잘못 해서 헤맸던 거 같습니다. 그래도 잘 마무리 됐네요..
---
앞에 풀었던 문제를 기반으로 풀었던 문제라, 각 위치 별 거리값을 +1를 해주어, 마지막 N * M 위치 값만 출력하면 되는 문제였습니다.
> 드디어 bfs 는 적응된 거 같네요.. 다시 윗 문제들을 dfs 문제로 싹 다 풀어봐야겠네요.
> Jungmin : Boj 2667 / Boj 4963/ Boj 2178

- jeongwoo/home/2022-04/15/Boj2178.java
- jeongwoo/home/2022-04/15/Boj2667.java
- jeongwoo/home/2022-04/15/Boj4963.java
DFS로 풀어봤다.
최단 경로를 구할 때는 BFS.
distance 배열에 해당 거리를 넣어 주었다.
map을 쓰기도 하지만 그냥 뭔가 더 직관적으로 알기 쉬우니까..
> Jeongwoo: BOJ 2178 미로 찾기 / BOJ 4963 섬의 개수 / BOJ 2667 단지 번호 붙이기

- jihoon/home/4-16/Boj_7562.java
- jihoon/home/4-16/Boj_7576.java
- jihoon/home/4-18/Boj_16940.java
- jihoon/home/4-18/Boj_16947.java
- jihoon/home/4-18/Boj_16964.java
아직 혼자 풀 실력은 아닌 것 같지만 몇 문제 더 풀다보면 유형이 익숙해져서 금방 풀 것 같다.
> Jihoon: Boj 7676 / Boj 7562

- yoonji/home/4/14/boj_1707.java
- yoonji/home/4/15/boj_2667.java
- yoonji/home/4/15/boj_4963.java
두 문제 모두 비슷한 로직으로 해결할 수 있었는데,
섬의 개수는 섬이 끊길 때마다(큐가 빌 때마다) count해주었고,
단지번호는 집이 끊길 때까지 방문하는 노드마다 count해서 집의 개수를 셌고
집 연결이 끊길 때마다 count해주어 단지 갯수를 셌습니다.
> 두 문제 모두 bfs로 풀었습니다.
> yoonji: boj 4963 섬의개수 /  2667 단지번호붙이기

- jihoon/home/4-18/Boj_16947.java
- jihoon/home/4-18/Boj_16964.java
푸는데 세 시간 이상 걸렸다... dfs으로 탐색해가면서 depth를 기록해주었다. 만약 탐색해가면서 해당 역이 한번 더 등장하고 depth가 1보다 클 때(부모 자식 경우의 수를 제외해주기 위해서) 순환선으로 간주하고 순환선인 역까지의 depth를 리턴하도록 했다.
```java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.*;
public class Boj_16947 {
private static ArrayList<ArrayList<Integer>> list = new ArrayList<>();
private static Set<Integer> set = new HashSet<>();
private static StringBuilder sb = new StringBuilder();
private static int[] depths;
private static boolean flag;
private static boolean[] visited;
public static void dfs(int i, int depth) {
if (flag) return;
if (visited[i]) return;
visited[i] = true;
depths[i] = depth;
set.add(i);
for (int x : list.get(i)) {
if (flag) return;
// 간선을 타다가 순환선을 만나면 해당 역까지 거리를 리턴
if (set.contains(x) …
```
> Jihoon: Boj 16947 지하철 2호선 / Boj 16964 dfs 스페셜 저지

- chris-an/home/4.18/Boj_16947.java
https://devnuts.tistory.com/74
위 링크에 접근 방식을 간략하게 적어 놓았습니다.
이 문제 로직을 설계하는 게 쉽지 않았습니다. 다시 풀어봐야할 거 같네요.
---
> Jungmin : Boj 16947 /  스페셜저지 (~ing)

- yoonji/home/4/18/boj_16947.java
후기 및 설계는 모두 [해당 글](https://thisisprogrammingworld.tistory.com/194)에 정리하였습니다.
> yoonji : boj 16947 서울 지하철 2호선

- chris-an/home/4.19/Boj_1697.java
- chris-an/home/4.19/Boj_2146.java
- chris-an/office/4.19/Pro_1829.java
- chris-an/office/4.19/Pro_43162.java
방문처리와 큐를 이용한 BFS 로 최소값을 찾으면서, 주의 해야할 부분인 위치 범위를 신경쓰면서 구현 했습니다.
---
어느정도 설계를 한 뒤 구현을 하는 도중에, 설계가 잘못 되었다는 걸 알게 되서 멈추고 다른 분 코드를 참고해서 수정 중에 있습니다.
처음 설계는 bfs로 첫 번째 섬을 찾고, 첫 번째 섬 기준으로 다른 여럿 섬의 거리를 찾기 위한 또 다른 bfs 를 구현을 했는데, 
첫번째 섬 기준으로 최소거리를 찾을 수 있다고 생각을 해서 짠 로직인데 완전히 잘못 됐네요.
각 섬마다 섬 끼리의 거리를 확인해서 전체를 구분할 수 있게 끔 코드를 짰어야 했습니다.
> 다른 분 접근방식을 참고해서 다시 구현했습니다.
> Jungmin : Boj_1697 / Boj_2146 / 프로그래머스

- chris-an/home/4.20/Boj_13549.java
- chris-an/home/4.20/Boj_13913.java
처음에 BFS 모든 기록을 담아서 처리를 했는데, 시간초과가 떴습니다.
그 이후에, 방문 했던 걸 기억을 하면 좋을 거 같다는 생각해서 검색해보니, 동적계획법(DP) 문제를 풀 때, `역추적`하는 로직을 같이 넣어 푸는 문제가 종종 있는데, 거기서 `역추적`하는 로직을 익히면서 현 문제에 적용시켜 코드를 수정 하였더니 됐습니다.
---
이번 문제에서 `숨바꼭질 1`에서 풀었던 문제에서 살짝만 변형하면 된다고 생각했는데, 완전히 틀렸던 생각이였습니다.
이 문제를 통해서 `BFS 는 가중치가 동일할 경우에만 최단거리 알고리즘으로 구현`할 수 있는 것이고, 가중치가 다를 경우 다익스트라 알고리즘이나 다른 방식으로 문제를 해결해야 하는 것을 알게 됐습니다.
이번 코드는 `다익스트라 알고리즘`을 공부해서 구현하기 보단 일반 BFS 에서 살짝 변형 된 `0-1 BFS 방식`으로 문제를 해결 했습니다.
---
> Jungmin : Boj 13913 / Boj 13549 / Boj 14226 (~ing)

- chris-an/home/4.21/Boj_1261.java
- chris-an/home/4.21/Boj_1991.java
- chris-an/office/4.21/Pro_여행경로.java
처음에 무작정 풀어보려고 생각을 했는데 구현이 잘 안됐습니다. 그래서 관련 알고리즘에 대해서 알아보았습니다.
이진트리 순회법을 개념 잡고 의사코드로 익히다보니 이런 문제가 어느 정도 정형화된 문제라는 걸 알았습니다.
그 이후에는 리스트, 배열, 맵 푸는 방식이 있는데 저는 배열을 이용하여 구현했습니다.
---
앞에 숨바꼭질3 문제와 별반 다를 게 없었습니다. 0-1 BFS 알고리즘을 다시 복습하기 좋았습니다.
> Jungmin : Boj 1991 트리순회 /  Boj 1261 알고스팟 / 프로그래머스

- jihoon/home/4-21/Boj_1991.java
> Jihoon: boj 1991

- yoonji/home/4/15/boj_7576.java
필요한 내용은 주석으로 추가했습니다.
- 무조건 호출된 메서드 내에서 Queue에 값을 넣는다 생각했는데, 먼저 값이 1인 것을 Queue에 넣어놓을 수 있다는 것을 알았다.
- 이차원 배열에 바로 값을 업데이트하면, visited 배열도 필요없게 된다.
- 토마토를 익히는 메서드에서 한번에 max값을 찾으려 했다가 시간이 많이 걸렸다. `box`에 값을 업데이트 한뒤 마지막에 안익은 토마토가 있는지 체크하면서 max값을 찾도록 변경했다. (->visited 배열 역할도 한다.)
> yoonji : boj 7576 토마토

- jeongwoo/home/2022-04/20/Boj13913.java
- jeongwoo/home/2022-04/21/Boj1991.java
노드 클래스를 만들어서 접근하였다.
---
0-1 BFS라는 게 있어서 보는 중.
> Jeongwoo: BOJ 1991 트리 순회 / BOJ 15349 숨바꼭질 2 푸는 중

- chris-an/home/4.27/Boj_14226.java
- chris-an/office/4.26/Boj_62048.java
- chris-an/office/4.26/Pro_49994.java
숨바꼭질과 비슷하여서 접근방식은 쉽게 떠올렸지만, 메모리초과로 인해서 조건문 처리에서 시간이 오래걸렸습니다.
**시도 flow**
1. 방문처리 없이 로직 설계 (메모리초과)
2. 방문처리 1차원으로 만든 뒤 로직 다시 수정 (메모리초과)
3. 몇 가지 케이스를 써가며, 조건문을 더 타이트하게 구성하기 (메모리초과)
4. 방문처리 2차원으로 바꾼 뒤, 로직 수정 (ArrayIndexOutofBuounds error)
5. 붙여넣기 로직 시, `limit` 미만으로 If 조건 수정 (통과)
> 설계에 시간을 좀 더 투자를 했다면, 시행착오를 겪지않았을 거 같습니다...
> Jungmin : Boj 14226 / 프로그래머스

- yoonji/home/3/28/boj_17404.java
- yoonji/office/4/28/prg_괄호변환.java
- yoonji/office/4/28/prg_문자열압축.java
- 점화식 dp[i] = 이전/다음집과 다른 색으로 칠해지는 최소 비용
1. 색이 어떤 값이냐에 따라 1번째 집에 지정 색의 다른 색들은 최대비용을 넣어놓는다.
2. N번째 집의 최소비용을 구할 때 색이 i인 경우를 제외시켜야 한다. (1번째 집과 같은 색이므로)
- 재귀호출이 있으므로 최종 반환할 `answerSB`를 메서드 내에 선언해야한다.
- 처음에는 재귀호출할 메서드를 따로 뺐는데, 빼고 나니 solution 메서드에서 하는 로직이 없어서 그냥 solution 메서드를 재귀 메서드로 사용했다.
- 문제의 예제 해설을 꼼꼼히 보면 생각보다 단순한 구현 문제라고 느껴진다.
- 두 문자열을 비교하면서 반복문을 도는데, 이때 고려해야할 점은 다음과 같다.
1. 같은가?
2. 다른가?
2-1. 같은 문자열이 쌓여왔나?
2-2. 같은 문자열 없이 다른 문자열을 만났나?
- 그리고 추가로 고려해야할 점이 다를 때, `마지막 커서이냐?`를 체크해줘야 마지막 문자열까지 고려하고 작업이 마무리 될 수 있다.
> yoonji: boj 17404 RGB거리 2 / prg 괄호변환 /  prg 문자열압축 (+jungmin, jihoon)

- chris-an/home/5.02/Boj_1339.java
- chris-an/office/4.28/Pro_60057.java
다 잊어버린 `순열` 문제를 복습한 거 같습니다....
base case 부분을 어떻게 구성을 하여 최대 합에 대한 루프를 돌리지 고민을 하는 문제인 거 같습니다.
recur 로직 구현 부에서 조합을 만들고, HashMap 을 통해 조합된 알파벳에 맞는 수를 저장하여, 
최대 합을 비교하는 방식으로 문제를 풀 생각이였습니다. 
그러면, 불필요한 과정이 많아지고 시간복잡도가 높아질 거 같아. 계속 다른 고민을 했던 거 같습니다. 
최종적으로 `indexOf` 을 통해서 해당 값을 arr배열에서 가져오는 형식으로 로직을 짰습니다!
> 추가로 이번 문제는 전에 한 번 풀었던 자리 수 조합문제에서 `*=10` 을 이용한 걸, 재차 사용해서 복습된 거 같습니다.
> Jungmin : Boj 1339

- jeongwoo/home/2022-05/02/Boj1339.java
1. 들어온 단어에 대해 0~9까지 완탐으로 조합을 만든다.
2. 이후 각 알파벳에 대해 어떻게 접근해야 될까 싶어서 고민하다가 찾아보니까 indexOf로 접근하는 것을 발견했다.
3. 각 자릿수를 더할 때 pow를 사용했더니 시간초과가 났었다.
> Jeongwoo: BOJ 1339 단어 수학

- jihoon/home/5-week1/Boj_1339.java
- jihoon/home/5-week1/Boj_1339_2.java
시간초과가 나서 애를 먹었던 문제였다. 처음 설계할 때 백트레킹으로 가능한 모든 수의 순서를 만든 다음 하나씩 비교해가면서 큰값으로 갱신하도록 로직을 짰다. 최대 시간 복잡도는 10! 이므로 시간초과가 안날것이라 생각했지만 계속 시간초과가 났다... 알고보니 Math.pow() 함수가 문제였다. 결국 for루프로 돌아 해결하긴 했지만 시간이 3초가 넘어갈 정도로 많이 나왔다.. 두 번째 방법은 검색을 통해 알아냈다.
> ### countAlphabets()
> 주어진 단어에서 하나씩 알파벳을 set에 넣어 주어진 알파벳 총 갯수를 센다.
---
> ### makeNumbers()
> 알파벳 총 갯수만큼 9부터 수들을 만든다. ex) 만약 알파벳 갯수가 4개라면 9,8,7,6 생성
---
> ### dfs()
> makeNumbers()에서 생성한 수들의 순서를 바꿔 가능한 모든 순열을 구한다.
---
> ### calcuateSum()
> dfs() 메서드에서 순열을 구할때마다 호출되며 HashMap을 이용해 각 알파벳들을 숫자로 1:1 매칭한뒤에 숫자합을 계산하여 최댓값을 갱신한다.
> Jihoon: Boj 1339 단어수학

- yoonji/home/5/02/boj_1339.java
1. num이라는 배열에 depth에 따라 숫자 0~9를 모두 다른 경우의 수로 넣는다.
2. 깊이가 현재 문자열들의 전체 알파벳 수가 되면 (중복허용x) 모두 채울수 있으니까
3. 모든 문자열을 반복문 돌면서, 각 문자열에서 10을 곱해나가면서 (특정 문자와 대칭되는 숫자를 indexOf로 찾고 이를 num배열의 index로 숫자와 매칭시켜) 특정 알파벳에 매칭되는 숫자를 더해간다.
- 같은 알파벳에 대해 같은 숫자 처리를 해줘야해서 풀수록 복잡하게 풀어가게 되었는데, 풀이를 찾아보니 문자와 배열의 `index`를 이용하면 된다는 것을 알았다.
> [FEAT] yoonji: boj 1339 단어수학

- jihoon/home/5-week1/Boj_14225.java
로직은 아주 간단하게 풀렸습니다. 백트래킹으로 모든 부분수열을 구한 다음 set에 합을 넣고 while문으로 정답을 구했습니다. 
의외로 조합을 이용해서 부분 수열을 구하는 부분에서 막혔습니다. 역시 기억력은 짧은 것 같습니다. 아니면 아직까지도 정확하게 재귀로 순열과 조합을 구하는 부분을 완벽하게 이해를 못 한 것 같습니다..
> # 수정
모든 조합을 구할 필요없이 sum변수로 합만 관리하면 되므로 기존 arrayList에서  int sum을 인자로 받도록 추가해주었다.
> Jihoon: boj 14225 부분 수열의 합

- chris-an/home/5.02/Boj_1339.java
- chris-an/home/5.04/Boj_14225.java
- chris-an/office/5.03/Pro_거리두기확인하기.java
확실히 조합을 만드는 과정이 익숙하지 않았던 거 같습니다.
몇 개의 숫자 중에서, 몇 개를 한정지어 조합을 만드는 건 기억하는데, 한 길이의 모든 조합을 출력하는 게 익숙하지 않아 애 먹었습니다.
dfs 부분의 조합 만드는 건, 
for문 루프 안에서 dfs를 돌려 visited = true / false를 컨트롤 하지 않고, dfs 두개를 가지고 백트래킹을 구현했습니다.
> ps 풀맛나네요. 크 패드 최고
> Jungmin : Boj 14225

- jihoon/home/4-15/Boj_14888.java
+-*/ 를 갯수에 따라 모두 배열에 넣어놓은뒤 순열을 이용해 모든 경우의 수를 구하고 최대 최소를 갱신하는 방법으로 풀었습니다
> Jihoon: boj 14888 연산자 끼워넣기

- yoonji/home/5/boj_14225_03.java
- yoonji/office/5/03/prg_거리두기확인하기.java
- yoonji/office/5/03/prg_메뉴리뉴얼.java
- 처음에는 `Set` 자료구조를 사용해서 해결하려 했는데, 복잡해지는 느낌이 들어서 배열을 이용했습니다.
- `isSubSequence` 배열에 모든 구해지는 부분수열의 index를 true로 바꾸고, 앞에서부터 찾으면서 false를 만나면 그 값을 출력하고 종료했습니다.
> 어제 결국 해결하고 끝났는데 다시 수정 전 상태인 제 코드로 해결하려니 결국 통과가 안되네요.. 정우님이 올려주시면 토대로 다시 수정해보겠습니다
➡️ 해결 및 수정 완료 (commit c6915ce)
1. `places`의 각 행에 대해 방문한다.
- 한 행에서 각 문자열에 대해 방문하며 `P`를 만나면 bfs(현재 x, 현재 y, `plcaes`의 한 행)를 호출
- bfs 로직에서는
- `xyQue`를 생성해서 큐가 빌때까지 반복하는데
- 상하좌우에 대해 방문하며 조건 2가지를 처리한다. (시작한 지점의 x,y이냐 + 범위를 벗어나지 않았느냐)
- 위치값이 `P`이고 맨해튼 거리 내에 있으면 0을 리턴 (거리두기 지키지 않음)
- 위치값이 `O`이면서 시작지점에서 x+y 거리가 2 미만에 있는 `O`이면 큐에 등록
2. 모든 로직이 끝나고 나면 조건 2가지 처리가 필요하다. 
> 주석으로 추가하였습니다.
> yoonji: boj 14225 부분수열의합 / yoonji&jeongwoo: prg 거리두기 확인하기 & 메뉴 리뉴얼

- yoonji/home/5/boj_14225_03.java
- yoonji/home/5/boj_14888_04.java
- yoonji/office/5/03/prg_거리두기확인하기.java
- yoonji/office/5/03/prg_메뉴리뉴얼.java
- dfs를 이용하였고, 제한된 깊이까지 간 경우 합에 대해 max와 min을 비교하여 넣는 식으로 답을 구해나갔습니다.
> yoonji: boj 14888 연산자 끼워넣기

- jeongwoo/home/2022-05/03/Boj14225.java
- jeongwoo/office/2022-05/03/Pro72411.java
- jeongwoo/office/2022-05/03/Pro81302.java
접근 자체는 어렵지 않았는데 부분 수열의 합의 집합에서 1이 없는 경우와 같은 예외 상황을 생각 못 해서 몇 번 재시도했었다.
> Jeongwoo: BOJ 14225 부분수열의 합 / 프로그래머스 72411 메뉴 리뉴얼 /  프로그래머스 81302 거리두기 확인하기

- yoonji/home/5/boj_15658_05.java
- yoonji/home/5/boj_16197_05.java
> 어제 푼 '연산자끼워넣기'와 완전히 동일 로직입니다. 
> 위 문제가 동일 문제라 한 문제 더 풀었습니다.
- row와 column을 x, y로 생각하면서 풀어서 그 부분에서 헤맸습니다. 
- 그 외에는 그렇게 어렵지 않았고 bfs로 풀었습니다.
> yoonji : 15658 연산자끼워넣기2 / 16197 두 동전

- chris-an/home/5.06/Boj_16197.java
BFS 로 문제를 풀었습니다.
BFS 내 구현하는 부분에서 큐에 데이터를 넣고 안 넣고를, if 조건만 잘 맞추면 되는 문제였습니다.
로직은
1. 입력 값 중에, 동전 위치값을 qu에 먼저 집어 넣습니다.
2. bfs 내 구현 조건을 정리합니다.
2-1.  두 코인 다 같이 out 시, continue
2-2. 하나만 out 시, return 종료
2-3. if else  를 통해서, 벽을 만났을 시, 만나지 않을 시
위 flow 대로 설계해서 구현하였습니다.
> Jungmin : Boj 16197 두 동전

- chris-an/home/5.07/Boj_16198.java
- chris-an/home/5.07/Boj_16198_refactoring.java
이번 문제는 구현하는 게 힘들었던 거 같습니다. 문제는 금방 이해했는데 조합을 어떤식으로 해서 구현을 해야하는 지? 계속 고민했습니다.
그래서 설계한 건, dfs 백트레킹 방식으로 조합을 만들고, 그 조합을 가지고 연산처리를 하게끔 로직을 구현했습니다.
로직 flow
1. 입력 받은 에너지 구슬을 배열에 저장합니다.
2. 입력받은 에너지구슬 배열의 첫번째와 마지막을 제외한 그 사잇값을 조합으로 만들어야하는데 idx로 일단 조합을 만듭니다.
3. idx로 조합을 만든뒤, 반복 조합한 idx를 반복 루프를 돌면서, 입력 받은 에너지구슬 배열에 접근하여 값을 뽑아옵니다.
4. 그 이후 로직은, 문제에서 언급한  에너지를 모으는 방법 로직대로 코드를 구현합니다.
5. 그리고 대소관계를합니다.
6. 위 과정을 반복해줍니다.
위 그림은 에너지 모으는 방법의 flow 예시입니다.
> 이번 문제는 배열의 idx를 다루는 데에 조금 더 공부된 거 같습니다. 그리고, 다른 분 코드를 참고해서, 다른 풀이방법을 추가로 익혔습니다.
> Jungmin : Boj 16198

- jihoon/home/5-week2/Boj_9663.java
시간 복잡도를 줄이고자 퀸을 보드에 둘 때마다 가로 방향과 대각선 방향을 모두 체크하고 백트레킹으로 재귀를 호출하며 체크되어 있지 않는 위치에만 퀸을 배치하도록 하였다. 하지만 백트레킹으로 해당 경우의 수가 리턴될 경우 체크를 다시 해제해주는 과정이 너무 복잡해져서 포기했다..
정답코드를 보니 생각보다 간결해서 의외였다. 나는 이차원 visited까지 필요하다고 생각했는데.. 아직 많은 문제를 접해보아야 할 것 같다.
> Jihoon: boj 9663 N-queen

- chris-an/home/5.09/Boj_9663.java
문제를 어떻게 접근을 해야할 지, 생각을 정말 많이했던 거 같습니다.
좌표를 가지고 방문처리를 한다는 생각을 했다가, 구현을 어찌해야할 지 갈피를 한동안 못잡았습니다. 
그러다 col / row 로 방문처리를 하는 방식으로 방문처리 로직 설계를 하면 구현할 수 있다는 생각이 들어. 이 방법으로 코드 구현했습니다.
설계가 오래걸렸지만 어느정도 틀이 잡히고는 간단하게 BackTracking 으로 구현이 가능했던 문제였습니다.
N-Queen 은 유튜브에서 찾아보니 면접에서 시간복잡도 줄이는 과정을 설명 하라고 질문이 나올 수 있다고 하더라구요.
https://devnuts.tistory.com/89
>드디어 N-Queen 문제를 풀어봤네요..
2월 말에 자료구조 기초편 책에서 잠깐 이런 문제가 있다....만 알고 있었는데, 이제 이런 문제를 접하니 확실히 성장한 느낌이 드네요 :)
> Jungmin : Boj 9663

- yoonji/home/5/boj_16198_07.java
- `문제 순서를 반복하며 sum의 최댓값을 찾아가는 dfs의 구현 느낌`으로 받았는데 문제를 이해하면서 풀려니까 어려웠다.
- 예제를 이용해서 구현대로 적어나가면서 특히 4번 문장이 이해되지 않았다. 
- 결국 이해 자체에서 막혀서 구글링하여 찾아봤는데, 구현된 코드에는 4번을 따로 구현한 것으로 판단되지 않아서 의문이다..
> yoonji: boj 16198 에너지모으기

- chris-an/home/5.10/Boj_2580.java
이번 문제는 N-Queen 문제를 풀고 보니, 설계를 빠르게 했지만 구현하는데 시간이 오래 걸린 거 같습니다.
루프를 돌리는게 여러 개라, 스도쿠 게임이 갖는 특성을 메서드화 시켰습니다.
설계대로 짰지만, dfs 구현부 쪽에서 무한루프가 돌아서 이 로직을 수정하는 대에 시간이 오래걸린 거 같습니다.
https://devnuts.tistory.com/90
> 이 문제는 시간이 지나고 다시 풀어봐야할 거 같습니다.
> Jungmin : Boj 2580

- jihoon/home/5-week2/Boj_2580.java
백트레킹의 개념에 대해서 다시 복습하고 이해할 수 있었던 문제였다. 
1. 먼저 main 함수에서 보드를 이중 배열로 초기화 하는 동시에 0이 있는 위치, row값과 col값을 rows와 cols(ArrayList) 에 넣어준다. 즉 rows.size 개수 만큼 숫자들을 찾아야 하는 것이다. 
2. dfs 함수에서 cols,rows에서 현재 depth 인덱스의 값을 가져온 뒤 1부터 9까지 숫자가 들어갈 수 있는지 확인하며 가능할때 보드를 해당 수로 넣어준다. for루프가 다 돌면 현재 조합으로 스도쿠를 풀 수 없다는 뜻이므로 다시 보드를 0으로 초기화 해준다.
> Jihoon: boj 2580 스도쿠

- jeongwoo/BackTracking/Boj2580.java
- jeongwoo/DFS/Pro67257.java
- jeongwoo/DP/Pro12980.java
- jeongwoo/Hash/Pro92431.java
- jeongwoo/문자열/Pro42888.java
1. 주어진 칸이 0인 경우를 찾는다.
2. 0이 있는 칸과 같은 행, 열, 3x3 박스에 1부터 9까지 넣어 보면서 있는지 확인한다.
3. 다 통과한다면 그 숫자를 넣는다.
4. 스도쿠 규칙에 안 맞는다면 넣은 숫자를 다시 0으로 바꾼다.
backTracking에서 리턴하는 경우를 원래 depth로 했었다.
그랬더니.. row 기준으로 9가 아니라 0을 기준으로 9개를 돌아서 모든 0이 다 바뀌지 않았다.
찾아보니까 row, col을 기준으로 하더라..
> Jeongwoo: BOJ 2580 스도쿠 / 프로그래머스 12980 점프와 순간 이동 / 프로그래머스 92341 주차 요금 계산

- chris-an/home/5.12/Boj_1987.java
- chris-an/home/5.12/Sw_1859.java
방문처리 백트래킹일 거 같다고 생각해서, 설계를 빠르게 하고 바로 코드를 구현했습니다.
처음엔 방문처리를 2차배열로 해야하나? 했다가, 아스키코드로 알파벳을 숫자로 변환해서 사용하면 1차배열로도 방문처리 관리가 가능할 거 같아 그렇게 로직을 짰고, 구현 도중에 base case가 없는건가? 무한루프를 돌려나? 생각을 했지만, 
dfs 내 로직 루프를 다 돌면 빠져나오기 때문에 별도의 base case 부분은 필요 없었습니다.
> 정답율에 비해, 너무 쉽다고 느껴서 성장했다고 느껴진 문제였습니다..
초반부터 하필 댓글이 눈에 들어와서..
뒤부터 루프 돌리는 걸로 자연스레 코드 구현을 해서 효율성 문제가 발생하지 않고 바로 pass 된 거 같습니다.
그 외엔 쉽게 접근할 수 있었던 거 같습니다. 가장 중요한 걸 힌트로 얻은 느낌이네요.
> Jungmin : Boj 1987 / SW 1859

- jeongwoo/DFS/Boj1987.java
base case에 대해 고민하다가 일단 구현해 봤는데, 보니까 for문 다 돌면 나가는 거였다..
> Jeongwoo: BOJ 1987 알파벳

- yoonji/home/5/boj_1987_12.java
- yoonji/home/5/mono/swExpert_1859_12.java
- yoonji/office/5/12/prg_수식최대화.java
- yoonji/office/5/12/prg_오픈채팅방.java
- 변수명 및 부가수정 추가 진행했습니다.
- 수식최대화 : `calculate` 메서드에서 우선순위가 정해진 연산자들 순서대로 계산해야하는 과정을 구현하기가 조금 힘들었습니다. 연산자와 피연산자의 List를 복사해서 제거하고, 새롭게 연산된 값을 추가하는 식으로 index를 맞춰 진행했습니다.
- 어떤 지점에서 max값을 구해줘야할지 고민해야했습니다..
- 앞에서부터 비교해가면, 현재 값보다 뒤의 값이 큰 경우, 그 값의 뒤의값도 확인해야하고 등등 복잡해집니다.
- 뒤에서부터 비교해가면, 해당 값을 두고, 그 앞에 있는 값들을 비교해가다가
- 더 큰 값을 만나면 `max`값을 바꿔주고
- 작은 값을 만나면 `sum`에 max 값에서 해당 값을 빼준 이익을 더해줍니다.
- 같은 경우는 pass합니다.  
- 1000000까지 가능한 N개의 자연수이고 각 매매가가 10000까지 가능하므로 sum의 단위가 int 이상으로 넘어가는 경우가 있다.
- 최대 이익을 구하고, 배열이 있는데, 앞뒤를 비교해서 구하는 문제에서 뒤에서부터 시작할 수 있음을 생각하는 연습이 필요할 것 같다.
> yoonji, jihoon : prg 수식최대화 & prg 오픈채팅방 / yoonji:  boj 1987 알파벳 & sw 1859

- chris-an/home/5.13/Boj_1062.java
- chris-an/home/5.13/Sw_1244_fail_메모리초과.java
- chris-an/home/5.13/Sw_1244_pass.java
이번 문제 풀 때, 메모리 제한이라는 게 존재해서 로직 설계할 때 복잡도  체크를 먼저하고 풀었습니다.
제가 설계한 로직은 문제에서 언급한 몇 단어 알파벳이 꼭 들어가야하는 애들이 있으니, 앞뒤 4word를 제외한 그 사잇 알파벳으로 조합을 만들어, 방문처리로 사용가능한 단어인 지 여부 체크를 하여 사용가능한 단어 갯수를 count 하여 최대로 단어 사용 가능한 수를 구하는 방식입니다.
제 로직이 복잡도에 문제가 되지 않을 거 같아. 바로 코드로 구현 했는데, 
조합 백트래킹에서 여러가지 조건들이 있다보니, 구현에서 시간이 걸렸던 거 같습니다. 
> 그래도 한번 풀어서 그런지, 비슷한 문제유형이 나오면 금방 접근해서 구현할 수 있을 거 같습니다.
흠... 이건 제가 풀었다고 볼 수 없네요.
로직 설계를 하는 도중에 계속 예외처리가 생겨서 확실하게 로직 설계를 못하였습니다.
swap을 하여 숫자판이 변형되는 과정에서 dfs로 완탐을 로직을 짜야하는데, 설계가 잘 안되네요.
> pass / fail (메모리초과) 를 commit 했습니다. 이 문제는 그냥 계속해서 봐야할 거 같습니다.
> Jungmin : Boj 1062 / SW 1244

- chris-an/home/5.14/Boj_13460.java
- chris-an/home/5.14/Sw_5948.java
로직 설계는 전에 풀었던 동전 문제랑 비슷해서 금방 접근했던 거 같습니다.
설계한 로직을 구현 다 했을 때, 몇 가지 테케 값이 일치하지 않아서 디버깅 해봤더니 로직 설계 때 놓쳤던 부분이 있다는 걸 알았습니다.
R 구슬과 B 구슬이 겹쳤을 경우, 사방면으로 구슬 위치를 재조정해야하는 부분입니다.
두 구슬 위치가 같을 경우 비교를 해줘야겠다 생각해서, 사방면에 맞게, 같을 때 위치값 back을 하게끔 로직 수정을 했습니다. (이 부분에서 시간을 많이 씀. 아마 이 부분 때문에 골드1인 거 같음.)
https://devnuts.tistory.com/95
> 비슷한 문제가 나온다면, 빈틈없이 로직 구현을 할 수 있을 거 같네요.
---
조합 후, 찾는 dfs 문제였습니다.
순위 구할 때, 중복 부분 제거를 위해서 HashSet 이용하고 정렬하는 거 외엔 기본 dfs 문제였던 거 같습니다.
> 아마 코테 1번 문제일 거 같고, 20분 내로 풀어야하는 문제였던 거 같습니다.
> Jungmin : Boj 13460 / SW 5948

- jihoon/home/5-week2/Boj_1062.java
1. (a,n,t,i,c)는 모든 문장에 포함되어 있으므로 최소 저 알파벳은 알아야 문장을 한개라도 읽을 수 있다. 즉 K개를 가르칠 때 K가 5 미만이면 0을 출력하도록 하였다.
2. K가 5 이상이면 먼저 (a,n,t,i,c)부터 가르치고 K-5를 가르칠 조합을 구하도록 하였다. 이 때 모든 알파벳에서 K-5개를 뽑는 경우의 수를 구해도 되지만 문장에서 등장한 알파벳에서만 K-5를 뽑아 만드는 조합만 구하면 되므로 먼저 문장에서 등장하는 모든 알파벳을 구하도록 하였다.
3. alphabets 중에서 K-5개를 뽑는 모든 조합을 백트레킹 방식으로 구한다. 
4. 만들어진 조합을 countWords 함수로 넘겨주며 해당 조합으로 문장을 구성할 수 있을때 count++ 해주며 최댓값으로 갱신해준다.
2 26
antarctica
antaxxxxxxxtica
의 경우와 같이 K가 배워야 하는 알파벳이 갯수보다 클 때 N을 출력하도록 하였다. 이 부분을 처리를 안해주어서 자꾸 50%에서 틀렸다..
> Jihoon: boj 1062 가르침

- yoonji/home/5/swExpert/swExpert_1244_13.java
주석으로 적어놓았지만..
- 처음 시도한 방법은 한 값과 그 뒤의 값들 중 max값을 바꿔나가는 식으로 진행했는데
➡️ 예제 `32888 2` 같은 경우의 최댓값을 구하지 못함.. 일단 모든 경우의 수를 구해야하구나 생각(회피하고 싶었던 것 같기도..) => `dfs`
- 조건은 제한 횟수만큼 다돌았을 때 `max` 값을 구하고 종료하도록 했습니다.
- 이전에는 print로 했는데, 이번에 buffer로 출력하는 방식으로 했습니다. (코드 한줄 더 추가되네요)
- 둘다 닫아주는 코드도 추가했습니다.
> yoonji: sw 1244 최대상금 (TC 3개 불통..)

- chris-an/home/5.16/Boj_12100.java
- chris-an/home/5.16/Sw_6485.java
- chris-an/home/5.16/Sw_N줄덧셈.java
- chris-an/home/5.16/Sw_가위바위보.java
- chris-an/home/5.16/Sw_간단한N의약수.java
- chris-an/home/5.16/Sw_거꾸로출력해보아요.java
- chris-an/home/5.16/Sw_대각선출력하기.java
- chris-an/home/5.16/Sw_더블더블.java
- chris-an/home/5.16/Sw_몫과나머지출력하기.java
- chris-an/home/5.16/Sw_서랍의비밀번호.java
- chris-an/home/5.16/Sw_스탬프찍기.java
- chris-an/home/5.16/Sw_신문헤드라인.java
- chris-an/home/5.16/Sw_아주간단한계산기.java
- chris-an/home/5.16/Sw_알파벳을숫자로변환.java
- chris-an/home/5.16/Sw_연월일달력.java
- chris-an/home/5.16/Sw_자릿수더하기.java
- chris-an/home/5.16/Sw_중간값찾기.java
- chris-an/home/5.16/Sw_최대수구하기.java
- chris-an/home/5.16/Sw_큰놈작은놈같은놈.java
- chris-an/home/5.16/Sw_평균값구하기.java
- chris-an/home/5.16/Sw_홀수만더하기.java
확실히 골드1에 가까워질수록 코드를 작성하기 전에 생각을 많이 해야하는 거 같습니다.
dfs 로 `depth` 에 맞춰 재귀를 돌려 주면 된다 라는 생각을 했지만,
어떤식으로 재귀를 돌려줘야할지? 가 생각이 나지 않았습니다.
일단 처음에 접근 했던 방식은 NxN 의 위치값을 계속 저장을 하면서 최신화해주고, 전에 있던 값까지 알아야하나? 그러니 객체를 만들어서 dfs를 돌려야하나? 라는 생각을 했습니다. 하지만, 그러면 메모리 측면에서 효율이 좋지 않을 거 같아. 다른 방법을 생각했습니다.
그래서 정리한 로직은,
매 dfs 재귀 돌릴 때마다, board 를 새로이 보드를 만들어, 움직임에 맞게 다시 세팅한다는 생각을 해서 다시 로직 설계를 했습니다.
그리고 방문체크에 대한 고민을 했는데, 움직임 횟수(5) 가 정해져 있고, 그 움직임 횟수대로 재귀를 돌릴 시, 최대 재귀 루프가 1300~1400정도? 돌기 때문에 일단은 방문탐색 없이 로직을 구현했습니다.
> 이제 dfs, bfs 코드 구현은 어느정도 익숙해졌고, 이젠 기본을 안 상태에서 다양하게 구현하는 방법을 공부하는 느낌입니다.
문제 이해하는 게 다인 문제입니다.
문제만 이해하면, 다양한 방법으로 구현하는 문제라 만약 코테로 문제가 나오면 1번 문제에 20분 내로 풀어야할 거 같습니다..
> 급하게 푸느라, idx 실수가 나서 시간을 40분이나 썼네요..
> Jungmin : Boj 12100 / Sw 6485 / diff1 - 전체

- jihoon/home/5-week3/Boj_12100.java
설계 자체는 간단했는데 구현하기가 어려웠다. dfs로 상하좌우로 이동하며 보드를 merge시키며 5번 돌렸을 때 최댓값을 갱신해주기만 하면 되었다. 하지만 보드를 merge 하는 부분을 구현하지 못했고 해당 배열을 복사해서 사용하는 방법을 생각해내지 못했다. (보드 merge를 구현해도 어떻게 원복시킬까 계속 고민하였는데 보드를 복사해서 사용하면 되었다!)
> Jihoon: boj 12100

- chris-an/home/5.17/Boj_16928.java
- chris-an/home/5.17/Sw_14178.java
이번 문제는 생각보다 쉽다고 생각해서, 설계를 빠르게하고 구현을 하면서 필요한 로직을 수정했습니다. (결국 약간의 삽질을 했습니다 😂)
처음 로직은
뱀을 고려할 필요 없다고 생각해서, 그냥 뱀의 시작 부분만 방문(true) 처리를 하고, 사다리정보만을 가지고 bfs를 돌렸더니..
7%에서 틀렸다고 나오더라구요..
그래서 뱀과 사다리 정보를 가지고 bfs 를 돌렸더니 22%에서 또 틀렸다고 나오던데, 
이 부분은 뱀 경로를 통해 이동한 위치의 방문 처리로 if 조건에 거르는 로직 `54line` 때문에 틀렸습니다. 
거기서 if 조건으로 거를 필요가 없습니다.
고민을 좀 많이하고 구현을 시도 했다면? 좀 더 빠르게 풀 수 있지 않을까합니다 :)
> 문제를 풀고 난 뒤에, 문제가 확실히 이해가 된 경우였습니다.
처음에는 bfs 인가? 그래서 bfs 로직으로 설계를 하려고, 그림을 그려가면서 하고있었는데...
이건 bfs 로직처럼 설계가 안되는 거 같고, 이건 뭐 그냥 나누기 문제인데? 생각이 되서 바로 수학적으로 나누기 계산을하고 
제출하니 맞았네요 :)
> 10분 내로 접근해서 풀수 있던 문제였습니다.
> Jungmin : Boj 16928 / SW 14178

- yoonji/home/5/boj_13460_14.java
- yoonji/home/5/swExpert/sw_6485_16.java
- yoonji/office/5/17/prg_튜플.java
- yoonji/office/5/17/prg_파일명정렬.java
- 두 문제 모두 완벽히 해결되지 않는 상태이다..
- 어디가 틀린지 감이 안와서 계속 고민 중이다.
> yoonji: sw 6485 삼성시의 버스 노선 / boj 13460 구슬탈출2

- jeongwoo/BFS/Boj16928.java
최단 경로여서 일단 BFS로 접근하였다.
1. 최단 거리 문제 -> BFS로 접근해 본다.
2. info[]에 사다리, 뱀에 대한 정보를 넣는다. x -> y라면 info[x] = y
3. BFS 시작 시 위치 1에 대해서 visited 체크를 하고, count[1] = 0 -> 첫 시작이니까.
4. 원래 위치에서 +1 ~ +6 (주사위)를 하면서 visited 체크가 돼 있는지 확인한다.
5. 이미 방문한 곳이라면 넘기고, 위치가 100을 넘어도 continue
6. 방문 예정인 곳(x)에 대해 info[x] 값이 있다면 info[x] 값이 visited 됐는지 본다. 방문하지 않은 곳이라면 큐에 넣고 cnt는 현재 있는 곳의 값에서 + 1
7. 방문 예정인 곳(x)에 대해 info[x] 값이 없다면 큐에 넣어 주고, cnt는 현재 있는 곳의 값에서 + 1
info[x]에 값이 0이 아닐 때, count[x]에 넣어 주는 게 아니라 count[info[x]]에 넣어 줘야 됐는데 헷갈렸었다.. 
count[x]를 0으로 두어도 visited 체크를 하니까 넘어가고, x에서는 info[x]로 바로 넘어가니까.......
아직도 BFS는 부족한 것 같다.
> Jeongwoo: BOJ 16928 뱀과 사다리 게임

- chris-an/home/5.18/Boj_16948.java
- chris-an/home/5.18/Sw_10059.java
- chris-an/home/5.18/Sw_간단한369게임.java
- chris-an/home/5.18/Sw_조교의성적매기기.java
- chris-an/home/5.18/Sw_중간평균값구하기.java
- chris-an/home/5.18/Sw_지그재그숫자.java
- chris-an/home/5.18/Sw_초심자의회문검사.java
- chris-an/home/5.18/Sw_파리퇴치.java
- chris-an/home/5.18/Sw_파스칼삼각형.java
- chris-an/home/5.18/Sw_패턴마디의길이.java
전형적인 기본 bfs 문제입니다. 
설계없이 바로 구현가능한 문제라 생각해서 바로 구현을 했고 간단하게 끝났던 문제였네요..
---
숫자놀음? 같았습니다..
처음에는 boolean 두 개로 운용해서 구현하는데, 너무 복잡해지다보니 4개로 늘려서,
`aMM` `bMM` `aYY` `bYY` 로 나누어 생각하였습니다.
그러니 쉽게 구현도 가능할 뿐만 아니라 코드 읽기도 편했습니다.
> Jungmin : Boj 16948 / SW 10059 / SW diff2 8문제

- yoonji/home/5/boj_16928_17.java
- 처음에는 그냥 사다리를 타면 빨리 도착할 것이라 생각해서 구현을 했는데, 아니었다..
- `bfs`로 풀었다.
- 1부터 6까지 주사위를 던지면서
- 이미 방문한 곳이면 pass
- 100을 넘으면 pass 
- 옮겨진 위치에서 snake나 ladder가 있고 방문하지 않은 곳이면 큐 추가, cnt+1 지정
- 그 곳이 방문 했으면 pass
- snake, ladder 없으면 그냥 그곳을 큐 추가, cnt+1 지정
> yoonji : boj 16928 뱀과사다리게임

- jihoon/home/5-week3/Boj_16948.java
dr, dc를 전역변수로 설정하고 bfs로 for문을 6번 돌면서 Queue에 넣었다. 클래스를 이용해서 r, c좌표값을 가지고 다니도록 하였다.
> Jihoon: boj 16948

- jeongwoo/BFS/Boj16948.java
- jeongwoo/Heap/Pro42626.java
- jeongwoo/수학/Pro17687.java
- jeongwoo/정렬/Pro42747.java
> Jeongwoo: 2022-05-18 BOJ 16948 데스 나이트

- chris-an/home/5.19/Boj_9019.java
- chris-an/home/5.19/Boj_9019_refactoring.java
- chris-an/office/5.19/Pro_H_Index.java
- chris-an/office/5.19/Pro_더맵게.java
어느정도 로직 설계를 한 뒤, 구현에 바로 들어갔는데 구현 도중에  L과 R 부분을 문제에서 언급한대로 풀기 보단, 문자열 다루는 걸 연습해보고자 String이랑 StringBuilder로 한 번 시도를 해봤는데 생각보다 이 부분이 미흡 했다는 생각을 했고, 문제를 다 풀고 난 뒤에 굳이 왜 이렇게 풀었을까? 라는 생각을 하게 됐습니다..
`자릿수(*10)` 관련 로직으로 푼 문제가 이번이 세 번째 같은데, 숫자 조합을 할 때 `자릿수(*10`) 를 이용하는 게 로직 설계할 때 훨씬 다양하게 구현이 가능하고 편할 거 같네요.
refactoring 을 할 땐, 다른 분 코드를 참고하면서 코드를 익히는데 중점을 두었습니다.
> 후기는 문제에서 언급한대로 문제를 풀어야 편하고, 문자열 다루는 건 더 능숙하게 다뤄야할 필요성이 있음. 불필요한 변수 선언이 많음 :(
아. 그리고 두 방법 차이는 메모리는 큰 차이는 없지만, 시간복잡도는 두 배가량 refactoring 코드가 좋습니다.
> Jungmin : Boj 9019 / Programmers H-Index, 더 맵게

- jeongwoo/BFS/Boj9019.java
L과 R 연산을 할 때 String로 접근해서 자리 바꿔 줬는데 그러면 0001이 1이 돼서 틀렸다.
그래서 정수로 표현하는 게 있다고 해서 바꿨다.
메모리 초과로 계속 고생했다....
테케 개수 T에 대한 정보가 없길래 처음에 input 배열에 넣어서 해 줬는데
받자마자 bfs를 호출했더니 해결됐다.
입력은 웬만하면 저장해 두지 말아야 된다고 배웠다.
입력에 대한 결과가 끝났으면 덮어쓰기..!!..... 크게 배웠다.
> Jeongwoo: BOJ 9019 DSLR

- chris-an/home/5.20/Boj_14502.java
- chris-an/home/5.20/Sw_숫자조작.java
- chris-an/home/5.20/Sw_어디에단어가들어갈수있을까.java
- chris-an/office/5.19/Pro_n진수게임.java
조합을 잘 다룰 수 있는지? 물어보는 문제였습니다.
정리한 로직 flow
1. 0~N-1까지 조합을 만듭니다 (idx 조합)
2. dfs 백트래킹을 boolean 으로 true / false 로 구별해서 찾습니다.
3. 찾은 조합으로 input 받은 data에 접근해서 조합idx 로 swap 작업
4. 재조합한 값을 max, min 비교
5. 위 과정을 반복
> 이런 문제는 이제 적응되서, 바로바로 구현이 가능하지만, 30분 내로 풀 수 있도록 연습을 더 해야겠습니다.
이번 문제는 고민을 많이했습니다. 이 문제를 풀려면 dfs, bfs 또는 dfs, dfs 이렇게 풀어야할 거 같다는 생각이 들었습니다.
벽을 어떻게 세워야하지? dfs로 어떻게 구현을 해야할까? 라는 생각에 시간이 오래걸렸습니다 :(
로직은
1. 벽 3개를 무조건 세워야하니 depth 기준으로 dfs 돌리기
2. 벽 세팅 된 걸로, 바이러스 버트리기 (bfs)
3. 전체 board를 탐색해서, 갯수 카운트해서 max 값을 비교
이번 문제는 벽을 세팅하는 부분에서 오랜 시간 고민했습니다. 쉽게 생각이 나질 않더라구요.
> 임의 갯수로 무언 갈 board 내에 셋팅하는 방법을 배운 거 같습니다.
로직 설계는 
일단 t의 갯수만큼 위치의 값을 알기 위해서 n진수의 값들을 나열해야합니다.
그래서 t의 갯수를 구할 수 만큼의 길이에 맞게 진수변환을 통해 진수값이 담긴 데이터를 String으로 세팅한 뒤
값을 뽑아주는 식으로 로직을 구현했습니다.
> 진법변환을 직접구현하려다가, 설마 진법 변환 메서드가 있는 지? 찾아보니 있어서 …
> Jungmin : Sw 숫자조작(13428) / Boj 14502 / Programmers n진수게임 / diff-2 계속 commit..

- jeongwoo/BFS/Boj14502.java
벽을 세우기 위해 dfs로 백트래킹을 하였다.
벽 3개를 세웠으면 bfs를 통해 바이러스(2)를 다 뿌려 주었다.
bfs에서 dfs에서 온 map을 받아야 하기 때문에 copiedMap으로 시작할 때마다 배열을 복사하였다.
> Jeongwoo: BOJ 14502 연구소

- yoonji/home/5/InputUtil.java
- yoonji/home/5/boj_14502_20.java
- yoonji/home/5/swExpert/sw_13428_20.java
char 배열을 문자열로 바꾸는 것은 String.valuof()로 쉽게 가능하다는 것을 알았다.
처음에는 min과 max를 구하는 메서드를 따로 두고, 아래 로직으로 작성했다.
>1. 반복문 돌며 최솟/최댓값구하기
>2. 반복문 돌며 최솟/최댓값보다 큰/작은 값을 만나면 교환
문제는 12324와 같은 케이스인데,
최솟값은 1이지만, `12324`보다 `12234`가 더 작으므로 변화가 있어야한다.
최솟값과 최댓값을 고르고 교환하는 로직이 아닌,
그냥 `전체 값`으로 `최소, 최대를 비교`해서 답을 구해야함을 알고 로직을 바꿨다.
> 채점 : 300608 / 924
- 로직을 설계할 때 완전 탐색으로 찾아봐야겠다는 것은 생각했지만, 현재 코드보다 벽을 세우는 방법에 있어서 더 간단히 해결하는 방법이 있을 줄 알았다.
- 계속 고민하다가 그 방법을 못찾는다 생각해서 구글링했는데, 그냥 벽을 모든 칸에 세워보고 안전영역의 최댓값을 구하는 것이었다.
- 그만큼 N과 M의 길이 제한이 짧기 때문에 가능하다.
- 그래도 역시 메모리 공간이나 시간이 많이 소요되는 코드인 것 같다.
➕ 처음에 `얕은 복사`를 해서 `bfs` 로직을 타기 전 `map` 상태가 변경되었다. => `깊은 복사` (값을 복사)로 변경
> yoonji: sw 13428 숫자조작 / boj 14502 연구소

- jeongwoo/BFS/Boj2206.java
- jeongwoo/Hash/Pro12981.java
- jeongwoo/List/Pro17680.java
- jeongwoo/순열/Pro87946.java
처음에는 map[i][j] == 1일 때 map[i][j] = 0으로 하고, bfs를 돌리고 다시 원래대로 돌렸다. else일 때는 그냥 bfs 돌리고. 이렇게 되면 모든 맵이 다 벽인 최악의 경우에 시간초과가 나고, 모든 벽을 다 0으로 바꾸는 방법이 아니라고 느꼈다.
그래서 찾아보니까 큐에 벽을 부수었는지, 안 부수었는지에 대한 정보를 저장하고, 그 값에 따라 분기 처리를 하는 거였다.
bfs에도 끝이 없구나~
> Jeongwoo: BOJ 2206 벽 부수고 이동하기

- chris-an/home/5.26/Boj_14442.java
- chris-an/home/5.26/Boj_16933.java
- chris-an/office/5.26/Pro_영어끝말잇기.java
- chris-an/office/5.26/Pro_캐시.java
- chris-an/office/5.26/Pro_피로도.java
이번 문제는 이동하기1 문제와 흡사해서 방문처리만 잘 처리해서 풀었습니다.
> 유사한 문제라 그런지 30분 이내로  풀 수 있었습니다.. 유사한 것만 나오면 참 좋다고 잘 풀게 되네요 :)
낮과 밤이라는 조건이 생겨서, 4차원 boolean 으로 하고 class 에 매개변수 하나를 더 만들어 낮과 밤을 구분지어 주었습니다.
그외에는 앞서 풀었던 문제와는 별 다를 게 없었습니다.
> Jungmin : Boj 14442 / Boj 16933 / Programmers 3문제

- jeongwoo/BFS/Boj16946.java
- jeongwoo/BFS/Boj7576.java
- jeongwoo/DFS/Boj1012.java
처음에는 완탐으로 1을 만날 때 0으로 바꾸고 주변 0을 다 카운팅했다. 
그랬더니 다음 1을 만났을 때 겹치는 0이 있어서 시간 초과가 났다.
찾아보니까 일단 같은 영역에 있는 0을 그룹으로 다 묶어 주었다. 그리고 0 자리에 그룹 배열에 그룹 id 값을 넣었다.
groupCnt 배열에는 각 그룹 id별로 몇 개의 0이 있는지 넣어 주었다.
1을 만나면 1의 상하좌우에 어떤 그룹 id가 있는지 찾아서 HashSet에 담았다. 1 주변에 같은 id가 있는 0이 있으면 중복이 되니까 셋으로 처리하였다.
id에 있는 0의 개수를 다 더해서 출력하면 끝.
> Jeongwoo: BOJ 16946 벽 부수고 이동하기 4

- chris-an/home/5.28/Boj_3055.java
움직이는 미로탈출 문제를 푼 뒤에 이 문제를 푸니깐, 어떻게 접근을 해야하는 지 금방 설계를 하고 구현을 했지만, 고슴도치(S)랑 비버의 굴(D) 의 위치 값을 반대로 생각을 하고 코드를 짜서 잠깐 삽질을 했습니다..
결국 S랑 D만 바꿔주니 통과가 됐네요. 생각보다 앞선 문제랑 비슷한 로직이라, 구현 연습하기 좋았습니다.
> Jungmin : Boj 3055

- chris-an/home/5.31/Boj_16236.java
- chris-an/office/5.31/Pro_땅따먹기.java
- chris-an/office/5.31/Pro_프렌즈4블록.java
bfs 문제가 점점 구현하는 게 어려워지네요..
`baby sharck` class 매개변수를 어떤 걸 넣을 지, 계속 수정하면서 문제를 풀었던 거 같습니다.
그리고, 
처음에는 먹이가 먹을 게 여러 개일 때,  문제에서 언급한 조건에 맞게끔 먹이를 먹을 수 있게 조정하는 걸 그냥 구현으로 처리 했는데, 
문제를 계속 풀다가 수정을 거듭하면서 `PriorityQueue` 에서 Comparator 로 수정했습니다.
또한, 처음 qu 에 상어 위치 값을 넣을 때, bfs 메서드 내 peek 을 통해 방문처리 하는 방식도 이전과 다른 방법이라 익히기에 좋은 거 같습니다.
그 이후에는 보통의 bfs 문제 풀듯이 풀었습니다. 
> 구현하는 게 빡센 거라 이러한 문제를 시간을 단축시켜 풀기 위해선 많이 익숙 해져야겠네요..
> Jungmin : Prg 2문제 / Boj 16236

- yoonji/home/5/boj_16236_31.java
- yoonji/home/5/boj_3055_28.java
- yoonji/office/5/prg_땅따먹기.java
- 처음에 다른 방식으로 풀다가 dp 방식으로 접근해야겠다 생각하고 다시 풀어 해결헀습니다.
- 좋은 접근인지는 모르겠습니다 😃
> yoonji: prg 땅따먹기

- chris-an/home/6.01/Boj_1963.java
이번 문제는 쉽다고 생각해서, 금방 구현하다가 bfs 에 대해서 잘못 이해하고 있던 부분이 있어서 삽질을 좀 한 거 같습니다.
현 로직에선 `Queue` -> `PriorityQueue` 로 바꿨지만, 전엔 `Queue`로 설계해서 구현했습니다. 
`Queue` 에 담는다면, 최소 횟수로 결과 값을 찾을 수 있다고 생각을 했지만, 계속 정답이 4로 나와서 문제가 발생했습니다.
문제를 제대로 이해하고 bfs 로 이어 잘 생각했다면, 매 순간 qu 에 넣고 뺄 때를 고려해서 구현 했을 거 같습니다.
소수로 바꾼 횟수가 최소 일 때 qu 에서 빼야함으로 우선 큐를 사용해서 처리를 했어야 합니다.
> 문제를 풀기 위해서 빠르게 코드를 구현하다보니, 코드 효율이랑 클린하게 코드를 짜질 못해서 코드 리팩토링을 해야할 거 같습니다. 예를 들면 숫자를 String -> char -> int 로 변환하는 거 없이 int 로만 짤 수 있게 코드를 바꾸던지, 자릿 수 중 하나를 수 교환할 때, 자릿수 연산처리로 숫자를 변경을 하는 클린 코드로 짜야할 거 같습니다.
> Jungmin : Boj 1963 소수경로

- chris-an/home/6.02/Boj_10026.java
- chris-an/home/6.02/Pro_가장먼노드.java
- chris-an/home/6.02/Pro_타겟넘버.java
- chris-an/home/6.02/Pro_행렬테두리회전하기.java
응용이 없던 그냥 일반 bfs 문제였습니다.
구현 문제였는데, 익숙하지 않아서 1시간 정도 걸렸던 거 같습니다.
이런 문제는 설계하는 건 어렵진 않지만 구현을 잘 할 수 있도록 연습이 많이 필요한 거 같습니다.
그래프(인접) 문제를 오래간만 풀어서, dfs, bfs 를 어떻게 돌렸는 지 생각이나질 않았습니다.
이번 문제를 풀면서 기존에 풀었던 방식을 다시 생각해내기 좋았습니다. 
조합을 어떤 식으로 만들어야 할지 생각이나질 않아 다른 분 코드를 찾아본 뒤 문제를 해결했습니다.
계속 설계가 안됐던 건, 피연산자가 `N`개 일 시, 연산자가 `N-1` 이니, 연산자의 갯수를 +, - 로 조합을 만든 뒤 그 후에 연산처리를 하려고 생각했는데, `+ 와 -` 이 두 가지를 가지고 연산자 조합을 만드는 방법이 생각이 나지 않았습니다. 예를 들어 +++++,++++-,+++-+ .........
이런 경우에는 dfs를 두 번 호출해서 풀수 있다는 걸 알게 됐습니다.
> Jungmin : Boj 10026 / Programmers 4문제

- jeongwoo/BFS/Boj10026.java
적록색약인 경우 R과 G를 같은 입력으로 받아서 해결했다.
vistied 체크를 main에서 하면서 각 색마다 탐색하여 몇 개의 구역이 있는지 확인하였다.
> Jeongwoo: 2022-06-02 BOJ 10026 적록색약

- chris-an/home/6.03/Boj_14395.java
- chris-an/home/6.03/Boj_14395_refactoring.java
일반적인 bfs 문제 였는데, 여러 조건들을 신경 써줘야합니다.
탈출 조건을 어떻게 할 지만 정리만 하면, 나머지는 문제에서 언급한대로 여러 조건을 걸러주기만 하면 됩니다.
> 메모리가 100만 정도 나오니, 다른 분 코드를 보면서 효율 측면에서 리팩토링, 클린하게 코드를 수정해봐야겠네요.
리팩토링은
boolean 형 방문처리가 아닌 Set 을 이용해서 중복처리르 해주었더니, 메모리, 시간 복잡도 효율이 훨씬 좋아졌습니다.
그리고 int 에서 long 으로 casting 했던 걸, 그냥 long 으로 타입을 지정을 해주었습니다.
> Jungmin : Boj 14395

- yoonji/home/6/boj_14395_03.java
- yoonji/home/6/mono/boj_2579_dp.java
- yoonji/office/5/prg_n진수.java
- `bfs`를 이용해서 조건에 충족할때의 1번째 값이 바로 최소가 된다.
- 사전순으로 첫번째 것을 뽑으라는 조건 => 연산자 for문을 돌릴 때 우선순위순으로만 계산하도록 하면 된다.
- 그 외 설명은 주석으로 추가했습니다.
- 처음에는 2,8,16진수만 고려해서 로직을 짰다. 그런데 커버되지 않는 테스트코드가 있어서 10진수를 n진수로 바꾸는 방법을 찾아보니 모든 진수에 대해 변환이 가능하다는 것을 깨닫고 다시 수정했다.
- 전체 문자열을 구한 후에, p차례에 해당하는 문자를 뽑았다.
> yoonji: boj 14395 4연산 / prg n진수

- jihoon/home/6-week1/Boj_10026.java
일반적인 bfs 방식으로 영역의 개수를 구하고 R와 G를 같은 것으로 보고 영역의 개수를 구했다. 적록색약인 사람과 아닌 사람을 위한 bfs를 따로 만들어야 해서 코드가 길어졌다.
똑같은 bfs를 재활용하되 다시 bfs를 실행하기 전에 board만 'G'를 'R'으로 바꿔주었다.
> Jihoon: boj 10026

- jeongwoo/이분 탐색/Boj10815.java
> Jeongwoo: 2022-06-04 BOJ 10815 숫자 카드

- chris-an/home/6.04/Boj_10815.java
그냥 딱 이분 탐색라서, 특별한 건 없었습니다.
이번 풀이는 재귀적, 반복적으로 두 가지 방법으로 구현 시도 해보면서 시간, 공간 복잡도 차이가 있는 지만 확인해 보았는데 별 차이 없었습니다.
> 윤지님이 공유 해주신 문제 덕분에 완전 비슷한 문제라 금방 접근해서 풀었네요:)
> Jungmin : Boj 10815

- yoonji/home/6/boj_10815_04.java
- 이분탐색은 **정렬된 배열**에서 가능하다.
- 기본적인 이분 탐색 로직으로 풀리는 문제였습니다!
> yoonji : boj 10815 숫자카드

- chris-an/home/6.06/Boj_10816_failed.java
- chris-an/home/6.06/Boj_10816_pass.java
처음 접근한 방법은 자료구조(`ArrayList`) 를 사용하여 이분탐색으로 탐색된 숫자카드를 `remove` 하고, 찾는 숫자의 갯수를 `count` 하는 방법으로 로직을 구현 했지만, 테케는 통과되고 틀렸다고 나오네요. 반례를 찾지 못했습니다.
그래서 다른 분 코드를 참고해서 보니, 이분탐색을 할 때, 하한선 상한선을 접근하여 idx를 빼주는 방법으로 중복된 숫자가 몇 개 있는 지를 확인할 수 있는 방법이 있어서 그렇게 로직구현을 하였습니다.
> 이분 탐색 응용을 공부한 거 같네요. 찾아보니 HashMap 방법도 있는 거 같으니, 다른 방법으로 구현해봐도 좋을 거 같습니다.
> Jungmin : Boj 10816

- jihoon/home/6-week1/Boj_10815.java
검색하고자 하는 배열을 먼저 정렬한뒤 이분탐색으로 검색하였다. 먼저 주어진 길이의 log2만큼 최대횟수를 지정하고 for문으로 그 횟수만큼 돌면서 수를 못 찾을 경우 0, 중간에 수를 찾으면 바로 1을 리턴하도록 하였다.
> Jihoon: boj 10815

- yoonji/home/6/boj_10816_06.java
- 이전과 비슷한 문제라서 이번에는 `HashMap` 자료구조를 이용해서 해결했습니다.
- 백준 채점현황이 기준이 되기에는 모호하지만...
- 메모리 : 176672kb,   시간 : 1124ms
> yoonji: boj 10816 숫자카드2

- chris-an/home/6.07/Boj_11728.java
- chris-an/home/6.07/Boj_11728_twoPointer.java
- chris-an/home/6.07/Boj_2003.java
- chris-an/home/6.07/Boj_2003_twoPointer.java
`ArrayList` 자료구조를 이용하여, 두 배열의 데이터를 담아 `Collections.sort` 하는 방식으로 구현했습니다.
메모리랑 시간복잡도가 높게 나와서 다른 분 코드를 참고해보니 비슷했습니다.
다른 방식으로 투포인터 방식이 있어서, 해당 알고리즘으로 구현해보면서 `투포인터` 도 익혀보았습니다.
> 추가로 수들의 합 2(2003) 문제가 투 포인터 문제라서 한 번 비교를 해보기 위해서 투포인터 로직 적용 전 후로 복잡도 check 를 했는데, 결과적으론 별차이가 없었습니다.. 메모리는 비슷했고 시간 복잡도도 큰 차이가 않나네요
> Jungmin : Boj 11728

- chris-an/home/6.08/Boj_1780.java
- chris-an/home/6.08/Boj_1780_refactoring.java
처음 로직 설계할 땐, 재귀 구현부 쪽에 재귀호출 코드라인을 하나만 만들어서 어떻게든 짜려고했지만, 
그렇게 설계 하기가 어렵고, 신경써야하는 부분이 많아서 정리가 안돼 구현하기가 쉽지 않았습니다.
그래서  각 9부분을 재귀 호출하는 방식으로 코드를 구현한다고 생각하니, 어느정도 길이 보여서, 그런 식으로 구현하였습니다.
그리고 `target` 값을 어떻게 알아서 `target`을 어떻게 count 를 해줄까? 생각을 하다가 `map` 자료구조를 이용하면 해결할 수 있을 거 같아. 그 부분은 `map` 자료구조를 사용했습니다.
> 설계를 해서 풀긴했지만, 시간이 오래걸린 거 같아. 재귀 짜는 걸 많이 연습해야겠다고 생각이 들었습니다.
`before`
Map 자료구조를 이용해서 각 종이의 개수를 cnt 를 해준 뒤, 다시 배열을 만들어 출력 값을 담아줘서 출력 해준 부분
`after`
종이는 -1, 0 ,1 만 있다보니, `+1` 해주어 일차원 배열을 가지고 어떤 종이인 지 구분과 동시에 배열을 idx에 접근하여 cnt를 해줍니다.
> Jungmin : Boj 1780

- chris-an/home/6.09/Boj_11729.java
코드를 재귀적인 설계를 한다는 게 확실히 어렵네요.
처음에 생각했을 땐, 자료구조 스택을 이용해서 가장 위에있는 `disc` 를 가지고 남은 이동 할 수 있는 두 `peg` 에 어떤 식으로 옮겨야 할까 라는 고민을 했습니다. 이렇게 할 시에 재귀적으로 설계를 한다는 게, 깔끔하지 않고 복잡해지기만 하고 로직 설계가 마무리 되어가는 게 아닌, 더 복잡해지는 거 같아서 다른 분 코드를 참고하였습니다...
역시 다른 분 코드를 보니 접근을 잘못했다는 걸 알게되서, 다른 코드를 찾아가면서 코드를 구현 해보았습니다.
최종로직은 총 `discs` 를 가지고 재귀를 돌려주는데, 가장 큰 `disc`에서 작은 `disc`를 갈수 있게금 callstack을 쌓아주고, callback 하는 과정에서 이동 했다고 이동한 상태 문자열을 만드는 식으로 구현하게 됩니다.
> 아마 몇 번 더 풀어보면서 재귀연습을 해봐야할 거 같네요.
아래 그림은 call Stack에 쌓아주면서, callback 시, 언제 이동 순서 문자열을 만드는 지 간략하게 그려봤습니다.
> Jungmin : Boj 11729

- jeongwoo/Recursion/Boj11729.java
- jeongwoo/분할 정복/Boj1780.java
종이의 처음부터 끝까지 탐색하면서 다 같은 종이인지 확인한다.
만약에 같은 숫자가 적혀 있지 않다면 3으로 나눠서 각 부분들(총 아홉 부분)을 탐색한다.
생각보다 쉬운 것 같았는데 어떻게 쪼개서 탐색할지에 대해 고민이 많았다.
처음에는 파라미터로 board만 보내 주려고 했는데, 그렇게 되어도 어차피 row, col, length 정보가 필요해서 그냥 row, col, length만 보냈다.
divideAndConquer을 9번 부를 게 아니라 for문을 통해 하면 더 좋았을 것 같다.
---
위와 마찬가지로 이렇게 하면 되겠다 싶었는데 코드로 표현하는 게 재귀는 약간 빡쎈 것 같다...
> Jeongwoo: 2022-06-08 BOJ 1780 종이의 개수 / 2022-06-09 BOJ 11729 하노이 탑 이동 순서

- yoonji/home/6/boj_11728_07.java
- yoonji/home/6/boj_11728_2nd.java
1차. 이분 탐색 => 정렬되어있는 두 배열이니까 이분할은 최악의 경우가 됨.
2차. 앞에서부터 비교
(1,2차는 `boj_11728_2nd.java` 파일에)
3차. ArrayList 넣고 `Collections`의 `Sort` 메서드로 **삽입+머지**
깊게 고민하지 않고 코드부터 작성하려했다가 멍청한 실수를..
> yoonji : boj 11728 배열합치기

- yoonji/home/6/boj_2263_10.java
- 트리 순회 순서를 직접 그려보며 감을 익혀야했다.
> 그외 설명은 주석에 달았습니다.
> yoonji : boj 2263 트리의 순회

- jeongwoo/Tree/Boj2263.java
post의 마지막이 root인 걸 알아야 됐고, 이걸로 inOrder에서 왼쪽 노드, 오른쪽 노드를 구할 수 있다는 것도 알아야 됐다.
근데 이거 이상으로 재귀 부분이 더 어려웠다.
> Jeongwoo: 2022-06-10 BOJ 2263 트리의 순회

- chris-an/home/6.10/Boj_2263.java
트리 개념이 잘 정리가 안되어 있어 공부를 하면서 풀었습니다.
일단 분할정복 문제인데, 어떤 부분에서 분할 정복을 해야하는 지는, 이 문제 핵심인 `postOrder` 로 root 를 찾고, `inOrder` 로 left, right 를 찾을 수 있다는 걸 알면, 분할 정복 알고리즘을 적용하여 생각해서 로직을 짤수 있고, 그 이후에 재귀로 어떻게 구현할 지는 또 다른 문제네요.
> Jungmin : Boj 2263

- jihoon/home/6-week2/Boj_11729.java
처음에 스택을 생각해서 백트래킹 형식으로 풀어보려고 했는데 시간 복잡도도 너무 커질 것 같고 복잡해져서 포기했다. 재귀부분을 찾는 것이 핵심이었던 것 같다.
> Jihoon: boj 11729

- yoonji/home/6/boj_1074_11.java
- yoonji/home/6/boj_1891_13.java
- 확실히 `count` 변수가 어떻게 바뀌어나가는지 직접 그림으로 그려보기 전까지는 풀이를 보고도 이해가 안됐습니다.
> 숫자의 범위를 유의해야 하겠음을 다시 깨달았습니다.. `NumberFormatException`으로 발생해서 찾는데 꽤 오래 걸렸습니다. 해당 문제를 해결하느라 발생할 수 있는 모든 경우를 수정한 것 같습니다. 
> - 2차원 배열을 인자로 넘겨주는 경우, StringBuilder를 인자로 넘겨주는 식으로 푼 것들을 위 에러를 해결하느라 많이 수정했는데 원인은 타입에 있었습니다 :)
- 부분부분 수정해야될게 오래 걸렸지만, grid에서 분할과정은 이전 문제(`Z`)와 유사했던 것 같습니다
> yoonji : boj 1074 Z / boj 1891 사분면

- chris-an/home/6.14/Boj_2447.java
- chris-an/office/6.14/Pro_압축.java
- chris-an/office/6.14/Pro_입국심사.java
N 의 3승인 (3, 9, 27) 을 그린 뒤, 각 위치의 좌표값으로 싹 적어놓고 보니깐 좌표값으로 규칙을 찾을 수 있게 됐고,
그 이후에 분할정복을 어떤식으로 적용해야하는 지 눈에 들어왔습니다.
그리기 전까지는 확실히 감이 안와서, 그리면서 계속 생각하는 문제라 시간이 오래 걸리게 되네요.
> 이 후에 다시 풀어봐야할 거 같네요.
> Jungmin : Boj 2447, Programmers 2문제

- yoonji/home/6/boj_2447_14.java
- yoonji/office/6/prg_압축.java
- yoonji/office/6/prg_입국심사.java
- 재귀로 생각하는 것과 빈 공간과 별 찍는 부분을 동시에 생각하려니 어려웠습니다.
- 재귀 호출을 해서 다시 돌아와서 추가적인 로직을 하는 것이 아닌 로직인데도 어려웠습니다.
- 정답률에 비해 해결하는 데에 오래 걸렸네요
- 해당 문제도 진행 상태를 그림으로 그려나가다보니 이해가 됐습니다.
> 그외 추가 설명은 주석으로 작성했습니다.
> yoonji :  boj 별찍기-10  / yoonji, jihoon, jungmin: prg 입국심사 / prg 압축

- yoonji/home/6/boj_2448_15.java
- yoonji/home/6/mono/boj_2012_greedy.java
- 함수 내의 세번의 재귀 호출(`r,c`, `r+h/2, c-h/2`, `r+h/2, c+h/2`)로 작은 삼각형 3개를 완성해내는데, 각 삼각형의 꼭짓점에 오도록 하려면 어떤 식으로 호출할지 고민하는 과정이 필요하다.
- 더 작아질 수 없는 크기가 됐을 때 별을 찍는다.
- `r,c` 호출은 3개의 삼각형 중 중앙 첫번째, `r+h/2, c-h/2`, `r+h/2, c+h/2` 호출은 3개의 삼각형 중 왼쪽, 오른쪽에 위치하는 삼각형을그린다.
- 큰 그림보다 가장 작은 패턴에 집중해서 그 패턴이 어떻게 그려질지를 고민해야 어떻게 재귀로 풀어낼지도 그려질 것 같습니다.
- 재귀 호출로 생각해내는 연습이 더 필요할듯 싶습니다.
> yoonji: boj 2448 별찍기-11

- yoonji/home/6/boj_2751_20.java
- 어떤 정렬 알고리즘으로 접근할지 고민했지만 (혹시 모를 제한..) 한번에 통과하기 위해 머지정렬을 이용했습니다.
- 직접 머지정렬 로직을 구현하면서 이해하는데 도움이 되었습니다.
> yoonji : boj 2751 수 정렬하기2

- jihoon/home/6-week4/Boj_11650.java
- jihoon/home/6-week4/Boj_11651.java
Point Class로 x,y를 가지고 있으며 comparable을 구현해주었다. 가끔 사용하는 comparable이어서 항상 Comparator와 헷갈린다....
> Jihoon: boj 11650, boj 11651

- yoonji/home/6/boj_10814_23.java
- 자료구조 Map을 사용해서 해결했다.
- 정렬할 때는 Entry를 사용해서 해결했다. (Entry를 두번째 써본것 같은데 아직은 어색한 것 같다)
> yoonji : boj 10814 나이순 정렬

- chris-an/home/2022.06/6.24/Boj_10989.java
수 정렬하기3
처음에 Arrays.sort 로 풀었다가, 효율이 너무 좋지 않아서 다르게 풀어보기 위해서 Counting sort 를 공부할 겸, 풀어봤습니다.
> 효율 측면에서 Arrays.sort < Counting sort
> Jungmin : Boj 10989

- jeongwoo/정렬/Boj1377.java
> Jeongwoo: BOJ 1377 버블 소트

- yoonji/Implementation/String/boj_17413_단어뒤집기2.java
- yoonji/Implementation/String/boj_4396_지뢰찾기.java
- yoonji/Implementation/String/prg_문자열압축.java
- yoonji/Implementation/String/prg_오픈채팅방.java
- `문자열 구현` 연습하고자 풀었습니다.
- 초기:IDE x, 초기 세팅 후:IDE o
- 1h 10m 소요했습니다.(실버5)
- `문자열 구현` 연습하고자 풀었습니다.
- 
- IDE 없이 1시간 소요했습니다.
> yoonji : boj 4396 & 17413 / prg 오픈채팅방 & 문자열압축

- yoonji/DFS/prg_타겟넘버.java
- yoonji/DataStructure/prg_짝지어제거하기.java
- yoonji/Implementation/prg_단체사진찍기.java
- yoonji/Sort/prg_최솟값만들기.java
- 기존에는 String으로 접근해서, 같은 연속되는 알파벳을 찾으면 그 두 알파벳을 제외한 앞뒤를 합치는 것으로 제거했는데, 효율성에서 통과되지 못했습니다.
- 계속해서 두개씩 제거하고 다시 생기는 문자열에 대해 반복적으로 진행하는 것이므로 아래와 같이 진행합니다.
1. 다를 때 혹은 Stack이 비었을 때는 Stack에 `push`
2. 같을 때는 가장 위에 있는 같은 알파벳을 `pop`
- 일반적인 dfs 로직만으로 해결할 수 있었습니다.
- dfs 메서드 내에서 덧셈한 값, 뺄셈한 값으로 각각 재귀 호출합니다.
> yoonji : prg 짝지어제거하기 / prg 타겟넘버 / prg 단체사진찍기

- chris-an/home/2022.07/7.04/Pro_124나라의숫자.java
* 접근 방식을 잘못했음.
HashMap 을 이용하여 10진법을 3진법으로 변환한 값을 가지고 요구하는 124진법 변환을 시도 함.
4->2
2->1
1->0
0->4 
ex) 102 -> 42
ex) 100 -> 24
이런식으로 3진법으로 변환한 값을 charAt 으로 값을 뽑아와서 i+1 값이 0일 경우 i값 변환하면서 i+1 값을 무시하는 로직을 구현하려 했지만,
예외상황이 발생했고, 풀이가 한 시간이 넘어 풀이를 멈춤.
> Jungmin : Programmers - 124 나라의 숫자

- chris-an/home/2022.07/7.05/Pro_기능개발.java
제한 시간 : 1시간
결과 : 시간 내에 풀지 못함.
문제에서 언급한 조건을 잘못 생각하고 있었음. 그래서 맞왜틀 하다가, 결국 시간 내에 못 품..
> Jungmin : Programmers - 기능개발

- yoonji/DataStructure/prg_기능개발.java
- yoonji/Implementation/prg_124나라의숫자.java
- 진법 관련 구현 문제!
- 고려해야했던 두가지는 아래와 같습니다.
```
1. 0으로 나누어 떨어질 때는 '4'가 나타나야하므로, 순서를 {4,1,2}로 정한다.
2. 124로 변환할 때 중간에 나머지가 0이 되면, n을 1개 줄여야한다.
```
- 자료구조를 사용해야한다는 점을 알고 시작해서 더 수월했던 것 같습니다.
- **배열이 있고, 인접한 원소 간의 비교가 필요할 때** 스택과 큐가 사용되는 문제가 종종 보이는데 그때마다 스택 or 큐를 사용할 생각을 잘 못하는 것 같습니다.
> yoonji : prg 기능개발 / 124나라의숫자

- chris-an/home/2022.07/7.06/Pro_더맵게.java
조건
제한 시간 45분 이내
시간내에 푼 문제.
문제에서 언급한 가장 작은 두 수를 뽑기 위해 정렬을 해주어야 한다.
우선순위 큐는 최대 힙(Max Heap) 을 이용하여 구현되고, 트리 형태이기 때문에 검색의 시간복잡도 또한 낮다. 
> 이전에 힙을 직접 구현하면서 삽질해서 그냥 문제 모자마자 우선순위 큐가 떠오름..
> Jungmin : Programmers - 더 맵게

- yoonji/Sort/prg_가장큰수_F.java
- yoonji/Sort/prg_최솟값만들기.java
- 두 수를 비교할 때 직접 앞뒤로 append해서 비교하면 되었다.
- `예외`; 지문에 숫자가 매우 클 수 있기 때문에 문자열로 리턴하는 것이라했으므로 `0000`일 때의 상황을 잘 고려해야헀다.
> yoonji : prg 가장 큰수 / 최솟값 만들기

- chris-an/home/2022.07/7.06/Pro_더맵게.java
- chris-an/home/2022.07/7.09/Pro_가장큰수.java
조건
제한시간 : 30분
> 단순하게 보고 순열을 이용해서 문제를 접근했었는데, 시간복잡도가 100000! 때문에, 런타임 에러가 발생했다.. 문제에서 언급했던 걸 잘 생각해서 로직 설계를 했어야 했는데 그러질 못하고 시간 내에 풀지 못했고? 다른 분이 풀었던 정렬 방법을 참고로 해당 문제를 다시 풀었다.
> Jungmin : Programmers 가장 큰 수

- yoonji/DFSorBFS/prg_게임맵최단거리.java
- yoonji/Implementation/prg_가장긴팰린드롬.java
> IDE 없이 20분 소요
- 기본적인 탐색문제였습니다!
> IDE 없이 1시간 30분 이상 소요..
- 효율성을 맞추는 것은 쉽게 가능했는데, 해당 문제에서의 조건이 아닌 원래 팰린드롬의 조건을 고려하다보니, 여러 조건을 추가해야했던 부분에서 헤맸습니다.
- 이외 설명은 주석으로 추가했습니다.
> yoonji : prg 게임맵 최단거리 & 가장 긴 팰린드롬

- chris-an/home/2022.07/7.10/Pro_소수찾기.java
- chris-an/home/2022.07/7.11/Pro_게임맵최단거리.java
제한시간 : 30분
> 간만에 탐색 문제를 풀어서 30분을 넘겼다.
> Jungmin : Programmers 게임 맵 최단거리

- yoonji/Implementation/prg_예상대진표.java
- 1시간 이상 소요했지만 해결 X
- 문제에서 언급했던 새롭게 숫자를 부여하면서 a와 b가 만나는 라운드 를 구하는 **규칙**이 있을 것 같았는데 그 규칙을 찾지 못해서 `firstTry` 메서드 방식으로 진행했지만 대부분이 불통..
- 규칙을 이해한 후 사용한 로직
- 1과 2가 대결하면, 이긴 숫자가 1이 되는데 이를 이용하면 각 숫자들을 2로 나눠준 몫이 새 숫자가 된다. (이때 홀수는 +1을 해줘야 새 숫자가 잘 부여된다.)
- 결국 두 a,b가 만나서 경기까지 한 라운드를 보면 같은 숫자로 통일된다. 
- 해당 특성을 활용.
> yoonji: prg 예상 대진표

- yoonji/Implementation/Efficiency/prg_순위검색.java
- yoonji/Implementation/prg_이진변환.java
> IDE없이 약 1시간 소요
- String을 다루는 문제에서는 사소한 부분에서 막히는 것 같습니다. 
-  `StringBuilder`는` equals()`가 오버라이딩되어있지 않아서 equals()를 사용할 경우, 주소를 비교한다.  (계속 false가 나온 이유..)
- String 변수를 그냥 다른 String 변수에 대입하면, 깊은 복사가 되기 때문에 서로 영향을 미치지 않는다.
- 예) `String clone = s;`
- String의 `replace()`는 변경된 값을 반환할 뿐, `this` 변수를 바꾸지 않는다.
- 예) `String replace = clone.replace("0", "");`
> IDE없이 1시간 이상 소요
- 꽤 최근에 풀어서 로직 자체는 구현하기 쉬웠습니다. 
- 효율성 테케 일부에서 통과되지 않아서 특정 `코테 점수` 이상이 되는 인원수를 찾을 때 이진탐색을 이용해야 했습니다.
> yoonji : prg 순위검색 & 이진변환 문제

- chris-an/home/2022.07/7.12/Pro_예상대진표.java
제한시간 : 45분
> 문제 접근을 잘못해서 시간 내에 풀지를 못했다.
a와 b 값이 둘 다 n/2 값보다 클 경우를 고려하지 못해서 최종제출 때 절반만 맞게 뜨고 '맞왜틀' 하다가 시간만 지나갔다.
시간이 초과되어 질문하기를 찾아보고 이유를 알게되어 로직을 수정하였다.
> Jungmin : Prg 예상 대진표

- chris-an/home/2022.07/7.15/Pro_괄호회전하기.java
> 시간 내에 푼 문제였고, Stack 을 이용해서 구현 했습니다
> Jungmin : Prg 괄호 회전하기

- chris-an/home/2022.07/7.16/Pro_배달.java
제한시간 1시간
> 이번 문제를 풀면서 간만에 푼 그래프 문제 감을 다시 찾는다 생각하고 풀었다.
역시 간만에 푼 문제라 시간 내에 풀지 못했고, 이 문제에서 플로이드-와샬 알고리즘을 적용해서 풀 수 있는 거 같아 관련 알고리즘 공부를 한 뒤에 풀었다.
> Jungmin : Prg - 배달

- chris-an/home/2022.07/7.17/Pro_2xn타일링.java
제한 시간 30분 이내
소요시간 : 10분
> 간만에 DP 문제를 풀어서 기억을 더듬어 어떤식으로 접근해서 풀었는 지 기억을 되새기는 문제였다.
> Jungmin : Prg 2 x n 타일링

- yoonji/Implementation/prg_후보키.java
- 자료구조를 많이 쓰는 것이 안 좋다는 생각 덕분에 다른 방법을 찾으려한 점 때문에 오래 걸렸습니다.
- 최소성을 만족하는 지를 확인하는 과정에서 어려움을 느꼈습니다.
> yoonji : prg 후보키

- yoonji/Sort/prg_HIndex.java
- H-Index를 `citations` 원소와 관련지어 생각하게 되어서 H-Index의 범위를 고려하는 부분이 어려웠다.
> yoonji : H-Index

- jeongwoo/수학/Pro42842Again.java
완탐 분류에 있는데 수식 사용해서 풀었다.
완탐으로는 어떻게 하는지 찾아봐야겠다.
> 2022-07-21 프로그래머스 42842 카펫

- yoonji/Implementation/prg_카펫.java
> yoonji : prg 카펫

- chris-an/home/2022.07/7.21/Pro_카펫.java
제한시간 : 45 분이내
> 이것저것 수의 공식을 찾느라, 시간을 꽉꽉 채워서 푼 문제였다.
> Jungmin : Prg 카펫

- yoonji/Greedy/prg_큰수만들기.java
- greedy는 구현보다 어렵게 느껴지는 것 같다.
- input 범위가 크다보니 그냥 접근하면 무조건 시간초과가 뜨는데, 어떻게 접근하면 될지 떠오르는 게 어려운 것 같다!
> yoonji : prg 큰수만들기

- chris-an/home/2022.07/7.22/Pro_큰수만들기.java
시간제한 : 1시간 이내
> 문제 설명은 간단하지만, 로직을 짜긴 힘들었다. 여러가지 생각을 가지고 로직설계를 했지만 코드만 복잡했고, 그 복잡한 로직으로 구현했을 때, 틀렸다고 나와서. 로직의 빈틈이 있다는 걸 알게됐다. 현 코드는 다른 분 코드를 참고해서 다시 푼 문제다.
> Jungmin : Prg 큰 수 만들기

- yoonji/DFSorBFS/prg_피로도.java
- 던전 통과 수를 내림차순으로 순회하여, max값이 바뀔 때 바로 종료하도록 했습니다.
- dfs로 해결했습니다.
> yoonji : prg 피로도

- jeongwoo/BruteForce/Pro87946Again.java
완전 탐색으로 다시 풀었다. 기존 코드는 순열 폴더에 있다.
> 2022-07-23 프로그래머스 87946 필요도

- jeongwoo/BruteForce/Pro17679.java
1. solution에서 while(true)를 되도록 지양하고 싶었지만 더 좋은 로직이 생각이 안 났다..
2. downBlock에서 if문 break를 안 걸어서 시간이 조금 걸렸다.
> 2022-07-25 프로그래머스 17679 프렌즈 4 블록

- jeongwoo/구현/Pro68645.java
- jeongwoo/구현/Pro68645Fail.java
1. 위에서 아래, 왼쪽에서 오른쪽, 아래에서 위로 가는 이동에 대해 메소드를 만들고 인덱스로 접근하려고 했었다.
2. 인덱스로 하고 제출하니까 시간 초과가 떴다.
3. 앞으로 트리처럼 생긴 그림이 나오면 왼쪽으로 다 밀고 접근해 봐야겠다.
4. 될 것 같아서 시간 오래 썼는데 안 돼서 약간 아쉽다.
> 2022-07-26 프로그래머스 68645 삼각 달팽이 

- yoonji/DP/prg_프렌즈4블록.java
1. `(1,1)`부터 시작해서 **좌,상,좌상대각선**만 체크하면 되는 것을 떠올리지못했습니다.
➡️ DP를 이용해서 위치 기준 좌&상의 블록을 확인해 스퀘어모양이 되는지 검사한 후, `true` 표시
2. 표시된 블록을 보드에서 삭제하여 남은 블록을 밑으로 내려야 한다.
이때 먼저 제거 boolean 표시를 하고, 다시 전체 블록을 순회하면서 제거(`.` 표시)하는 방식이 효율성이 떨어질거라 생각해서 실행에 옮기지 X
➡️ but, 한 바퀴를 모두 돌면서 스퀘어로 동일한 블록을 모두 찾은 후에, 제거해야하므로 어쩔 수 없이 2번 순회해야한다.
3. 기존에는 `ArrayList`안에 `char`타입 배열을 넣어서, 공통된 square일 때 제거하면, 자동으로 값들이 자리를 옮기는 방식을 생각했는데
매번 행의 길이가 바뀌고, 그때마다 최소의 공통 길이를 찾아야하므로 배열로 바꿔야했습니다.
+ square 블록을 찾을 때, 이미 제거된 블록(`.`)인 경우 확인안해도되므로 pass하는 로직 필요합니다.
> yoonji : prg 프렌즈4블록

- chris-an/home/2022.07/7.26/Pro_삼각달팽이.java
제한시간 : 1시간
> 시간 내에 풀지 못해서, 바로 다른 분 코드 참고 함. 이번 문제 접근은 잘 했는데 좀 꼬아서 생각했던 거 같음. 풀다가 2차원 배열을 row = x, col = y 로 생각해서 좌표 값처럼 생각해야 하는 거라 깨달았는데, 역시나 그렇게 풀었던 게 맞았다. 시간이 흐른뒤 다시풀어봐야 함.
> Jungmin : Prg 삼각 달팽이

- chris-an/home/2022.07/7.27/Pro_영어끝말잇기.java
제한시간 : 30분 이내
> 전에 풀었던 문제라, 로직 구현은 쉬웠고, 자료구조를 어떤걸 사용할지 고민하면서 풀었던 문제였다.
> code : Prg 영어 끝말잇기

- yoonji/Implementation/prg_영어끝말잇기.java
> IDE 없이 20분 소요
- 이미 언급된 단어이거나, 끝말을 잇지 못하는 단어가 나타날 경우, `[번호, 순서]`를 계산하고 중지합니다.
- 단순 구현 문제!
> yoonji : prg 영어끝말잇기

- chris-an/home/2022.07/7.28/Pro_타겟멤버.java
제한시간 : 1시간 이내
> 처음 풀었던 때와 다르게, 로직 구현이 생각나는 부분이 많았다. dfs 두 개를 호출해서 모든 경우의 수를 만드는 방식을 다시 연습하게 된 문제다.
> Jungmin : Prg 타겟멤버

- yoonji/DataStructure/prg_짝지어제거하기.java
> IDE없이 17분 소요
- 스택에 넣다가, 같은 값이 연속으로 나오면 값을 제거하고, 문자열만큼 순회하고 났을 때 스택에 값이 없으면 성공, 있으면 실패
- 후입선출이므로 스택!
> yoonji : prg 짝지어제거하기

- chris-an/home/2022.07/7.29/Pro_짝지어제거하기.java
제한시간 : 30분 이내.
> 풀고 나서 전에 푼 걸 봤는데, 현 코드 로직이 불필요한 게 너무 많았다. 문제를 더 잘 이해 했다면 더 쉽게 구현할 수 있었다는 문제라는 걸 뒤늦게 알았다.
> Jungmin : Prg 짝지어 제거하기

- yoonji/Implementation/구름_근묵자흑.java
- yoonji/Implementation/구름_사은품교환하기.java
두 문제 모두 구현 문제였고, 규칙을 찾지 않고 문제를 풀려하면 일부 테스트케이스에서 통과되지 않았습니다.
문제자체가 구현문제 같아서 규칙이 있을 거란 생각을 안하고 냅다 풀어버려서 푸는데 꽤 오래 걸렸습니다.
특히 사은품교환하기 문제가 오래 소요되었네요
> yoonji : goorm 근묵자흑 / 사은품교환하기

- jeongwoo/Stack & Queue/Pro12973.java
처음에 문자열을 이용해서 substring으로 제거하려고 했다.
이렇게 되면 반복문을 이중으로 돌게 돼서 문자열 길이인 1,000,000 * 1,000,000으로 시간 초과가 났다.
그래서 생각한 게 스택이었다.
> 2022-08-02 프로그래머스 12973 짝지어 제거하기

- yoonji/DFSorBFS/prg_거리두기확인하기.java
> IDE 없이 1시간 이상 소요
- bfs로 풀어야 한다는 것을 알았는데, 맨해튼 거리를 큐에 같이 넣어줘야한다 생각하는 바람에 코드를 잘 못 작성했다.
- bfs를 한번 호출했을 때 맨해튼 거리가 2이상이 되면 더이상 확인하지 않아도 된다는 전제를 기반으로 풀지 못했다
> yoonji: prg 거리두기확인하기

- chris-an/home/2022.08/8.04/Pro_거리두기_확인하기.java
제한시간 : 45분이내
> 로직 설계를 복잡하게 한 부분도 있고, 시간내에 풀려다가 마음이 급해져서 로직 설계가 마무리되지 않은 상태에서 구현에 들어갔음. '맞왜틀' 하다가 시간이 초과됨. 좀 더 차분하게 로직 설계를 했었으면 좋았을 거 같음.
> Jungmin : Prg - 거리두기 확인하기

- chris-an/home/2022.08/8.08/Pro_튜플.java
제한시간 : 45분 이내
> 한 번 풀었던 문제라 문제 로직 설계는 쉬웠다. 그렇지만 구현할 때 Map의 Value 값 정렬하는 부분이 바로 떠오르지 않은 점이 아쉬웠다. 이번에 다시 익히도록.
> Jungmin : Prg 튜플

- chris-an/home/2022.08/8.09/Pro_전화번호목록.java
제한시간 : 45분 이내
> 다시 푼 문제라 복습 개념으로 푼 문제였다.
> code : Prg 전화번호 목록

- yoonji/DataStructure/prg_전화번호목록_hash.java
> IDE 없이 45분 내 진행
- hash로 풀어본 문제
- 배열에 대한 반복문을 돌면서 해당 배열의 substring이 이미 전화번호부(set)에 있는 전화번호인지 체크한다.
- 순차적으로 진행하기 때문에 정렬을 해주지 않으면 `1111, 111`인 경우 통과되지 않는다.
> yoonji : prg 전화번호목록(hash)

- chris-an/home/2022.08/8.10/Pro_프린트.java
###조건
제한시간 : 45분 이내
> 두 번째 푼 문제. 첫번째 풀 땐 큐로 어찌어찌 하여 풀어서, 이번엔 우선 큐를 사용하자 생각을 했다. 우선큐로 어떻게 구현할까 고민하다가 로직 설계하는 데 시간을 많이 썼다. 시간초과.
> Jungmin : Prg 프린트

- chris-an/home/2022.08/8.11/Pro_주식가격.java
제한시간 : 30분
> 몇 달전에 푼 문제인 거 같은데, 또 못 풀었다.. 20분 고민하고 그냥 내가 또 문제 이해를 못하는 거라고 단정짓고, 문제 이해를 위해 참고 글을 봤다. 역시나 문제설명이 친절하지 않았다.(솔직히 거지 같다) break; 라는 코드가 필요했다.
> Jungmin : prg 주식 가격

- chris-an/home/2022.08/8.12/Pro_전력망을두개로나누기.java
제한시간 : 1시간 이내
> 그래프 문제를 정말 간만에 풀어서, 시간이 너무 오래걸렸다. 인접행렬, 인접리스트 여러 문제를 다시 풀어야할 듯 싶다. 이번 문제는 그래프 문제로 인접행렬 또는 인접리스트로 bfs 또는 dfs 로 구현이 가능한 문제 같다.
> Jungmin : Prg 전력망을 두개로 나누기

- chris-an/home/2022.08/8.13/Pro_모음사전.java
제한시간 : 45분 이내
> dfs 문제를 간만에 풀어서, 금방 접근하지 못한 거 같음. 원하는 출력값을 얻기 위해 이것저것 시도 하다가 시간초과가 됨. 너무 복잡하게 생각했던 거 같음 (1시간 반 정도 소요)
> Jungmin : Prg 모음사전

- chris-an/home/2022.08/8.16/Pro_구명보트.java
제한시간: 45분이내
> 시간 내에 풀지 못했지만, 접근은 잘한 거 같아 시간을 더 투자했으면 풀 수 있었던 문제였다. 이제 그리드 문제 스타일이 어떤 건지 감이 왔다.
> Jungmin : Prg 구명보트

- chris-an/home/2022.08/8.17/Pro_스킬트리.java
조건
제한시간 : 1시간 이내
> 자료구조를 이용해서 풀었다. 코드 작성할 때, 변수명에 더 신경쓰면 좋았을 거 같음.
> Jungmin : prg 스킬트리

- chris-an/home/2022.08/8.18/Pro_점프와순간이동.java
제한시간 : 30분 이내
> 금방 풀렸던 문제다. 다 풀고 전에 풀었던 방식이랑 비교해보니 코드가 더 간결해지고 이해하기도 쉬워졌다.
> Jungmin : Prg 점프와 순간이동

- chris-an/home/2022.08/8.19/Pro_방금그곡.java
제한시간 : 1시간 이내
> 한 시간 이내에 풀지를 못했다.. 하 replaceAll 왜 생각이 안났지..?
> Jungmin : Prg 방금 그곡

- chris-an/home/2022.08/8.22/Pro_파일명정렬.java
- chris-an/home/2022.08/8.23/Pro_올바른괄호.java
제한시간 : 30분 이내
> 풀었던 문제라 금방 접근 했다.
----
제한시간 : 1시간 이내
> 문자열 처리 때문에 시간이 오래걸렸지만 시간 내에는 풀었다. StringBuilder 를 조심 해야할 듯 싶다.
> Jungmin : programmers : 올바른 괄호, 파일명 정렬

- chris-an/home/2022.08/8.24/Pro_n진수게임.java
제한시간 : 30분 이내
> Integer.toString() 메서드를 잊지 말자...
> Jungmin : Prg - n 진수 게임

- jeongwoo/수학/Pro17687Again.java
1. 지난번에는 나머지로 n진수를 구했는데, Integer.toString()으로 더 쉽고 간편하게 구할 수 있다.
2. String이니까 +=보다는 Builder를 사용하면 더 빠르다.
> 2022-08-24 프로그래머스 17687 N진수 게임

- chris-an/home/2022.08/8.25/Pro_다음큰숫자.java
> code : Prg 다음 큰 숫자

- jeongwoo/수학/Pro12911.java
어제 n진수 변환 Integer.toString에 대해 익혀서 그런지 쉽게 풀었다.
코테 문제가 다 이랬으면 좋겠다.
> 2022-08-25 프로그래머스 12911 다음 큰 숫자

- chris-an/home/2022.08/8.26/Pro_3xn타일링.java
제한시간 : 45분이내
> 음..DP 는 코테에 나오면 버려야하나 심히 고민됐던 문제였다. 시간 내에 풀지 못했고, 규칙만 찾다고 결국 구글링해서 점화식을 확인했다. 아 ps: 이거 분명 푼 건데 백준에서..왜 못풀겠지
> Jungmin : Prg 3 x n 타일링

- jeongwoo/수학/Pro87390.java
처음에는 각 배열에 값을 다 넣어 줘야 하는지, 그렇게 되면 int[]로는 초과하니까 long[]으로 해야 되는지, 아니면 ArrayList로 접근해야 되는지 고민했다. n <= 10^7이어서 어떻게 넣어 주든 시간 초과가 날 것 같아서 다른 방법으로 접근하였다. 배열에 알맞는 값을 다 넣는 것보다는 원하는 구간에 대한 값만 가지고 오면 된다는 게 생각나서 몫과 나머지로 접근하였다.
> 2022-08-29 프로그래머스 87390 n^2 배열 자르기

- chris-an/home/2022.09/9.01/Pro_가장큰정사각형찾기.java
제한시간 : 45분 이내
> 처음에 간단한 문제라 생각하고 bfs 로 접근하고 바로 코드로 구현하다가, 시간 복잡도 문제가 발생할 거 같다는 생각으로 다시 로직을 생각하느라 시간을 다 썼던 거 같다. 시간 내에는 다 풀지 못했고 바로 다른 분 풀이를 참고 했는데, DP 문제라는 건 유추했지만 풀이 시간을 더 준다 하더라도 방법을 찾기는 쉽지 않았을 거 같다.
> Jungmin : Prg 가장 큰 정사각형 찾기

- chris-an/home/2022.09/9.02/Prg_JadenCase문자열만들기.java
- chris-an/home/2022.09/9.02/Prg_압축.java
- chris-an/home/2022.09/9.02/Prg_최댓값과최솟값.java
> Jungmin : 압축, 최댓값과 최솟값, Jaden Case 문자열 만들기

- jeongwoo/문자열/Pro12939.java
> 2022-09-04 프로그래머스 12939 최댓값과 최솟값

- chris-an/home/2022.09/9.06/Pro_N_Queen.java
제한시간 : 1시간 이내
> 한 시간 꽉 채워서 풀었다. 이전에 푼 기억이 있어서, 기억 상기용으로 한 30~40분 정도 고민했고 바로 구현했다.
> Jungmin : Prg N_Queen

- yeonsup/package.json
- yeonsup/programmers/01_runRace.js
1. callings를 loop 하여 callings의 값으로 player의 인덱스를 찾아 해당 player와 앞 선 player와 swap
2. 시간 복잡도 개선을 위해 map을 사용하여 등수를 저장하고 map 저장된 등수를 활용하여 swap
> 2023-05-22 프로그래머스 178871 달리기 경주

- chris-an/src/main/kotlin/programmers/implement/programmers_0523.kt
- 처음에는 간단하게, 각 그림당 점수를 담은 Map 을 만든 뒤, 이중포문으로 탐색해서 값 만들어서 intArray 로 return 시키기
- 위 설계가 통과된 후, 코드양을 줄이는 생각하기
- stream zip 함수를 통해 두 array 를 묶어 map 을 만드는 과정과
- map 컬렉션함수를 통해서 sumof 계산하여 코드 양 줄이기
> 프로그래머스 - 추억 점수

- yeonsup/programmers/02_walkPark.js
- yeonsup/programmers/02_walkPark_2.js
- yeonsup/programmers/03_memoryScore.js
- yeonsup/programmers/03_memoryScore_2.js
- 자바스크립트는 느슨한 언어라 타입 명시가 명확하지 않아 정수 타입 문제로 인해 애를 먹었다. 정수인 값들은 정수인지 확인하거나 정수 타입으로 캐스팅을 하는 코드를 넣어야 한다.
- 내가짠 코드는 map을 사용하지 않았다. 그랬더니 중복된 코드도 많아지고 알아보기 어려운 코드가 되었다.
- map을 적절히 잘 활용하는 것은 코드를 최적화하는 데 많은 도움이 된다.
- map과 forEacg함수를 사용하여 간단하게 구현하였다.
- 다른 사람이 한 코드에는 reduce라는 함수가 있었다.
- 이 함수를 활용하니 코드가 확 줄어들었다.
- reduce는 배열의 요소를 콜백 함수를 통해 반복하여 하나의 return 값을 합산하는 함수이다.
- 첫번째 인자로 들어오는 값이 합산된 값이며, 배열 요소를 잘 활용하여 알고리즘을 구현하면 원하는 합산 값을 얻을 수 있다.
- 시간 복잡도는 차이가 없지만 내부 함수를 사용하면 구현을 간단하게 할 수 있다.
> 2023-05-22~2023-05-24 프로그래머스 공원 산책, 기억 점수

- yeonsup/programmers/02_walkPark.js
- yeonsup/programmers/04_cardBundle.js
- yeonsup/programmers/05_keymap.js
1. goals에 있는 문자열을 loop 돌려 해당 문자열이 카드1 또는 카드2 에 있을 경우 카드에 있는 단어 하나를 앞에서 부터 하나씩 가져온다.
2. 그렇게 해서 만들어진 문장을
3. goals와 비교하여 맞으면 Yes 아니면 No를 출력한다.
2023-05-27 프로그래머스 160586 대충 만든 자판
1. map 을 사용하여 각 문자의 최소 횟수를 저장하여 map을 초기화 한다.
2. targets의 문자를 하나씩 비교하여 최소 횟수를 누적 합산하고 중간데 없는 단어가 있으면 undefind로 하여 합산이 안되게끔 처리한다.
3. undefined면 -1를 출력 아니면 누적 합산된 정수 값을 출력한다.
> 2023-05-25~27 2문제

- chris-an/src/main/kotlin/baekjun/baekjun_0601.kt
- chris-an/src/main/kotlin/programmers/implement/programmers_0524.kt
- chris-an/src/main/kotlin/programmers/implement/programmers_0525.kt
> 
>
> 구현 OR 정렬 두 가지 카테고리로 나눌 수 있던 문제였다.
> ~ 2023-06-01 프로그래머스 2, 백준1

- chris-an/src/main/kotlin/programmers/implement/programmers_0603.kt
- chris-an/src/main/kotlin/programmers/implement/programmers_0604.kt
> 여러 예외케이스가 존재할 거 같았지만, 처음 로직설계대로 문제를 풀었을 때 통과 함.
> '카드를 다 사용하지 않고도 goal 단어조합을 만들 때' 케이스를 고려하지 못해서 시간 낭비를 함.
> 2023-06-04 프로그래머스 2문제

- chris-an/src/main/kotlin/leetcode/leetcode_0606.kt
- chris-an/src/main/kotlin/programmers/implement/programmers_0605.kt
- chris-an/src/main/kotlin/programmers/implement/programmers_0606.kt
> 하..오역
> 아직도 자바스럽다.. map > count 를 이용했다면 코드가 간결했을 것 같다.
> String 을 map 으로 처리할 수 있다는 걸 알게 된 문제  withIndex() 함수를 이용하여 `Iterable<T>.map` 로 처리
> 2023-06-06 프로그래머스 2문제, 리트코드 1문제

- chris-an/src/main/kotlin/leetcode/leetcode_0607.kt
- chris-an/src/main/kotlin/programmers/implement/programmers_0607.kt
> 이후에 스택으로 풀면 여러 조건을 주지 않고, 스택 특징을 이용하여 잘 풀 수 있을 거 같음. `removeFirst()`, `first()` 두 함수 기억
> 기존에 시간복잡도를 n에 2승으로 for 문 두 개로 풀 수 있지만, hash 를 이용하여 검색하는 방법으로 시간 복잡도를 줄일 수 있다.
> 2023-06-07 프로그래머스 1문제, 리트코드 1문제

- chris-an/src/main/kotlin/leetcode/leetcode_0608.kt
- chris-an/src/main/kotlin/leetcode/leetcode_0610.kt
- chris-an/src/main/kotlin/programmers/implement/programmers_0608.kt
> 음.. 그냥 구현 문제이다..
> 음.. 이 문제는 일트 시도에 failed 했는데, 그 이유는 처음 로직은 홀수 일 경우, 마지막 index 값을 추가로 더해주는 로직으로 작업을 했다.. 내 로직에 빈틈이 있어서 failed
> 이 문제는 그냥 구현 문제다. 이번엔 코틀린 Iterable 확장 함수를 이용하여 한 번 풀어보고 싶어서 도전했다.. 그런데 진짜 실제 코테엔 그러면 안될 듯 싶다..
> 2023-06-10 프로그래머스 1문제, 리트코드 2문제

- chris-an/src/main/kotlin/leetcode/leetcode_0611.kt
- chris-an/src/main/kotlin/leetcode/leetcode_0612.kt
> 제한조건이 크지 않았지만, 만약 컸더라면 2번째 방법을 이용하여 처리하는게 훨씬 효율이 좋을 것이다.
> 자리 수를 찾기 위해선 10의 자리수로 접근하면 더 효율이 나아질 것이다.
> 2023-06-12 리트코드 2문제

- chris-an/src/main/kotlin/leetcode/leetcode_0613.kt
- chris-an/src/main/kotlin/leetcode/leetcode_0615.kt
> 이 문제는 다시 풀어야할 것 같다. 처음 설계를 잘못해서 인덱스 관리하는 부분이 너무 복잡해졌다. 가장 중요한 건, 길이를 한 쪽으로 맞추는 것!
> 해당 문제를 자바로 풀었다면, 더 복잡했을 것 같다. 코틀린으로 문제를 풀 경우, 좀 더 가독성을 높여 코드를 작성할 수 있었다.
> 2023-06-15 리트코드 2문제

- chris-an/src/main/kotlin/leetcode/leetcode_0617.kt
- chris-an/src/main/kotlin/leetcode/leetcode_0617_2.kt
- chris-an/src/main/kotlin/leetcode/leetcode_0618.kt
> 2023-06-18 리트코드 3문제

- yeonsup/java/bj/Bj_6603.java
- yeonsup/java/bj/Boj_1004.java
- yeonsup/java/bj/Boj_21919.java
- yeonsup/java/leetcode/ConfusingNumber.java
- yeonsup/java/leetcode/FindAnagramMappings.java
- yeonsup/java/leetcode/MaxDistanceInArrays.java
- yeonsup/java/leetcode/OneEditDistance.java
- yeonsup/java/leetcode/PalindromePermutation.java
- yeonsup/java/leetcode/PerformStringShifts.java
- yeonsup/java/leetcode/ReverseWordsInaString.java
- yeonsup/java/leetcode/ShortestWaytoFormString.java
- yeonsup/java/leetcode/WiggleSort.java
- yeonsup/js/toss/1.js
1. 2023 토스 코딩테스트 1번 문제
2. 자바 알고리즘 스터디 3문제
3. 리트코드 9문제
> 2023-07-08 ~ 2023-08-21 총 13문제
