Java-Algorithm-Study/algorithm-problems

jiyoung/home/2022-03-07/boj_10820.java, jiyoung/home/2022-03-07/boj_11655.java, jiyoung/home/2022-03-07/boj_2743.java
- 간만에 쉬운 문제 !  
|메모리|시간|
|:---:|:---:|
|17652 KB|208 ms|
- 아스키코드를 활용
- 대문자와 소문자로 기준을 나누고 다시 각각 반으로 나누었을 때 'n(또는 N)' 보다 작거나 같을때는 13을 빼고, 그보다 클 때는 13을 더해주는 식으로 계산하였다.
|메소드|메모리|시간|
|:---:|:---:|:---:|
|**bazzyung()**|15998 KB|156 ms|
|**boj()**|14256 KB|100 ms|
- 길이가 4인 배열에 소문자, 대문자, 숫자, 공백이 순서대로 들어갈 수 있도록 하였다.
- 백준 공유 코드에서는 각 문자 형태에 맞는 변수 4개를 만들어 그 변수를 출력하는 형식으로 짜여 있었다.
|메소드|메모리|시간|
|:---:|:---:|:---:|
|**bazzyung()**|14212 KB|124 ms|
|**boj()**|15004 KB|128 ms|
=> Jiyoung : BOJ 2743 단어 길이 재기 / 11655 ROT13 / 10820 문자열 분석

yoonji/home/3/09/boj_1934.java, yoonji/home/3/09/boj_2609.java
- 2609번에서 이용한 함수 그대로 사용하였다.
- 최대공약수
1. smaller에 대해 2, smaller-1까지 나눠떨어지는 수를 모두 구한다.
2. 리스트의 뒤에서부터 bigger에 나눠떨어지는 값을 찾으면 바로 리턴한다.
> 수정 : `gcd_withEuclideanAlgorithm()` 참고
> 🏴󠁧󠁢󠁷󠁬󠁳󠁿  `유클리드 호제법` : 두 자연수 a를 b로 나눈 나머지가 r이면, a,b의 최대 공약수 == b와 r의 최대공약수
- 최소공배수
1. bigger에 대해 * i++을 진행하면서 smaller와 나눠떨어지면 바로 리턴한다.
> 수정 : `solveLCM_withGCD()` 참고
> 앞서 구한 gcd를 이용해서 lcm을 간편히 구할 수 있다.
> 🏴󠁧󠁢󠁷󠁬󠁳󠁿 `두 수 a,b를 곱한 m을 최대공약수 gcd로 나누면 최소 공배수가 된다.`
- 피드백 후의 코드 길이가 거의 400줄 이상이 줄었다. 👍 
- 수학적으로 접근하는 것이 더 이과적인 방법이고, 평가 입장에서도 똑똑하게 볼것같다 (?)
=> yoonji : boj 1934 최소공배수/ 2609 최대공약수와최소공배수

yoonji/home/3/18/boj_11052.java, yoonji/home/3/18/boj_11727.java, yoonji/home/3/18/boj_9095.java
- 1,2,3으로 N을 만드는 경우의 수
- 주석에서
`1.`  for문으로 푼 경우
`2.`  재귀 + memoization으로 푼 경우
=> 백준 채점현황에서는 2번이 조금 더 효율이 높다.
2x1로 도출
1x2로 도출
2x2로 도출
1x2와 2x2를 섞은 조합으로 도출
예시👇 
2x1 : 1
2x2 : 3
2x3 : 5 = dp[1]*2 + dp[2]
2x4 : 11 = dp[2]*2 + dp[3]
2x5 : 21 = dp[3]*2 + dp[4]
**점화식 D[N] = D[N-1] + D[N-2]*2**
- 1x2와 2x2 섞은 조합을 생각하지 못했음
- 모든 경우의 수에 대해 최댓값으로 지정한다.
- DP 배열의 index는 카드의 갯수를, 값에는 최댓값을 넣는다.
- 카드 i개를 살 때 카드 i개를 만들 수 있는 모든 카드 조합의 경우의 수를 구해서 최댓값을 구한다.
- 바깥 for문을 각각의 카드 구매 갯수를 기준으로 두고, `이중 for문`을 돌아야겠다까지는 갔는데.. 내부 for문을 어떻게 둬야할지 답이 안나왔다.
- 결정적으로 점화식 정의하지 못함
=> yoonji : boj 9095 1,2,3 더하기 / 11727 2*n 타일2 / 11052 카드 구매하기

yoonji/home/3/19/boj_10844_2ndTry.java, yoonji/home/3/21/boj_11053.java, yoonji/home/3/21/boj_14002.java, yoonji/home/3/21/boj_2193.java, yoonji/office/3/22/prg_124나라의숫자.java, yoonji/office/3/22/prg_3진법뒤집기.java, yoonji/office/3/22/prg_로또.java, yoonji/office/3/22/prg_약수개수와덧셈.java
- D[N] : N자리 이친수 갯수
- 자릿값과 자릿수를 이차원으로 표현하였다.
- 이외 설명은 주석으로 작성하였습니다.
1. 모두 배열의 길이를 1로 설정 (최소 배열의 길이는 1)
2. 이중 for문 : i보다 앞에 위치한 j들과 비교
2-1. 뒤의 값(i)이 더 커야 한다.
2-2. 동시에 크기가 더 큰 값의 부분수열의 길이(dp[i])가 작은 값의 수열길이+1(dp[j]+1)보다 작으면, 부분수열에 포함되지 않은것이므로 +1
2-3. 조건 모두 충족 시 부분 수열에 포함됨
2-4. 내부 for문 종료 시, max값을 뽑아서 가장 긴 부분 수열의 상태를 업데이트함.
⚠️  input이 최솟값 1일 때 for문을 돌지 않으므로 max 값은 1로 초기화해야 올바른 답이 나옴. 
- 11053 문제에서 로직 추가
- 가장 긴 증가하는 수열에 해당하는 수들을 출력하기 위해 배열 `dp`를 뒤에서부터 순차적으로 방문하며 max값과 일치하는 인덱스에 해당하는 `nums` 배열 원소를 list에 추가하였다.
- 값들을 출력 : 뒤에서부터 출력해주었다.
=> yoonji : boj 2193 이친수

yoonji/home/3/25/boj_2156.java, yoonji/home/3/25/boj_9465.java
- 참고한 풀이는 대각선의 `dp[i-1]`와 `dp[i-2]`중 max값으로 값을 구하는데, 더 그 전의 것을 고려하게 되면 대각선에 있는 `i-1`과 `i-2`가 고려되지 않은 dp가 된다.
- 내 풀이(시간초과) : 해당 값까지 오는데에 모든 dp 중 최댓값을 구하는 방식
- dp는 작은 문제로 큰 문제를 해결할 수 있다는 점에서 효율이 있는 방식인데, dp의 관점으로 문제를 해결하지 못하고 있는 듯하다. (특히 이번 풀이는 완전탐색으로 푼듯하다)
- 점화식 : DP[N] = N까지의 포도주 양 최댓값 (자리 N의 포도주를 포함한 경우와 포함하지 않은 경우의 최댓값을 구한다.)
- 연속 3개의 포도주를 잡지 않도록 하는 것을 어떻게 처리해야할지 고민하였고, N을 `포함한 경우`와 `포함시키지 않는 경우`로 구분해야겠다 생각했다.
- 이를 코드로 구현하는 과정에서 막혔다.
아래 중 max값을 찾는다.
- 포함하는 경우 : 3전의 최댓값 + -1전+현재 vs 2전의 최댓값+현재  `dp[i-3] + arr[i-1] +arr[i]`  VS. `dp[i-2] + arr[i] `
- 포함하지 않는 경우 : `dp[i-1]` (전 위치의 포도주까지의 최댓값과 동일한 값으로 지정)
예정
=> yoonji: boj 9465 스티커 / 2156 포도주시식

yoonji/home/4/01/boj_15649.java, yoonji/home/4/01/boj_15650.java, yoonji/home/4/01/boj_9095_BruteForce.java
1. T만큼 반복문을 돈다.
2. sum이 0인 상태로 dfs를 호출한다.
3. dfs 내에서 1,2,3을 반복하며 sum에 더하여
3-1. dfs를 재귀호출하는데 if문에 의해 sum이 목표값이 되거나 지나치면 return하여 해당 재귀는 중단한다.
- 중복되는 수를 피하고자 조건문을 추가했지만, 원하는 대로 답이 출력되지 않았다.
- 방문을 체크하는 배열 `visited`를 이용해서 중복을 피할 수 있었다.
- dfs로 푸는 것에  더 익숙해져야함을 느낀다.
- N과 M(1)을 풀고 N과 M(2)를 푸니 접근 방식이 중요하다는 걸 느꼈다
- 전자는 중복인 경우를 고려해야하므로 visited 방문 배열을 이용했지만
- 이번에는 중복을 고려해야하지만 오름차순으로 정렬하면 되기 때문에 for문의 시작을 현재 숫자값으로 지정하기만 하면 된다.
=> yoonji: boj 9095 1,2,3 더하기(Brute Force) / 15649 N과 M(1) / 15650 N과 M(2)

jeongwoo/home/2022-03/30/Boj1476.java, jeongwoo/home/2022-03/31/Boj1748.java, jeongwoo/home/2022-03/31/Boj6064.java
-아이디어
1. N과 M보다 작거나 같은 두 자연수 x, y로 해를 나타낸다
2. x % N, y % M으로 표현할 수 있음
3. x, y가 같은 숫자가 될 때까지 years++;
4. 안 나온다면 -1
--> 시간 초과
10 12 3 9
1. x에 맞는 years를 구한다.
2. 위 테스트 케이스의 경우 x = 3이니까 가능한 years = 3, 13, 23, ... -> years = Ni + x ( i = 1, 2, 3, ...) years < lcm(N, M)까지
3. 가능한 years에서 y를 구한다. y = years % M
-시간 복잡도
1. O(NM)
2. O(lcm(m, n))
안 될 거 알았지만 일단 MN까지 하는 걸로 접근해 보았다.. x부터 구하고 등차 수열처럼 증가하면서 y를 구하면 더 빠르고, 최댓값을 lcm으로 둬야 한다. lcm은 생각도 못 함.
--
-아이디어
1. n을 입력 받으면 1부터 n까지 숫자 이어 쓰기
2. 1부터 n까지 숫자를 다 입력 받지 말고 자릿수만 계산하면 된다
3. n은 최대 1억이니까 일, 십, 백, 천, 만, 십만, 백만, 천만, 억 자릿수 + 십억 하나
문제에서 요구하는 게 자릿수인 만큼 직접 다 써서 구하려고 하지 말고 자릿수로 접근해야 된다
=> Jeongwoo: BOJ 6064 카잉 달력, BOJ 1748 수 이어 쓰기 1

jihoon/home/4-5/Boj_15663.java, jihoon/home/4-5/Boj_15664.java
이전 문제에서와 로직은 똑같고 차이점은 1~n까지의 숫자를 고르는 것이 아니라 주어진 배열에서 숫자를 고르는 것이다. numbers을 전역변수 배열로 만들어서 수를 고르게 하였다.
이전 문제들과 똑같이 수를 뽑되, 중복된 값만 제거하면 되었다. 처음에 set을 생각했지만 set은 순서가 엉망이 되어버렸기 때문에
List으로 만들어서 List에 넣으면서 contains을 써보았다. 이 문제에서는 시간 초과가 안 났던 것으로 기억하지만 이후 문제에서는 시간초과가 났다. 값을 넣을 때마다 contains메서드로 O(N)만큼 검색을 해야 하니 시간이 오래 걸린 것이다.
set을 이용하면서 순서를 기억할 방법을 찾다가 삽입된 순서를 기억하면서 중복을 제거하는 LinkedHashSet 자료구조가 있다는 점을 알게 되었다.
=> Jihoon: Boj 15663 / Boj 15664

chris-an/home/4.09/Boj_14501.java, chris-an/home/4.09/Boj_14889.java, chris-an/home/4.09/Boj_1759.java
알파벳이 암호에서 증가하는 순서의 배열이고 두 가지 조건을 만족시키기 위해서 방문처리로 dfs 로직으로 증가하는 배열 중, 조건으로 걸러주었습니다. 전에 풀었던 문제와 유사해 금방 접근할 수 있었습니다.
---
문제 풀 때, 로직 설계는 잘 된 거 같은데 구현하는 게 힘들었습니다...
재귀에 이해도가 많이 부족했던 거 같습니다. 
이번 문제를 통해서 재귀함수 구현하는 사고 유연성이 좀 넓혀진 거 같습니다.
---
풀었지만, 너무 주먹 구구식으로 문제를 접근해서 푼 느낌입니다.
1 - 두 팀 전체의 팀원을 만들 수 있는 리스트를 만듭니다. `1 ~ 중간 (스타트)`,  `중간 ~ 끝 (링크)`
2 - 능력치 조합을 통해 더해줍니다.
3 - 두 팀 능력 차이를 비교해주고, 최소 차이를 찾습니다.
---
=> Jungmin : Boj 1759 / Boj 14501 / Boj 14889

jihoon/home/4-9/Boj_14501.java, jihoon/home/4-9/Boj_14889.java, jihoon/home/4-9/Boj_1759.java
조합으로 가능한 모든 암호들을 만든다음 모음의 개수를 세도록 했다. 모음이 하나도 없거나 L-2보다 많이 나온 경우(자음이 2개 미만으로 나온 경우)를 제외하도록 했다.
주석으로 보시라
depth == N / 2일때 모든 경우를 구한다음 그 배열의 절반만큼 루프를 돌며 서로 대칭을 이루는 팀을 스타트 팀과 링크팀으로 구분하였다.
예를 들면 1, 2, 3, 4가 나온 경우 4C2의 조합의 경우는,
1, 2
1, 3
1, 4
2, 3
2, 4
3, 4
여기서 (1, 2) <-> (3, 4), (1, 3) <-> (2, 4), (1, 4) <-> (2, 3)이 각각 스타트와 링크 팀이 되는 경우다.
각 팀마다 이중루프를 돌면서 팀의 능력치를 더한다음 최소치를 구했다.
=> Jihoon: Boj 1759 암호 만들기 / Boj 14501 퇴사 / Boj 14889 스타트와 링크

yoonji/home/4/13/boj_1260.java, yoonji/home/4/13/boj_13023.java, yoonji/home/4/13/boj_14391.java, yoonji/home/4/14/boj_11724.java, yoonji/home/4/14/boj_1707.java
- 연결된 노드들에 한해서 큐가 채워지고 비워지기 때문에, 이를 기준으로 연결 요소 갯수를 ++합니다.
- 이분 그래프는 두 그룹으로 분할했을 시, 각 그룹 내에서 인접하면 안된다.
- 그래프 상 각 layer간 인접하면 안되므로, CHECKER를 이용해서 구분한다.
- 인접 노드 간 같은 CHECKER라면 이분 그래프가 성립되지 않는다.
- 이분 그래프 개념에 대해 다시 알게 되었습니다.
> 두 문제 모두 bfs로 풀었습니다.
=> yoonji: boj 11721 연결요소의 개수 / 1707 이분 그래프

chris-an/home/4.16/Boj_16929.java, chris-an/home/4.16/Boj_7562.java, chris-an/home/4.16/Boj_7576.java
앞에서 문제를 풀었던 거에서 살짝 변형해주면 되는 문제였습니다. 처음에는 매초마다 계속 루프를 돌리면서 시간 초를 누적 시키려고했는데,
복잡도가 굉장히 높아질 거 같다는 생각에 잘못된 접근인 걸 알았습니다.
그래서 qu에 익은 토마토의 좌표를 다 넣은  뒤, 최소시간을 구하는 방법으로 접근방식을 바꿔서 풀었습니다.
---
앞에서 풀었던 토마토 문제랑 비슷해서 쉽게 접근을 했지만, 
잘못된 접근을 했는데, 처음 생각에는 문제에서 최소의 이동 횟수를 구한다는 말에, target x,y 까지 갈 수 있는 이동 횟수가 여러 방법이라 생각을 해서 리스트에 이동 값을 다 넣어서 최소값을 구하려 했습니다. 그런데, 무한 루프를 돌았습니다.
그 이후에, 방문처리로 로직을 바꿔서 방문했던 곳은 가지 않도록 하고 bfs 를 돌려서, qu가 다 비었을 때 타겟좌표의 이동값을 뽑는 로직으로 변경했습니다.
> 의문이였던 건, 타겟좌표에는 무조건 도달하고 딱 한 가지 나온 값이 최소 값인가? 였습니다 그런데 검색하다보니 BFS 탐색은 모든 인접 정점을 최소 이동 횟수로 보장해주는 탐색 방식이며. 현재 정점 위치를 저장하고, 그 위치에서 8개의 방향으로 이동하며 목표 지점을 찾을 때까지 탐색을 수행하면 된다는 글을 보고 의문이 였던 점을 접기로 하였습니다.
---
처음 접근은 bfs 푸는 것처럼 좌표클래스를 만들어 Stack 을 이용하여 dfs 깊이 탐색을 시키다가, 첫 출발한 좌표값을 만나면 멈추는 식으로 만드는 방법으로 접근했습니다. 그런데 첫출발 그 1단계 이후에 방문처리 true로 되어, 마지막 부분에서 첫 촤표값을 만나지 …
=> Jungmin : Boj 7576 / Boj 7562 / Boj 16929

yoonji/home/4/19/boj_1697.java, yoonji/home/4/20/boj_14226.java
- `boolean`타입 방문 배열과 시간초 변수를 따로 두었는데,
방문 배열을 `int`로 두고 0이 아닌 값일 때는 이미 방문한 것으로 처리한다.
배열에 들어가는 값을 이전 위치에서 +1로 하여 cnt로 둘 수 있다.
- 따로 그래프를 생성할 필요 없이, 가능한 이동 X-1, X+1, 2*X 경우를 큐에 추가하면 된다.
- 위치값을 방문하면서 그때의 흐른 시간초를 넣어준다.
- 만약 배열에서 동생위치값이 0이 아닌 값이 있으면 바로 중지한다. (이미 최솟값으로 찾은 경우이니)
- 화면에 출력되는 이모지 갯수, 클립복드에 저장되는 이모지 갯수를 각 emojiN, clipboard 변수로 생성을 하였고,
이미 진행된 emoji갯수인지 체크하면서 시간초를 저장하는 배열도 1차원으로 진행해서 각 계산 시 상태를 모두 커버하지 못했다.
그래서 구글링하였고.. 수정한 부분은
1. 이모지 갯수들과 시간 초 값을 가지고 있는 클래스 추가
2. 화면 출력갯수와 클립보드 갯수를 인덱스로 하는 2차원 `boolean` 배열을 생성하여 이미 계산된적이 있는지 체크  <- 이것을 어떻게 떠올릴 수 있을까?
> 주석으로 추가했습니다.
=> yoonji: boj 1697 숨바꼭질 / 14226 이모티콘

yoonji/home/4/21/boj_1261.java, yoonji/home/4/21/boj_1991.java
- 로직 처리 중에는 문자를 숫자로 처리하고, 다시 정답을 반환 시에는 문자로 바꿔주었다. (`-64`, `+64`)
- `.`인 노드를 처음에 제거하거나 Null을 넣는 식으로 하려했는데, 그냥 방문할 때 조건 처리를 해주는게 더 간단한 것 같다.
- 후위, 중위, 전위 탐색에 대해 코드로 접근해본 적이 있어서 중점 로직 구현은 어렵지 않았다.
> 주석으로 추가했습니다.
- 방문했던 방에 대해 다시 방문할 수 있는 경우를 제외해줄 생각을 못했다. => 0과 1로 구성된 map 행렬의 값을 -1로 넣어주어 방문 처리를 한다.
- `0-1 BFS 알고리즘` (가중치가 0, 1로 주어진 그래프에서 최단경로를 찾아낼 수 있는 알고리즘) 개념을 알게되었다.
- 먼저 고려해주면 더 빨리 정답을 찾을 수 있는 경우를 **높은 우선순위**로 두어 로직을 처리하는 방법이다.
- `LinkedList` 타입을 `int`타입 배열로 지정할 수 있는 점
=> yoonji: boj 1991 트리순회 / 1261  알고스팟

yoonji/home/4/19/boj_2146.java, yoonji/home/4/22/boj_1167.java, yoonji/home/4/22/boj_2250.java
- 1에서 출발하여 가장 먼 노드를 찾고, 그 노드에서 다시 가장 먼 노드를 찾아서, 그중 최댓값의 길이가 지름이 된다.
- 언제 가중치 값을 비교하면 될지 몰랐던 점
> Q. 트리를 두번 탐색하지 않았을 때 문제되는 반례를 아직 찾지못해서 왜 두번 해줘야하는지 이해하지 못했다.
- 가장 왼쪽에 위치한 노드부터 x좌표가 정해지면 순차적으로 정해지므로, 중위순회가 알맞다.
- 중위순회를 하면서 
1. level 체크
2. 현재 x좌표 값이 현재 level에서 가장 왼쪽/오른쪽의 값인가? (각 level의 x좌표 min, max 값을 담을 배열 필요)
- parent, left, right를 프로퍼티로 갖는 Node 클래스 생성한다. (data는 ArrayList의 index로 대체 가능)
> 필요한 내용은 주석으로 추가했습니다.
- 다리를 짓는 로직에서, 바다가 시작될 때 (값이 0일 때) bfs 메서드를 호출하도록 했다.
=> 어떤 섬을 만나면 그 섬을 기준으로 섬일 때를 체크해야하므로 `2 이상일 때` bfs 메서드를 호출한다.
- 효율성을 항상 체크한다. 해당 문제에서는 크기가 100*100이 최대이니 효율성을 신경쓰지 않아도 되겠다는 생각을 하고 시작한다.
- 조건문을 체크하는 부분에서 시간을 많이 썼다.. (`setIslandNumbering`에서 바다인 경우 조건문을 따로 떼어서 체크한다.)
- 이중 for문으로 매 칸마다 bf를 호출하는 것이 비효율적으로 보이는 것 같긴 하다.
- 근데 visited를 왜 매번 재초기화해야하는지 모르겠다...
=> yoonji : boj 1167 트리의 지름 / 2250 트리의 높이와 너비 / 2146 다리만들기(추가)

chris-an/home/4.22/Boj_1167.java, chris-an/home/4.22/Boj_11725.java
테스트 케이스를 가지고 그림을 그리니, 이해는 금방 됐습니다.
그런데, 처음에 생각할 때, 기준이 1인 줄 알았습니다.. 그래서 기준 루트가 1인 상태에서 최대값을 구하니, 틀렸다고 나왔습니다....
잘못된 로직 설계를 했는데, 생각해보니 기준(루트) 가 없는 상태에서 지름이 최대인 길이를 구하는 문제였습니다.
다시 설계를 하기 위해서 하나하나 다 찾을까 했는데, 시간 복잡도 효율이 엄청 떨어질 거 같았습니다.
그래서 찾아보니, 트리의 증명에 대한 어느정도 정형화된 게 있었습니다.
1) _임의의 정점으로 부터 가장 먼 정점을 구한다._
2) _1에서 나온 정점으로 부터 가장 먼 정점을 구한다._
3) _1과 2에서 나온 정점간의 거리가 트리의 지름_
위와 같은 규칙을 가질 수 있는 건, 트리의 지름 귀류법 증명을 통해서 알수 있습니다.
어느 정도 문제를 이해해보니, 알면 쉽게 접근할 수 있었던 문제 였습니다.
---
처음에 인접리스틀르 만들어서 인접리스트 중 0번 째리스트를 뽑고, 1이 루트니깐 리스트 중 1이 들어 있는 경우에, 부모노드를 1로 출력할 수 있게 설계를 했더니, `틀렸습니다.` 라고 나왔네요...
역시 설계하고 구현할 때 주먹구구식인 거 같아 틀릴 거 같았는데.. 후
다시, 인접리스트를 bfs로 돌려서 구현했더니, 비슷하듯 아닌 다른 로직이라 통과가 됐습니다.
=> Jungmin : Boj 1167 / Boj 11725 / Boj 2250(~ing)

chris-an/home/4.25/Boj_16940.java, chris-an/home/4.25/Boj_16964.java
처음 문제 접근했을 때, 비슷하게 접근을 했지만, 구현 쪽에서 막혔습니다.
이번에 구현을 했을 때의 `index + count` 만큼 루프를 따로 돌려주는 방법으로 비슷한  로직을 
전에 다른 문제에서 적용한 기억이 있는데, 이 걸 잘 활용을 못했던 거 같습니다.
문제를 풀면서 정리한 건,
아래 부분을 신경 써서 문제를 구현해야 했던 문제 였습니다.
1. 시작 정점은 1이기 때문에 1이 아닌 다른 정점부터 시작하는 방문 순서는 올바르지 않습니다.
2. 간선은 양방향으로 저장
3. 같은 레벨에 있는 정점들의 순서만 중요합니다. 
4. 즉, 한 정점에서 이동하는 정점들과 다른 정점에서 이동하는 정점들의 순서가 섞이면 안 됩니다
---
BFS 문제와 동일하게 접근 하였습니다.
---
> 위 두 문제를 다시 풀어야할 거 같습니다. 방문 순서에 대한 문제여서 익숙해지면 다른 문제에 응용하기 좋을 거 같습니다.
=> Jungmin : Boj 16940 / Boj 16946

yoonji/home/4/09/boj_14051.java, yoonji/office/4/26/prg_방문길이.java
- Dynamic Programming을 이용해 해결한다.
- dp 배열은 **해당 상담일자까지의 누적 소득중 최댓값**으로 정의내린다.
- 이때 dp[i]는 MAX(i일자를 제외한 상담소득의 최댓값, i일자의 소득+i일자의 상담소요시간 이후의 일자의 최댓값)이다.
`dp[i] = Math.max(dp[i+1], schedule[1][i]+dp[nextConsultDate]`
✔️ 다음 상담일자가 만약 `N+1`보다 크다면 그다음 상담일자의 최대소득값으로 넣어줘야한다. (즉, 해당 일자의 소득값을 추가하지않는다.)
- dp 배열을 위와 같이 정의내리고 본인은 i=1일부터 구해나갔다.. BUT 마지막 상담일자부터 앞으로 구해나가야 최댓값을 구할 수 있다.
- 최댓값이라해서 무조건 증가하는 식으로 구하는게 아니라는 것을 느낀 문제였다. 
추가해야하는 조건은
- 해당 위치가 범위를 벗어나지 않는지 -> `isInBounds()`
- 해당 경로를 방문했는지  -> `checkVisited()`
- 어려웠던 점은, 점이 아닌, 선을 고려해야했는데 계속 점을 기준으로 생각하게 되어 오래 헤맸다.
-> 선을 고려하려면 출발 지점에 대한 정보를 무조건 넣어줘야 한다.
> 개인적으로 어렵게 느껴진 부분
> 두 정보를 모두 고려해야하는데 이때
> - 출발 지점의 왼쪽(위쪽)을 체크하고, 도착 지점의 오른쪽(아래쪽)을 체크해줘야한다는 점
> - 그 두개를 체크할 때 사이에 x 혹은 y값을 증가(감소)시켜야 한다는 점
=> yoonji: boj 14051 퇴사(DP) / prg 방문길이

chris-an/home/5.05/Boj_15658.java
앞선 문제 연산자 끼워넣기 로직에서 약간만 변형하면 된다고 생각했지만, 시간초과가 떴습니다.
이전 로직을 현 문제에 적용하여 수정한 로직은 44개의 연산자 중, 10개의 조합을 찾는 거라 24억이 넘어가, 시간복잡도가 높았습니다.
수정된 로직에서 큰 틀은 
1. dfs 에 recur 루프 도는 부분에서, `beforeOperators` 이전 연산자를 기억하게끔 하여, 이전 연산자가 동일하게 나올 시, pass 하게끔 합니다.
2. 원래는 recur 부분에서 연산작업을 depth N-1까지 하면서 루프를 돌다가, 목표 depth가 도달할 때, 최대 최소비교를 하였는데,  수정된 로직은 조합을 구하고 그 조합을 가지고 연산작업을 하게끔 바꿨습니다. (조합을 구하는 과정에서 중복은 recur를 x)
3. `operators` 연산자 배열을 미리 전역변수로 선언한 걸, 입력받은 연산자 갯수에 맞게끔 초기화를 할 수 있도록 로직 수정을 했습니다.
=> Jungmin : Boj 15658

jeongwoo/BackTracking/Boj9663.java
1. NxN 체스판에 퀸 N개를 서로 공격할 수 없게 놓는 경우의 수를 구해야 한다.
2. 공격할 수 없는 경우는 상하좌우, 대각선으로 이어진 직선상에 다른 퀸이 없어야 한다.
3. i행 arr[i]열에 퀸을 놓기 전에 상하좌우, 대각선을 보면서 놓을 수 있는지를 먼저 체크한다.
4. 놓을 수 있다면 재귀 호출.
=> Jeongwoo: BOJ 9663 N-Queen

yoonji/office/5/10/prg_점프와순간이동.java
- 처음에는 앞에서부터 `dp[i-1]+1`과 `dp[i/2]`의 min값으로 dp[i]를 구해갔다.
- TC에서 시간초과가 떠서 재귀로 시도했는데도, 마찬가지로 시간초과 떠서 다시 로직을 접근했다.
- 예제 3번째 값이 크길래 5000부터 /2와 -1을 하며 계산해갔고 규칙이 보였다.
- 재귀 그대로 가되, n부터 시작하도록 변경했다.
➕ `n`이 2보다 작거나 같은 경우 `recur` 메서드 자체를 호출하기전에 return하도록 했다.
=> yoonji: prg 점프와순간이동

chris-an/home/5.21/Boj_12886.java, chris-an/home/5.21/Sw_오목판정.java
처음에 설계를 할 때, dfs, bfs 둘 다 사용해야 한다고 생각했습니다.
`bfs` -> `dfs` -> `calculate` -> `bfs` -> `dfs` -> `calculate` ....
이렇게 로직을 돌게끔 설계를 했고, 구현했습니다.
구현 도중에 조합 dfs 에서 그냥 두 값만 뽑게끔 dfs를 구현 했는데,  세 그룹을 다 알고 있어야해서 dfs 로직을 visited 로 재 설계해서 세 수를 다 알 수 있게 로직 수정을 하였고.
다 구현 했을 때, 바로 통과가 안되고 로직확인이 필요했습니다. 
코드를 다시 확인하면서 부족했던 거 check 하면서 수정을 하니 통과됐습니다.
_로직 설계 부족했던 점_.
1. 무한루프. 문제에서 언급한 동일한 값이 아닌 크기가 다른 두 그룹이라는 글귀를 놓침
2. 메모리초과. 이 부분은 visited를 하나 만들어서 방문처리로 해결
3. 틀렸다고 뜸. 이 부분은 `1번`을 다르게 해석해서, qu에서 뽑을 때, a==b && a==c && b==c 는 continue 로 설계해서 설계 오류가 남.
> 시간은 많이 걸린 건 아니지만, 문제가 단순해서 대충 읽다가 잦은 실수가 많았습니다.
그리고 이번 문제는 더 쉽게 풀수 있을 거 같다는 생각이 들어, 리팩토링좀 해야할 거 같네요.
처음에는 bfs 로직인 줄 알고, 대충 머리로만 설계를 하고 구현했지만, bfs가 아닌 거 같아 그냥 for문으로 구현처리 했습니다.
처음에는 8방면을 하나하나 확인해줄까 했다가?
4루프 내에서 중심 앞뒤로 한 칸씩 확인하는 로직으로 구현했습니다. `isPossible` 부분.
=> Jungmin : Boj 12886 / SW 오목판정

chris-an/home/5.25/Boj_16946.java, chris-an/home/5.25/Boj_2206.java, chris-an/home/5.25/Boj_2206_failed_시간초과.java, chris-an/home/5.25/Sw_문자열나누기.java, chris-an/home/5.25/Sw_팔씨름.java
이번 문제는 알고리즘을 어떤 걸 사용해야 하는 지 고민을 계속 했던 거 같습니다.
DP? 인건가 아니면, 익숙하지 않아서 모르지만 그리디인건가? 그래서 그리디 문제도 보고 이것저것 찾아보았지만,
이번 문제를 어떻게 구현해야할지 정리가 안되서, 문제 그대로 생각하고 구현해보자고 생각하고
가정을 세워서 문제를 풀었습니다.
인접한 값이 같으면 안되니깐, 
인접한 값이 같을 시 문자열을 다음 인접한 값을 문자열에 추가하여 비교하고, 인접한 값이 다를 경우 count 하고? 이전 값을 현재값으로 초기화하면서 계속 반복해주었습니다.
여러가지 테케를 만들어서 해봤을 때, 계속해서 정답이 나와 바로 구현했습니다.
> 이번 문제는 알고 분류가 뭘까요..
이번 문제는 처음 로직을 구상하고 풀었을 때, 시간초과가 났습니다.
시간 초과가 나는 건, 벽을 하나 씩 빼가면서 bfs 를 돌려서 그랬습니다. (복잡도는 1000*1000..)
계속 생각하다가 생각이나질 않아, 찾아보니 다른 분들은 3차원 방문처리를 이용해서 푸는 걸 보고,
그걸로 다시 로직 설계를 했습니다.
로직 설계 중에 3차원 방문처리로 푸는 과정을 다 이해하지 않고 바로 구현을 했다보니 계속 틀렸다고 나왔네요.
놓치고 있던 부분은 3차원으로 할 때, 0,1을 구분을 해줘서 해당 Node가 crash를 했는 지 안했는지 여부에 따라, 구분지어 qu에 다 넣어서 bfs를 계속 돌려줘야 했었습니다.
> 3차원 boolean 배열을 이용해서, 이렇게 시간초과를 줄이는 방법을 알게 됐네요.
이번 문제는 전 문제를 풀어봐서 그런지, 보드에 있는 칸 하나씩 bfs를 돌리면 …
=> Jungmin : Sw 문자열나누기 (+팔씨름) / Boj 2206 / Boj 16946

chris-an/home/5.27/Boj_16954.java, chris-an/home/5.27/Boj_16954_2.java
처음 설계는 방문처리 없이, bfs를 돌리면서 벽이 행으로 한 칸 내려가게끔 board 내 벽 위치를 재 배치를 하면서 계속 루프를 돌려주는 식으로 코드를 짰습니다.  
첫 번째 맞이한 로직 상 오류는 board 값이 계속 변해서 class 내에 각 큐일 때, board 위치를 가지고 큐를 넣을 수 있게 코드를 수정이 필요했습니다. 하지만, 메모리 초과가 났습니다.
메모리 초과가 된 건, 1초에 벽이 한 번 씩 행으로 내려오는 경우를 안될 땐 들어가지 않게끔 예외 조건을 막아줘야하는데 제가 짠 로직 상 큐에 8방면을 다 집어 넣고, 빼면서 확인하는 로직이라 메모리 초과가 났던 거 같습니다.
이동할 때, 8방면에 벽 있는 지 check 도 해주고, 이 후에 벽이 재배치 했을 경우, 닿으면 안되는 상황까지 고려해서 큐에 집어 넣어야 했습니다. 그리고 각 상황에 맞게 벽이 얼마나 내려왔는 지 status 까지 알고 있어야 함으로, 문제가 더 까다로운데 단순하게 생각했던 거 같습니다.
수정된 로직은 board 의 재배치 없이 벽이 이동한 횟수를 방문체크와 class에 가지고 다니면서 bfs 돌리는 방식으로 구현했습니다.
>  두 번째로 commit 해서 올린 코드가 제가 처음 접근했던 코드와 유사합니다. 메모리 초과 됐던 부분을 for문 하나로 처리했으면, 수월하게문제가 풀렸을 거 같습니다..
=> Jungmin : Boj 16954 

yoonji/home/5/boj_14442_25.java, yoonji/home/5/boj_16933_26.java, yoonji/home/5/boj_16946_24.java, yoonji/office/5/26/prg_영어끝말잇기.java, yoonji/office/5/26/prg_캐시.java, yoonji/office/5/26/prg_피로도.java
* K-?개를 부수고 이동한 경로들 / 안부수고 이동한 경로들 중 가장 가까운 최솟값을 구하려면
* 각각의 방문처리를 따로 해줘야 한다.
* visited는 3차원으로, boolean[N][M][K+1] 어야 한다.
* 다 부수고 특정 칸에 먼저 도착해도, 이후에 N,M에 도달하지 못하는 경로일 수 있기 때문에!
* 아예 안부신 경우, K이고 부신 경우 그만큼 K-1
- 낮과 밤에 대한 상태 정보를 inner class에 추가해주었다.
- 벽을 만났을 때 밤에 대한 조건을 추가해주었다.
- 벽인 경우 -> 밤인 경우 -> 낮이 되려면 `이동횟수+2`를 해준 후, `큐`에 추가한다. 
---
- 기존에 내가 시도한 방법과 페어 중 진행한 방법, 두가지 모두 추가해놓았다.
- 해당 문제는 DFS로 풀었으며, 종료 조건은 `던전 길이만큼 들어온 경우`이다.
- 만약 dfs 내 for문 중간에 현재 피로도가 i의 `최소 필요 피로도`보다 작다면, 해당 탐험(?)을 depth로 하여 뒤에 이어질 경우의 수만 건너뛰면 되므로 `continue`하면 된다.
=> yoonji : boj 벽부수고 이동하기2,4, 3(추가 commit) / prg 피로도 & 캐시 & 영어끝말잇기

yoonji/Implementation/String/prg_모음사전.java, yoonji/Implementation/String/prg_순위검색.java, yoonji/Implementation/String/prg_후보키.java, yoonji/home/6/mono/prg_행렬테두리회전하기.java
- 정확성과 효율성 모두 체크해야하는 문제
1. 각 4개의 칼럼의 값들을 '-' 와 함께 섞어서 경우의 수를 모두 구한다. (dfs로 접근)
- 쿼리에서는 '-'인 경우 해당 칼럼을 고려하지 않는 것이고 여러 쿼리에 해당하는 지원자가 있을 수 있기 때문에 모든 경우의 수를 구할 때 '-'를 포함시킨다.
- 탐색하며 4자리가 완성되면 하나의 `String`으로 `map`의 key에 두고, value에는 코테 점수를 추가하도록 `ArrayList`로 선언한다. 
2. 모든 key의 value들에 대해 `sort` (왜 모든 key에 대해 진행해야하는지는 여전히 의문)
3. 인자 `query`를 돌면서 동일한 key값의 (정렬된) value들에 대해 이분 탐색으로 값을 찾는다.
> ➕ 추가
> 가능한 모든 query의 개수는 4 * 3 * 3 * 3 = 108가지이고, query는 최대 100000개 주어지는데, 쿼리는 중복될 수 있기 때문에 **정렬한 key를 재 정렬할 수도 있겠다.** 그러므로 어떤 경우에는 미리 정렬하는 것이 더 적은 경우의 수로 정렬이 이루어질 것이다.
- size(1부터)만큼 반복하면서 dfs를 호출한다. 
- size까지 depth가 들어갔다면 그때 후보키에 해당하는 칼럼의 필드를 `Set`에 넣으면서 중복성을 체크한다.(유일성) + 최소성을 고려해야한다. 
- 관건은 최소성이다. 최소성의 조건은 아래와 같다.
> 예제) 
> 0,1번째 칼럼이 후보키이고,  0,1,2번째 칼럼이 후보키이면  0,1번째 칼럼만 고려한다. (완전 포함되므로)
> 0,2번째 칼럼이 후보키이고, …
=> yoonji, jeongwoo: prg 순위검색/ prg 후보키(진행중) , yoonji : prg 모음사전

yoonji/DFSorBFS/goorm_숫자카드게임.java, yoonji/DFSorBFS/prg_메뉴리뉴얼.java
- IDE 없이 1시간 이상 소요
- 사전순 정렬이어서 모두 정렬을 하려하니 복잡했는데, `우선순위 큐`를 사용하니 깔끔해졌다.
- 처음에 배열 `orders` 원소들을 순회하며 정렬을 하고 시작했는데, `HashMap`에 추가할 때 정렬해서 넣어주는 식으로 바꿨더니 더 적은 수의 데이터를 정렬할 수 있었다.
- 정렬 조건이 조금 많이 들어간 정도인데도 복잡하게 느껴졌다.
=> yoonji : prg 메뉴리뉴얼

jeongwoo/문자열/Pro17677.java
처음에는 교집합과 합집합을 arrayList로 접근해서 교집합에 들어가는 문자열, 합집합에 들어가는 문자열을 다 넣어 주었다.
그러다 보니 합집합에 교집합이 중복될 때의 경우가 다 들어가지 않았다.
그래서 교집합을 개수로 구하고, str2는 교집합들을 다 삭제했다.
교집합을 다 구하고 나면 str2에는 교집합이 없는 문자열들만 있다.
합집합은 str1 개수 + str2만 가지고 있는 문자열 개수로 구할 수 있다.
=> 2022-08-03 프로그래머스 17677 뉴스 클러스터링

yoonji/Implementation/prg_뉴스클러스터링.java
> IDE 없이 40분 진행
- 각 String에 대해 조건에 맞는 길이가 2인 집합을 `HashMap`의 key로 두고, value로 등장 횟수를 넣었습니다.
- 둘 중 하나의 집합만 돌면서, 동일한 원소가 있을 경우
- 교집합에는 두 `HashMap`의 value 중 최솟값을, 합집합에는 최댓값을 더해주고, 나머지 하나의 집합에 해당 key를 제거했습니다.
- 다 돌고 나면 나머지 집합 1개에 있는  동일하지 않은 원소들의 등장 횟수를 모두 합집합에 더해줍니다.
=> yoonji : prg 뉴스클러스터링

yoonji/Implementation/prg_스킬트리.java
- `skill`의 순서는 Map 자료구조로 0부터 넣어주었습니다.
- `skill_trees`의 원소를 순회하며 Map의 key에 있는 스킬번호이면 if문을 통해 조건처리하였습니다.
=> yoonji : prg 스킬트리
